### ISSUE TITLE
How to include images not generated by R code in the final website?

### ISSUE THREAD

**Issue by aa-m-sa** [workflowr/workflowr#103]
I'd like to add markdown image links to images not generated by the R code in my analysis, like this:
``
![title](path/to/image/file.png)
``

What is the officially sanctioned way to do this? Copying the images into the relevant `docs/figure/(...)/` and committing them into the git repository manually apparently is not (because it seems that they are overwritten when I run `wflow_publish()`).

**Comment by jdblischak** [comment]
Great question, @aa-m-sa. I had previously given advice on this in Issue #37. After seeing your new issue, I went back and updated that old thread https://github.com/jdblischak/workflowr/issues/37#issuecomment-387744317

> I'd like to add markdown image links to images not generated by the R code in my analysis, like this:
`![title](path/to/image/file.png)`

Yes, this is possible. My recommendation is below. I'll make a note to remind myself to add this question to the [FAQ page](https://jdblischak.github.io/workflowr/articles/wflow-05-faq.html).

> What is the officially sanctioned way to do this? Copying the images into the relevant `docs/figure/(...)/` and committing them into the git repository manually apparently is not (because it seems that they are overwritten when I run `wflow_publish()`).

Here's my recommendation:

1. Create an assets directory to include any file that should be part of the website but is not created by the R Markdown files in `analysis/`:
    ```
   dir.create("docs/assets")
    ```
1. Move the image files to `docs/assets`
1. In the R Markdown file, refer to these images using the relative path from `docs/` (because this is where the HTML files are located):
    ```
   ![](assets/external.png)
    ```
1. Run `wflow_build()` to confirm the external image was properly added
1. Use `wflow_git_commit()` to commit the files to the Git repo (so that they get pushed to GitHub)
    ```
   wflow_git_commit("docs/assets/external.png", "Add external image of ...")
   # If you are adding multiple files, you could use a file glob
   wflow_git_commit("docs/assets/*.png", "Add external images of ...")
    ```
1. Run `wflow_publish()` on the R Markdown file that contains the external image(s)

Please let me know if you like this solution or if you have other ideas.

**Comment by aa-m-sa** [comment]
Thanks, the suggested solution seems to work fine. (Of course it would be smoother if you wouldn't need to remember to `wflow_git_commit()` the images, but this works, so I'm closing the issue.)

**Comment by jdblischak** [comment]
@aa-m-sa Glad that works for you.

> Of course it would be smoother if you wouldn't need to remember to wflow_git_commit() the images

In general `wflow_publish()` only automatically commit files that it creates itself (e.g. the image files created by the R Markdown files) since it knows exactly where they are saved. Any other files in the directory need to be committed manually by the user. To remove a step, you could pass the custom image files directly to `wflow_publish()`. As an example, if `file.Rmd` uses PNG images in `docs/assets`, you could skip `wflow_git_commit()` and instead run `wflow_publish(c("analysis/file.Rmd", "docs/assets/*png"), "Commit message.")`

Thanks for using workflowr!

**Comment by ditordccaa** [comment]
I'm trying to insert an external image using the method described in the [FAQ](https://jdblischak.github.io/workflowr/articles/wflow-05-faq.html). The image is not rendered though.

![path](https://user-images.githubusercontent.com/58598645/75716324-f7c8b180-5c9c-11ea-93fe-a68cf0ef3ffc.png)
![image1](https://user-images.githubusercontent.com/58598645/75716340-fdbe9280-5c9c-11ea-91ea-eef8f9c02037.png)

Am I doing something wrong here?

Thanks!

**Comment by jdblischak** [comment]
The URL to the image has to be relative to the final HTML file, which will be in `docs/`. So it should start with `assets/`. In your case it will be:

```
knitr::include_graphics("assets/nps.png")
```

Note that a downside of this approach is that the image won't preview inside the Rmd editor in RStudio. But it will be there in the HTML.

**Comment by ditordccaa** [comment]
So I've changed the code 
```{r npsImage, include=TRUE, echo=TRUE, out.width="400px", out.height="400px"}
library(knitr)
knitr::include_graphics("assets/nps.png")
```
Now when I build the website I get
```
library(workflowr)
> cat(getwd())
D:/workspace/projects/workflowProject
> wflow_build('analysis/*.Rmd')
Current working directory: D:/workspace/projects/workflowProject
Building 3 file(s):
Building analysis/descriptive.Rmd in C:/ProgramData/LecteurD/workspace/projects/workflowProject
Build failed. See log files for full details.
stdout: C:/Users/dqa5242/AppData/Local/Temp/1/Rtmpa0zq4S/workflowr/descriptive.Rmd-2020-03-02-15h-59m-48s-out.txt
stderr: C:/Users/dqa5242/AppData/Local/Temp/1/Rtmpa0zq4S/workflowr/descriptive.Rmd-2020-03-02-15h-59m-48s-err.txt

  |                                                                            
  |........................................................              |  80%
label: npsImage (with options) 
List of 4
 $ include   : logi TRUE
 $ echo      : logi TRUE
 $ out.width : chr "400px"
 $ out.height: chr "400px"
Error: callr subprocess failed: Cannot find the file(s): "assets/nps.png"
```
The workflowr version I'm using is 1.6.0

**Comment by jdblischak** [comment]
Try using the markdown syntax instead (outside of a code chunk):

```
![](assets/nps.png)
```

Apparently using `include_graphics()` used to work: https://github.com/jdblischak/workflowr/issues/162#issuecomment-489768758. I'm not sure what happened.

**Comment by jdblischak** [comment]
I confirmed that this usage of `include_graphics()` was broken in knitr version 1.28. It works fine in 1.27.

**Comment by ditordccaa** [comment]
![](assets/nps.png) works. 
I know see the images rendered.
Thanks @jdblischak

**Comment by jdblischak** [comment]
I figured it out. That error you received is new behavior. You have to set `error = FALSE` for `include_graphics()` to work with workflowr.

https://github.com/yihui/knitr/issues/1717#issuecomment-583373829

**Comment by ditordccaa** [comment]
Yes definitely. I was looking at that at the moment and I saw that you've already mentionned it :D. Cool
I saw that the 1.28 changes were mainly with the `include_graphics()` function.

**Comment by jdblischak** [comment]
I updated the docs in commit f4bedd0
