### ISSUE TITLE
Error in wflow_git_push()

### ISSUE THREAD

**Issue by zihao12** [workflowr/workflowr#108]
Hi John,

In my laptop, I follow the instructions on https://jdblischak.github.io/workflowr/articles/wflow-01-getting-started.html until Deploy the website, when I get an error:
`Error: Push failed for unknown reason.

The error message from git2r::push() was:

Error in 'git2r_push': SSL error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert
protocol version`

when doing wflow_git_push(). I redo what I have done on rcc midway through cloud rstudio and does not get an error. Then I clone the repository to my laptop and still get the same error when I try to wflow_git_push(). Any suggestions? Is there some git configurations I get wrong?

**Comment by pcarbo** [comment]
@jdblischak Note that @zihao12 said that `git push` worked for the same repo in terminal on his laptop. Also, he gets the same error in both R and RStudio.

**Comment by jdblischak** [comment]
OK, great. Since your using macOS, this might be easier to solve (since macOS has common compilers installed, unlike Windows).

Try to compile git2r directly on your machine by running the following:

```
install.packages("git2r", type = "source")
```

If that doesn't fix the issue, then the easiest way forward for the time being would be to run `git push` in the Terminal when updating your workflowr project on your local laptop.

In the future, this should be fixed with the next release of git2r. Unfortunately that simple fix is being held up because git2r is being overhauled (in a backwards-incompatible manner), so it may be awhile before that happens.

**Comment by jdblischak** [comment]
And for more context, the reason that `wflow_git_push()` is failing on your local machine is because it is using the libgit2 package that is bundled with git2r, and this is using the TLSv1.1 protocol. `git push` in the Terminal works because the native install of Git uses TLSv1.2. `wflow_git_push()` works on RStudio Server on Midway because that is running on Linux, and thus is also using TLSv1.2.

The hope is that by compiling libgit2 from source on your local machine, it may be linked to the TLSv1.2 protocol.

**Comment by zihao12** [comment]
This does not work, but still thanks! Will git push in terminal have the same effect as wflowr_git_push?

**Comment by jdblischak** [comment]
> This does not work, but still thanks!

Yeah, I didn't have high hopes. Since this step relies on so many system libraries, it can be difficult to troubleshoot. For what it's worth, `wflow_git_push()` works for me on macOS 10.10.5.

> Will git push in terminal have the same effect as wflowr_git_push?

Yes. `wflow_git_push()` is a convenience function for running `git push` directly from the R console. It also is a replacement in the situation in which a user does not have Git installed. Since you already have Git installed on your machine, you can use it instead.

**Comment by pcarbo** [comment]
@jdblischak For the time being maybe `wflow_git_push` could suggest running `git push` upon failure? (And provide some info that this function may not work on all computers.)

**Comment by jdblischak** [comment]
@pcarbo Good idea. I suggest that for the known failures, so it makes sense to also do it for an unknown failure. Fixed in 2cb83c503fa702ce62130654d61d9fea48606852
