### ISSUE TITLE
Cannot open connection to child documents

### ISSUE THREAD

**Issue by timtrice** [workflowr/workflowr#111]
Before reporting your bug, please search the existing issues (both "open" and "closed") to check that a similar bug has not already been reported.

1. Give the exact command or line of code you ran that caused the issue, e.g., `wflow_publish("myanalysis.Rmd")`.

Two files in analysis directory, "about.Rmd" and "test.Rmd". 

`test.Rmd` contents:

```
# Test
```

`about.Rmd` contents (4-space indentation added):

```
    ---
    title: "About"
    output:
      workflowr::wflow_html:
        toc: false
    ---

    Describe your project.

    ```{r, child = "analysis/test.Rmd"}
    ```

```

`wflow_build()` fails with error given below. Other variations I have tried:

    ```{r, child = "test.Rmd"}
    ```

    ```{r, child = "./analysis/test.Rmd"}
    ```

2. Describe the result of running the command or code, including any warning or error messages.

```
 Error: cannot open the connection 
```

Traceback:

```
7. stop(e$message, call. = FALSE) at wflow_build.R#395
6. value[[3L]](cond) 
5. tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
4. tryCatchList(expr, classes, parentenv, handlers) 
3. tryCatch(callr::r_safe(build_rmd, args = list(rmd, seed, ...), 
    stdout = stdout_file, stderr = stderr_file, show = verbose), 
    error = function(e) {
        message(wrap("Build failed. See log files for full details.")) ... at wflow_build.R#381
2. build_rmd_external(f, seed = seed, log_dir = log_dir, verbose = verbose, 
    envir = .GlobalEnv) at wflow_build.R#258
1. wflow_build() 
```

Output of stderr:

```
Error in readLines(if (is.character(input2)) { : 
  cannot open the connection
Calls: withCallingHandlers ... FUN -> knit -> readLines -> .handleSimpleError -> h
In addition: Warning message:
In readLines(if (is.character(input2)) { :
  cannot open file 'C:/Users/TIM~1.TRI/AppData/Local/Temp/RtmpwRT71b/test.Rmd': No such file or directory
Execution halted
```

3. Tell us about your computing environment, including the version of R, RStudio and workflowr you are using. The simplest way to do this is to run `sessionInfo()` in R (and `RStudio.Version()` if you are using RStudio) and copy the output here.

**R version 3.5.1 (2018-07-02)**

**Platform:** x86_64-w64-mingw32/x64 (64-bit) 

**locale:**
_LC_COLLATE=English_United States.1252_, _LC_CTYPE=English_United States.1252_, _LC_MONETARY=English_United States.1252_, _LC_NUMERIC=C_ and _LC_TIME=English_United States.1252_

**attached base packages:** 
_stats_, _graphics_, _grDevices_, _utils_, _datasets_, _methods_ and _base_

**other attached packages:** 
workflowr(v.1.1.1)

**loaded via a namespace (and not attached):** 
_Rcpp(v.0.12.17)_, _crayon(v.1.3.4)_, _assertthat(v.0.2.0)_, _digest(v.0.6.15)_, _rprojroot(v.1.3-2)_, _R.methodsS3(v.1.7.1)_, _R6(v.2.2.2)_, _backports(v.1.1.2)_, _git2r(v.0.22.1)_, _magrittr(v.1.5)_, _evaluate(v.0.10.1)_, _stringi(v.1.2.3)_, _rstudioapi(v.0.7)_, _callr(v.2.0.4)_, _R.oo(v.1.22.0)_, _R.utils(v.2.6.0)_, _rmarkdown(v.1.10)_, _tools(v.3.5.1)_, _pander(v.0.6.2)_, _stringr(v.1.3.1)_, _glue(v.1.2.0)_, _processx(v.3.1.0)_, _yaml(v.2.1.19)_, _compiler(v.3.5.1)_, _htmltools(v.0.3.6)_ and _knitr(v.1.20)_

**Comment by pcarbo** [comment]
@timtrice Did you mean `wflow_publish("about.Rmd")`? It appears to be related to the fact that `rmarkdown::render("about.Rmd")` also does not work with child documents. This may not be a well supported knitr feature. 

If you can get `rmarkdown::render` to work with child documents, please let us know, as that will be helpful for fixing this issue in workflowr.

**Comment by pcarbo** [comment]
@timtrice Thank you for sharing. I see now; `rmarkdown::render` changes the output settings based on `_site.yml` in the same directory. If I run `rmarkdown::render("default.Rmd",output_format = "html_document")`, for example, in the `analysis` directory, it works.

So it appears that `workflowr` (specifically, `workflowr::wflow_html`) currently does not work with [child documents](https://yihui.name/knitr/demo/child), and perhaps other knitr processing steps that involve files. This will have to be a feature we incorporate into a future release of workflowr.

So for now, perhaps @jdblischak can suggest a workaround.

**Comment by jdblischak** [comment]
@timtrice Thanks for reporting this. We do need to think about child documents and whether or not they can be supported by workflowr. The issue is that workflowr expects a 1:1 relationship between Rmd and HTML file, and child documents break that pattern.

> So it appears that workflowr (specifically, workflowr::wflow_html) currently does not work with child documents, and perhaps other knitr processing steps that involve files.

@pcarbo Correct. `workflowr::wflow_html` creates a temporary version of the R Markdown file with the reproducibility report and other chunks inserted. The code still runs correctly because the knit directory (`knit_root_dir`) is still set to the R Markdown directory of the workflowr project. The child document fails because knitr looks in the directory where the file is located (in this case the temporary directory), and not where the code is being executed.

@timtrice Could you please share your use case for child documents? What are you trying to accomplish? Are you sharing a custom function across documents?

> I have not used the wflow_publish function; My typical publishing workflow has been either knitting (Ctrl+Shift+K) or wflow_build(). Either way gets the error.

@timtrice Would you be able to share one of your workflowr projects so that we can better understand how you are using workflowr? Thanks!

**Comment by jdblischak** [comment]
@timtrice Thanks for the reprexes! Very helpful.

I'm currently traveling, and the hotel I am currently at has garbage wifi. I'll investigate this next week once I return (I should be able to respond by Wed at the latest).

**Comment by jdblischak** [comment]
@timtrice I have potential solutions. As I mentioned above, the issue is due to the difference between the location of the R Markdown file (`analysis/`) and the working directory when the code in the file is run (default is the root of the project file).

One solution would be to update the path to the child document to be relative to the root of the project, e.g.:

    ```{r, child = file.path("analysis", "01_child.Rmd")}
    ```
and

    ```{r, include = FALSE}
    src <- lapply(
      month.name, 
      FUN = function(x) {
        knitr::knit_expand( 
          file = file.path("analysis", "02_child.Rmd"),
          title = x
        )
    })
    ```
This will work. The main downside is that the code will break if you change the value of `knit_root_dir` in `_workflowr.yml` or the name of the subdirectory with the R Markdown files. To make it more robust, you can access the location of the original R Markdown file using `knitr::opts_knit$get("output.dir")` (I realize this is confusing, the knitr `output.dir` is to the location of the R Markdown files. It is only after the HTML file has been created there that the value of `output_dir` in `_site.yml` is used by rmarkdown to move the HTML file to `../docs`).

    ```{r, child = file.path(knitr::opts_knit$get("output.dir"), "01_child.Rmd")}
    ```
and

    ```{r, include = FALSE}
    src <- lapply(
      month.name, 
      FUN = function(x) {
        knitr::knit_expand( 
          file = file.path(knitr::opts_knit$get("output.dir"), "02_child.Rmd"),
          title = x
        )
    })
    ```
Lastly, workflowr expects every R Markdown file in the R Markdown directory to be a primary analysis file (i.e. create a viable HTML file that is part of the website). Thus to keep using the workflowr functions (e.g. `wflow_build()`, `wflow_status()`, `wflow_publish()`), you will want to move the child documents to a subdirectory, e.g. `analysis/external`.

    ```{r, child = file.path(knitr::opts_knit$get("output.dir"), "external", "01_child.Rmd")}
    ```
and

    ```{r, include = FALSE}
    src <- lapply(
      month.name, 
      FUN = function(x) {
        knitr::knit_expand( 
          file = file.path(knitr::opts_knit$get("output.dir"), "external", "02_child.Rmd"),
          title = x
        )
    })
    ```

I modified your RStudio Cloud project and saved it as a new project: [workflowr-sample-project-01-proposed-solution](https://rstudio.cloud/project/50538). Please test it out and let me know if this proposed solution works for you.

**Comment by lazappi** [comment]
I wonder if this could be addressed by using the `here` package in some way https://cran.r-project.org/web/packages/here/index.html? It's designed to help with these kinds of problems by providing a consistent file path. Just thought I would mention it in case you haven't seen it before.

**Comment by timtrice** [comment]
John, this works and I appreciate your help on this. This will make it much easier to manage my company's project in addition to some other projects I'd like to incorporate. 

Do you think it would be helpful if I turned this issue into a vignette? I'd be hard pressed to think I'm the only one who chooses to use child documents.

**Comment by timtrice** [comment]
@lazappi `here::here` is indeed another working solution and possibly a bit cleaner than the file.path call. The [third reprex](https://rstudio.cloud/project/50538) has been updated to add 03_parent.Rmd which uses `here`.

**Comment by jdblischak** [comment]
> I wonder if this could be addressed by using the here package in some way https://cran.r-project.org/web/packages/here/index.html?

Yes, great suggestion @lazappi!

> John, this works and I appreciate your help on this. This will make it much easier to manage my company's project in addition to some other projects I'd like to incorporate.

@timtrice Great! I'm glad this solution works for your use case.

> Do you think it would be helpful if I turned this issue into a vignette? I'd be hard pressed to think I'm the only one who chooses to use child documents.

Yes, I think a vignette on sharing across documents is a good idea. In addition to child documents, I'd also like to include the strategy for sharing common functions by `source`ing an R script.

How involved would you like to be in the creation of this vignette? Would you like to write the section on child documents, or would you rather just review/modify something that I write?

**Comment by jdblischak** [comment]
> The third reprex has been updated to add 03_parent.Rmd which uses here.

@timtrice Just an FYI that I don't think this worked. I don't see `03_parent.Rmd` in https://rstudio.cloud/project/50538. My guess is that you didn't choose the option "Save a Permanent Copy", so your changes were lost.

**Comment by timtrice** [comment]
John, I'd be happy to write as much as I can and you can fill in the gaps/trim it as you see fit.

Regarding `source`, can you elaborate a bit? I only have a functions file in the <underline>code</underline> directory which I `source` from many of my reports. These run just fine for me. For example, 

```r
source(file.path(".", "code", "functions.R"))
```

Is this what you are referring?

Regarding the last demo, I'll leave it alone. We'll cover that the vignette.

**Comment by jdblischak** [comment]
> John, I'd be happy to write as much as I can and you can fill in the gaps/trim it as you see fit.

@timtrice Great! I'll create a new vignette with a basic outline and then let you know when it's ready for you to modify.

> Regarding source, can you elaborate a bit? I only have a functions file in the code directory which I source from many of my reports. These run just fine for me. For example,
>
> source(file.path(".", "code", "functions.R"))
>
> Is this what you are referring?

Yep! That's also how I share functions across R Markdown files.

> Regarding the last demo, I'll leave it alone. We'll cover that the vignette.

Sounds good!

**Comment by jdblischak** [comment]
@timtrice I started a vignette on sharing common code in the dev branch:

https://github.com/jdblischak/workflowr/blob/dev/vignettes/wflow-07-common-code.Rmd

Please let me know if you need any advice on submitting a pull request to the dev branch.

Also, a thought about how to document this implementation. I was very paranoid in my above examples by using `file.path()` for everything. This was because I wanted to make sure I could get child documents to work. However, I think that may be overkill, especially since using `file.path()` makes the code so much more verbose. I'd recommend the instructions show how to use a relative path, e.g. use `"code/common.R"` if the knit directory is the project root, and use `"../code/common.R"` if the knit directory is the R Markdown directory.

And finally, thanks for your help improving workflowr!

**Comment by jdblischak** [comment]
@timtrice As always, thanks for the reproducible example to help with troubleshooting.

>  I have found that images generated from within child documents are not moved back into the working directory from the temporary directory

I think we should distinguish between the two different strategies you are using to share code across documents. One is using child documents using the syntax below, which gets processed by `knitr::knit_child`:

    ```{r parent-chunk, child=here::here("analysis/child/child.Rmd")}
    ```

In contrast, the example you show above passes chunks as text directly to `knitr::knit` within the R Markdown file (not sure what to call this strategy). The fact that the chunks get generated by `knit_expand` isn't important for this issue with the figures.

Unfortunately, both of these strategies have problems with figure paths.

The child document problem seems really tough to solve. If `analysis/child/child.Rmd` contains the following chunk to create a figure:

    ```{r child-chunk}
    hist(1:10)
    ```

then that figure is saved to `analysis/figure/child.Rmd/child-chunk.png`. Any other figures produced by chunks in the parent document are saved as `analysis/figure/parent.Rmd/<chunk-name>.png`. This difference is due to the fact that `knitr::current_input()` changes inside of the child R Markdown file (which is used by workflowr's [figure hook](https://github.com/jdblischak/workflowr/blob/1c1c72d3d36ee48fefe7f883ed18cfe2c2b89d9a/R/wflow_html.R#L159)). When `workflowr::wflow_site` goes to move figures to `docs/`, it only looks in `analysis/figure/parent.Rmd/`, and then deletes `analysis/figure` ([source](https://github.com/jdblischak/workflowr/blob/1c1c72d3d36ee48fefe7f883ed18cfe2c2b89d9a/R/wflow_site.R#L89)).

For the second strategy that calls `knit` directly in the R Markdown file, the problem is that `knit` doesn't know where the R Markdown file originally was (since it was only passed text). Thus it defaults to using the current working directory, which by default for workflowr projects is the root directory. These figures end up being saved in `figure/<basename>.Rmd/<chunk-name>.Rmd`, when they need to be saved to `analysis/figure/<basename>.Rmd/<chunk-name>.Rmd`. This can be fixed by specifying the knitr package-level option in the plotting chunk:

    ```{r define-plot-chunk-as-text}
    chunk <- "```{r knit-from-within}
    knitr::opts_knit$set(base.dir = \"analysis\")
    plot(1:10)
    ```"
    ```
    
    `r knitr::knit(text = chunk)`

Unfortunately this is quite hacky. A simpler option would be to change `knit_root_dir` in `_workflowr.yml` to `"analysis"` so that all code in the R Markdown files is executed in the R Markdown directory. I could also explore trying to set `base.dir` inside of of the output format function `wflow_html`.

Here's an [RStudio Cloud project](https://rstudio.cloud/project/53266) for more experimenting. The file `analysis/knit.Rmd` demonstrates how to fix the figure path for running `knit` inside of an R Markdown file. The files `analysis/parent.Rmd` and `analysis/child/child.Rmd` reproduce the naming figure path issue with child documents. Please check them out and let me know your thoughts.

**Comment by timtrice** [comment]
After playing around with this some more and changing the `knit_root_dir` option to "analysis", all of the examples work without any additional hacks. I can call files from the code and data dir without issues. Now I'm kind of feeling like I made a big fuss about nothing.

So, my question is, what is wrong or what issues could potentially develop by just making "analysis" the root dir?

**Comment by timtrice** [comment]
Same results. So, basically, best I can tell for now, we can remove that option or set it to "analysis"; either way is fine. But, using `file.path` will fail. I haven't tried `output_dir` yet. 

[Here's the latest example](https://timtrice.github.io/workflowr_child_docs/). (And, might I add that being able to see previous versions of even the images I find a wonderful feature!)

Edit: missed your first question; I hadn't changed it before so `knit_root_dir` was set to default "."

**Comment by jdblischak** [comment]
> So, my question is, what is wrong or what issues could potentially develop by just making "analysis" the root dir?

@timtrice There's nothing wrong with this approach. Its main downside is that it is inflexible. The workflowr functions are designed such that they can handle any value for `knit_root_dir` that is set in `_workflowr.yml`. I was hoping to find a solution here so that a user could use child documents with any value for `knit_root_dir`, but that clearly isn't going to be trivial.

And another advantage of setting `knit_root_dir: "."` is that you don't have to change the working directory after opening the RStudio project (which is why that is the default for new workflowr projects).

**Comment by jdblischak** [comment]
P.S. I prefer setting `knit_root_dir: "analysis"` over deleting the field entirely from `_workflowr.yml`. While they have the exact same result, the former is more transparent (especially for those less familar with the workflowr framework).

**Comment by jdblischak** [comment]
> And, might I add that being able to see previous versions of even the images I find a wonderful feature!

@timtrice Great! I also really enjoy this feature since it makes the typically difficult task of viewing past versions accessible to anyone with a web browser.

**Comment by jdblischak** [comment]
@carlmurie Thanks for the help!

I was skeptical this would be any different than specifying the `child` chunk option. Although the Markdown result is identical, it saves the figures correctly. I confirmed that it works when `knit_root_dir` in `_workflowr.yml` is set to `"."`, `"analysis"`, or `"data"`. The only potential concern is that if `knit_root_dir` is not `"analysis"`, knitr sends the following warning:

```
Warning message:
In in_dir(input_dir(), inline_exec(block)) :
  You changed the working directory to /cloud/project/analysis (probably via setwd()). It will be restored to /cloud/project. See the Note section in ?knitr::knit
```

But using `getwd()`, I confirmed that this does not effect the code execution in the parent or child document. I updated my previous RStudio Cloud  project [figs-in-child](https://rstudio.cloud/project/53266) with the file `analysis/knit_child.Rmd`. Hopefully this change is saved, but if not the file contains the following:


    ```{r parent-fig}
    knitr::current_input()
    plot(1:10)
    getwd()
    ```
    
    Use `knit_child` instead of speciying the child in a chunk:
    
    ```{r parent-chunk-name}
    library(readr)   ## read_file
    child1 <- here::here("analysis/child/child.Rmd")
    childy <- read_file(child1)
    ```
    
    `r paste(knitr::knit_child(text = childy), collapse = '\n')`
    
    ```{r getwd}
    getwd()
    ```

@timtrice Could you please evaluate this option to see if it works for your use case? I like it since it does not force the user to choose a specific directory for code executation.

**Comment by timtrice** [comment]
Apologies for late response; been very hectic. I'll look at @carlmurie's example and another example I've come across in recent days as soon as I can.

**Comment by timtrice** [comment]
I finally spent some time playing with @carlmurie's solution. The solution is best when simply including child documents without parameters. However, if you want to pass variables to the child document, it becomes a bit messy, at least for my preferences. 

I'm going to close this issue as I feel the best way to include child documents (with and without parameters) are those demonstrated in [workflowr_child_docs](https://github.com/timtrice/workflowr_child_docs/). This requires setting the `knit_root_dir` to "analysis" in the _workflowr.yml file. [As mentioned](https://github.com/jdblischak/workflowr/issues/111#issuecomment-411497849), it may have some limitations though, for the time being, I've yet to uncover them. 

Will readdress should anything change.

**Comment by jdblischak** [comment]
> I'm going to close this issue as I feel the best way to include child documents (with and without parameters) are those demonstrated in workflowr_child_docs. This requires setting the knit_root_dir to "analysis" in the _workflowr.yml file. As mentioned, it may have some limitations though, for the time being, I've yet to uncover them.

@timtrice Great! I'm glad you found a workable solution. Do you still have any interest in helping write some documentation for sharing code across analysis files in a workflowr project?

Here's the link to the vignette skeleton I initially created:

https://github.com/jdblischak/workflowr/blob/dev/vignettes/wflow-07-common-code.Rmd

**Comment by timtrice** [comment]
@jdblischak, the first draft of the vignette has been pushed to my fork if you'd like to review.

https://github.com/timtrice/workflowr/blob/dev/vignettes/wflow-07-common-code.Rmd

**Comment by jdblischak** [comment]
@timtrice Could you please send a PR with your current draft of the vignette? I'm preparing for the next release of workflowr, and I'd like this new vignette to be included. If you send the PR, I'll merge it and then make the changes I requested above. Thanks for your help with this!
