### ISSUE TITLE
fig.path option is overridden

### ISSUE THREAD

**Issue by lazappi** [workflowr/workflowr#114]
workflowr overrides the knitr `fig.path` option. It's not a big deal because where it puts things is fairly reasonable but it might be possible to use the existing value if it has been set. If not it would be nice to produce a message/warning so that it's clear to the user what is happening.

**Comment by pcarbo** [comment]
@lazappi If I correctly understand what you are saying, the `fig.path` knitr option cannot (or should not) be used within a workflowr project. So if the user tries to set `fig.path`, a warning or error should be generated? I suppose we could add a check for this in workflowr… @jdblischak Do you think this is possible?

**Comment by lazappi** [comment]
Yeah I guess so. Basically the user setting `fig.path` doesn't do anything because workflowr overwrites it but not sure what kind of behaviour you want workflowr to have.

**Comment by jdblischak** [comment]
@lazappi Would you be interested in the user being able to configure this? It would be possible to allow this to be configured in `_workflowr.yml`. Do you have a specific use case in mind? It is critical that workflowr knows where the figures are saved so that it can commit them and link to past versions.

I'll investigate whether it's possible for workflowr to detect if `fig.path` is set by the user.

**Comment by pcarbo** [comment]
@jdblischak I'm not sure there is a simple way for it to work all the time, but checking the value of `opts_chunk$get("fig.path")` would be part of the solution.

**Comment by jdblischak** [comment]
For documentation, the figure location is currently mentioned in two places. Briefly in the [getting started vignette](https://jdblischak.github.io/workflowr/articles/wflow-01-getting-started.html):

> Each of these figures is saved according to the following pattern: `docs/figure/<insert Rmd filename>/<insert chunk name>-#.png`...

And in more detail in the section [Where are the figures?](https://jdblischak.github.io/workflowr/articles/wflow-04-how-it-works.html#where-are-the-figures) in the vignette [How the workflowr package works](https://jdblischak.github.io/workflowr/articles/wflow-04-how-it-works.html).

To improve the documentation, I propose mentioning in both of these places that a consequence of this behavior is that `fig.path` set by the user is ignored. Thoughts?

The warning message is tougher. To detect that the user has set a custom `fig.path`, this has to be run while the file is being knit. I can check in the current chunk hook function [hook_fig_path](https://github.com/jdblischak/workflowr/blob/a69257e13bf0238e0c61594d786230c97cdbcd24/R/wflow_html.R#L158) to see if `fig.path` differs from the rmarkdown default of `"<basename-sans_ext>_files/figure-html/"`. However, any warning message will be inserted directly into the HTML file. The warning would certainly get the user's attention since it will be displayed after every chunk with a plot (that is if they set `fig.path` globally). Thoughts?

**Comment by pcarbo** [comment]
> The warning would certainly get the user's attention since it will be displayed after every chunk with a plot (that is if they set fig.path globally). 

@jdblischak I think that would still be effective.

**Comment by lazappi** [comment]
> To improve the documentation, I propose mentioning in both of these places that a consequence of this behavior is that fig.path set by the user is ignored. Thoughts?

I think that would be a good idea, that way is somebody is wondering what is going on they should be able to find the answer. Warnings would definitely make that obvious as well I guess, but maybe without as much detail

**Comment by jdblischak** [comment]
@lazappi This feature is now available in [workflowr 1.2.0](https://github.com/jdblischak/workflowr/releases/tag/v1.2.0).
