### ISSUE TITLE
Integration with flexdashboard and other special cases

### ISSUE THREAD

**Issue by ohofmann** [workflowr/workflowr#115]
Thanks for workflowr, this looks like an excellent environment to unify some of the ongoing research projects!

I've stumbled into one issue when trying to add RMarkdown code to a project that generates specific HTML output. E.g., RMarkdown's dashboards (https://rmarkdown.rstudio.com/flexdashboard/) get wrapped into workflowr output and cease to render as expected. 

Is there a way to keep these files as part of a workflowr project, but knit them as-is? Alternatively, could they be excluded and rendered through the command line without the workflowr wrapper?

**Comment by jdblischak** [comment]
> Thanks for workflowr, this looks like an excellent environment to unify some of the ongoing research projects!

@ohofmann Of course! Thanks for your interest!

> I've stumbled into one issue when trying to add RMarkdown code to a project that generates specific HTML output. E.g., RMarkdown's dashboards (https://rmarkdown.rstudio.com/flexdashboard/) get wrapped into workflowr output and cease to render as expected.

Right, so flexdashboard uses its own custom output format [flex_dashboard](https://www.rdocumentation.org/packages/flexdashboard/versions/0.5.1.1/topics/flex_dashboard). This conflicts with workflowr's custom output format [wflow_html](https://www.rdocumentation.org/packages/workflowr/versions/1.1.1/topics/wflow_html).

> Is there a way to keep these files as part of a workflowr project, but knit them as-is? Alternatively, could they be excluded and rendered through the command line without the workflowr wrapper?

I think the best approach will to keep the source R Markdown files separate, and then move the dashboard HTML file to the `docs/` subdirectory so that it is included as part of the website.

I created a [RStudio Cloud project](https://rstudio.cloud/project/53341) to demo a proof-of-concept. The dashboard is defined in `dashboard/dashboard.Rmd`, and the R script `dashboard/build-dashboard.R` builds the HTML file and then moves it to `docs/`. You could potentially also automate the committing of the Rmd and HTML files in the R script, or you could do these steps manually. Please try it out and let me know what you think.

**Comment by jdblischak** [comment]
@ohofmann Great! I'm glad that works for your use case.

In case it'd be useful for any future workflowr user, below I document the proposed solution:

1. Create a separate top-level subdirectory, e.g. `dashboard`, to save the R Markdown dashboard file:

```
project
├─analysis
├─dashboard
└─docs
```

2. Create an R script that builds the dashboard and moves it to the `docs/` subdirectory so that it is included in the website:

```
#!/usr/bin/env Rscript

# Run this script from the root of the workflowr project to add the dashboard to the workflowr website.

library(rmarkdown)
render("dashboard/dashboard.Rmd")
file.rename("dashboard/dashboard.html", "docs/dashboard.html")
```

3. Manually add and commit `docs/dashboard.html` and then push online
