### ISSUE TITLE
Sourcing R files in code folder

### ISSUE THREAD

**Issue by sdhutchins** [workflowr/workflowr#127]
I dont know if I am doing something wrong but when running an analysis or `wflow_build`, I cannot source any R file in the code folder.

It'd be really beneficial to do this.

**Comment by jdblischak** [comment]
> when running an analysis or wkfl_build, I cannot source any R file in the code folder.

@sdhutchins Sorry to hear workflowr is not working as you expected. Are you trying to use the `source()` function from within an R Markdown chunk to load code from an R script saved in the `code/` subdirectory? If yes, this is possible. For example, the line below would load all the code in a hypothetical file `code/external-code.R`.

```
source("code/external-code.R")
```

Please let me know if this is what you are trying to accomplish or if you had a different goal in mind.

**Comment by sdhutchins** [comment]
Thanks for the prompt response, @jdblischak! I tried it on a different project, and it worked beautifully. Seems there was an unrelated issue in this particular project.

**Comment by jdblischak** [comment]
> Thanks for the prompt response, @jdblischak! I tried it on a different project, and it worked beautifully. 

@sdhutchins Of course! I'm glad it's working now.

> Seems there was an unrelated issue in this particular project.

My guess is that the knit directory was changed for this project. You can check if `knit_root_dir` is set in the file `_workflowr.yml`, and a good sanity check is to run `getwd()` inside of a code chunk in your R Markdown file to determine where the code is executing. For example, if the knit directory is `analysis/`, then the relative path to the R script would be `source("../code/external-code.R")`.

I'm going to close the issue since it seems like your problem has been resolved, but if you send me the link to the GitHub repo for the problematic project, I'd be happy to try and diagnose the problem.
