### ISSUE TITLE
Integrate pre-rendered shiny_documents

### ISSUE THREAD

**Issue by rsimon64** [workflowr/workflowr#130]
Interactive documents would be neat for integration. Tried the following example. Almost works but it seems that some css files are missing.

---
title: '50'
author: "My Name"
date: "10/31/2018"
output: html_document
runtime: shiny_prerendered
---

```{r setup, include=FALSE, context="setup"}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
```

```{r eruptions, echo=FALSE, context="render"}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)

```

```{r}
plotOutput("distPlot")
```

```{r eruptions_plot, echo=FALSE, context="server"}
output$distPlot <- renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```

**Comment by jdblischak** [comment]
@rsimon64 Thanks for the suggestion! The reason the CSS doesn't work is because `runtime: shiny_prerendered` requires the static files to be in a different directory structure compared to R Markdown websites.

https://rmarkdown.rstudio.com/authoring_shiny_prerendered.html#external_resources

A few questions to better understand your use case:
1. How do you plan to deploy your workflowr website?
1. Have you considered deploying your Shiny app with shinyapps.io and then embedding it inside the R Markdown file via `iframe`, e.g. with [`knitr::include_app()`](https://www.rdocumentation.org/packages/knitr/versions/1.20/topics/include_url)?

**Comment by jdblischak** [comment]
@rsimon64 Thanks for starting this discussion about Shiny apps. I updated the FAQ in commit 5237c18 to document how to use `knitr::include_app()`, which I think is currently the best method for embedding Shiny apps in workflowr websites. If you have further ideas, please feel free to open a new issue.
