### ISSUE TITLE
Possible inclusion of themes from `prettydoc`

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#133]
Hi John -- I hope you had a great holiday!

I wonder whether it is possible to include the additional html themes from `prettydoc` package (<https://cran.r-project.org/web/packages/prettydoc/vignettes/architect.html>) in `workflowr`.

If too many implementation efforts are needed, I am still very happy with all the existing themes provided by `rmarkdown`: <https://bookdown.org/yihui/rmarkdown/html-document.html#appearance-and-style>

**Comment by jdblischak** [comment]
@xiangzhu Thanks for the suggestion! This is related to #126. The problem is that the workflowr reproducibility features are implemented using an output format (`wflow_html()`) that extends the default `rmarkdown::html_document()` function. One possibility that I am exploring is to refactor `wflow_html()` so that it can be more easily integrated with other output formats (this is what @docmanny did with `blogdown::html_page()`).

However, there is a second problem. These lightweight themes purposefully avoid using Bootstrap. This is an issue because the navigation bar of R Markdown websites (and soon also the workflowr report) rely on Bootstrap. Thus I don't think it will be easy to create even a simple R Markdown website using `prettydoc` themes or any other theme that does not load Bootstrap.

**Comment by xiangzhu** [comment]
Thanks for the explanation!

As a user I am happy with the existing themes available in `rmarkdown`. Please feel free to close this issue.

**Comment by jdblischak** [comment]
@xiangzhu Sounds good!
