### ISSUE TITLE
Remove requirement that `wflow_open` specify a filesystem path

### ISSUE THREAD

**Issue by CreRecombinase** [workflowr/workflowr#135]
1. Describe the suggested feature.

It might be cool if in addition to calling `wflow_open` like this:
```
wflow_open("analysis/new_analysis.Rmd")
```
I could just do this:
```
wflow_open("new_analysis")
```
2. Describe why you think this feature is needed.

 Right now (as far as I'm aware) the only "correct" place you can create a workflowr document is in the `analysis` folder, and the only permissible file type is R markdown (`.Rmd` or `.rmd`), so making the user specify all of that seems unnecessary.  The other reason I think this might be nice is that the notion of "working directory" can be a pretty confusing concept, especially for beginners; an interface like this doesn't require knowledge of the working directory (or the file system at all!).  If you think this is reasonable I'd be happy to submit a PR

3. Tell us the version of workflowr you are using. Run `packageVersion("workflowr")` in R or RStudio, and copy & paste the output here.
`1.1.1`

**Comment by CreRecombinase** [comment]
Now that I'm thinking more about it, because workflowr projects have a more or less fixed structure, you could also have something like `wflow_data("data.csv")`, which would return `../data/data.csv` (and maybe also records the size, modification time, etc?)

**Comment by pcarbo** [comment]
@CreRecombinase We have thought a lot about this---in short, we are worried that allowing for shortcuts such as those you suggest will also add to confusion about working directories (a subject  that many people already find very confusing).

**Comment by jdblischak** [comment]
> Right now (as far as I'm aware) the only "correct" place you can create a workflowr document is in the analysis folder, and the only permissible file type is R markdown (.Rmd or .rmd), so making the user specify all of that seems unnecessary.

@CreRecombinase Thanks for sharing your thoughts! I agree with your points. In fact, the first implementation of `wflow_open()` behaved exactly as you describe. Since the file could only go one place, I had `wflow_open()` discard the initial filepath and only use the basename. This behavior is preserved in [workflowrBeta](https://github.com/jdblischak/workflowrBeta).

> The other reason I think this might be nice is that the notion of "working directory" can be a pretty confusing concept, especially for beginners; an interface like this doesn't require knowledge of the working directory (or the file system at all!). If you think this is reasonable I'd be happy to submit a PR

Agreed! That was my initial motivation. I wanted to make `wflow_open()` smart enough that it "just worked" no matter what the working directory was. The problem is that the other workflowr functions can't be that smart. Functions like `wflow_publish()`/`wflow_git_commit()` can accept Rmd and non-Rmd files and need to pass them properly to Git. Also, most workflowr functions now accept file globs. For these reasons, most of the functions require that the user is passing the correct file path. Since only a minority of the functions were able to make these simplifying assumptions (e.g. `wflow_open()` and `wflow_view()`), we decided that API consistency was more important. Currently all the main workflowr functions have the same first argument: a character vector of file paths that may or may not include globbing patterns.

I hope that helps explain how we arrived at the current behavior. Happy to continue the discussion if you have more thoughts on this.

**Comment by jdblischak** [comment]
Also see this Issue thread for related discussion on the updated behavior of `wflow_open()`: https://github.com/jdblischak/workflowr/issues/107#issuecomment-402208943

**Comment by CreRecombinase** [comment]
@pcarbo @jdblischak I think the interface (and motivation) for what I'm proposing is slightly different from how `wflow_open()` worked in `workflowrBeta`, in that under what I'm proposing, a valid filename outside of `analysis` would still throw an error unless combine with`project=NULL`.  As I think more about this, I've come to the conclusion that consistency between `wflow_publish`, `wflow_open` and `wflow_git_commit` is actually a little misleading, in that the argument `files` means subtly different things for each function. 

 `wflow_git_commit` does pretty much exactly what it says on the label, and the argument `files` gives a good indication of what what it will do: I can predict what  `wflow_git_commit(a)` vs `wflow_git_commit(b)` will do, it will commit files `a` or files `b`.  

The meaning of the `files` argument in `wflow_publish` however, changes based on:
 1) the location of the file (`wflow_publish("foo/code.Rmd")` just commits while `wflow_publish("analysis/code.Rmd")` commits, builds and commits again) 
2) the extension of the file (`Rmd` triggers a build, `html` doesn't, and `yml` doesn't, but probably should).

If instead the argument to `wflow_publish` was  something like`wflow_objects` (bad name), which takes either:
1) A string that contains neither `/` nor a file extension, which is interpreted as corresponding to one or several "analysis objects" (because you could still allow globbing), which are treated as  `.Rmd` files.  
2) A valid file path, in  which case you get the current behavior of `wflow_publish`
3) the output of some helper function which controls the inputs to `wflow_publish` and had a signature like:
```
wflow_ls <- function(all=TRUE,update=FALSE,republish=FALSE)
``` 
The helper function would also be nice in that accomplishing the behavior that `all`, `update` and `republish` control in `wflow_publish` can all be expressed by changing the inputs to `wflow_publish`

**Comment by jdblischak** [comment]
> I think the interface (and motivation) for what I'm proposing is slightly different from how wflow_open() worked in workflowrBeta, in that under what I'm proposing, a valid filename outside of analysis would still throw an error unless combine withproject=NULL.

@CreRecombinase Thanks for giving this so much thought!

> As I think more about this, I've come to the conclusion that consistency between wflow_publish, wflow_open and wflow_git_commit is actually a little misleading, in that the argument files means subtly different things for each function.

Agreed that they all have slightly different behavior.

> the extension of the file (Rmd triggers a build, html doesn't, and yml doesn't, but probably should).

I purposefully don't trigger a build on a change to either `_workflowr.yml` or `_site.yml`. In theory I agree this should be done, but in practice users often have some files with very long running code or other reasons they don't want to rebuild the entire site. The documentation always recommends including `republish = TRUE` when editing either of these configuration files, but users are free to only update the files they want (the results in the unchanged files are still reproducible since they contain the commit that was used to create them).

> If instead the argument to wflow_publish was something likewflow_objects (bad name), which takes either:
>
>    A string that contains neither / nor a file extension, which is interpreted as corresponding to one or several "analysis objects" (because you could still allow globbing), which are treated as .Rmd files.
>    A valid file path, in which case you get the current behavior of wflow_publish
    the output of some helper function which controls the inputs to wflow_publish and had a signature like:
>
> wflow_ls <- function(all=TRUE,update=FALSE,republish=FALSE)
>
> The helper function would also be nice in that accomplishing the behavior that all, update and republish control in wflow_publish can all be expressed by changing the inputs to wflow_publish

This is really interesting approach! My worry is that it is just as confusing (or more) than the current approach. It would allow the first argument of `wflow_publish()` to accept either a file path, a character string representing an Rmd file (kind of like a slug of a blog post), or a special function.

Whereas the current behavior is to accept character vectors of valid file paths and/or globs. The user only needs to remember that Rmd files go through the 3-step process, but anything else is only committed. In fact, one way to think about workflowr is that it is just Git with a special hook for any file that matches the pattern `analysis/.+\.Rmd$`.

But while we continue to discuss `wflow_publish()`, let's not forget to continue discussing `wflow_open()`. How critical of a function is this for you? i.e. do you run it often? Do you use it primarily to create new files, open existing files, or both?

**Comment by pcarbo** [comment]
> As I think more about this, I've come to the conclusion that consistency between wflow_publish, wflow_open and wflow_git_commit is actually a little misleading, in that the argument files means subtly different things for each function.

@CreRecombinase Could you give a specific example where you find the specification of the `files` argument in these functions to mean different things? As far as I know, `files` is the same in each function (*i.e.*, they must be pathnames of files on your computer relative to your working directory). It is true that the functions do different things with these files, but that relates to the name of the function, not the name of the argument.

**Comment by CreRecombinase** [comment]
> consistency between wflow_publish, wflow_open and wflow_git_commit is actually a little misleading, in that the argument files means subtly different things for each function.

@pcarbo @jdblischak I think "misleading" was the wrong choice of word here.  I originally brought it up to make the point that the the way I think about the consistency between 2 APIs has more to do how well they "go together" than whether they have similar signatures.
 
>> the extension of the file (Rmd triggers a build, html doesn't, and yml doesn't, but probably should).

> I purposefully don't trigger a build on a change to either _workflowr.yml or _site.yml. In theory I agree this should be done, but in practice users often have some files with very long running code or other reasons they don't want to rebuild the entire site. The documentation always recommends including republish = TRUE when editing either of these configuration files, but users are free to only update the files they want (the results in the unchanged files are still reproducible since they contain the commit that was used to create them).

That totally makes sense to me.

> to accept either a file path, a character string representing an Rmd file (kind of like a slug of a blog post), or a special function

I get that it seems like a lot (and maybe it is), but if you think about the `file` argument to `read.table`, or `write.table`, they both can accept a lot of things that are conceptually "table-formatted data" without actually being file paths. 

>  let's not forget to continue discussing wflow_open(). How critical of a function is this for you? i.e. do you run it often? Do you use it primarily to create new files, open existing files, or both?

I only ever use `wflow_open` to start new analyses, and I suppose it's not critical for me as I sometimes   just start a new R markdown file in RStudio and copy the header from an old file.  To know that that will work though, requires understanding more about  how `workflowr` works than is maybe strictly necessary? (though you guys do a really good job of explaining this through documentation and error messages) 

I think the main point I wanted to make is that while I think that the "git + hooks" model is a good way of thinking about `workflowr` from an implementation perspective, there's a lot more to the user experience of `workflowr` than that.  `git`, `knitr` and github pages are all very flexible, powerful tools. So flexible in fact that in when combined in general, the only common abstraction they all share is that of the file.  From that perspective, I can totally see why an API based strictly on file paths makes the most sense.  One of the things that excites me the most about `workflowr` though, is that because it's more opinionated about both set up and use-case than either git,  R markdown, or github pages, that it is able to (in theory) expose abstractions that might be more relevant, and more accessible, to a much wider user base.

**Comment by CreRecombinase** [comment]
Yeah that totally sense, thanks for hearing me out!
