### ISSUE TITLE
Global chunk options for all rmd files

### ISSUE THREAD

**Issue by LSun** [workflowr/workflowr#137]
Hi John and Peter,

Am I allowed to set global chunk options for all .rmd files in `analysis/` by modifying `_workflowr.yml` or some other file?

Right now I'm including the following R code chunk in every .rmd file involving R coding:

    ```{r global_options, include = FALSE}
    knitr::opts_chunk$set(warning = FALSE, message = FALSE)
    ```

Any change I can change some files so that I'll include it only once?

Thank you.

**Comment by pcarbo** [comment]
@LSun It is a simple question with a not-so-simple answer. Part of the issue is that there are rmarkdown options and there are knitr options, and these were developed in separate stages, so the overall interface is convoluted. 

I believe that the simplest solution is to create a separate `.R` file containing the chunk options. The old version of workflowr had a nice example of this. @jdblischak?

**Comment by jdblischak** [comment]
> Am I allowed to set global chunk options for all .rmd files in analysis/ by modifying _workflowr.yml or some other file?

@LSun Good question. Currently we leave sharing chunk options to the standard methods provided by knitr. Using one of these methods will make it easier to update the options (i.e. you'd only have to update one file), but you'll still need to have a boilerplate chunk at the top of every R Markdown file.

We are working on a vignette to document [how to share code across R Markdown files](https://github.com/jdblischak/workflowr/blob/dev/vignettes/wflow-07-common-code.Rmd), but it's not ready yet. I've considered allowing the specification of knitr options in `_workflowr.yml`, but this can get really convoluted really quick (since there are multiple places to specify these options, which ones take precedence? And other problems).

## Option 1: Source a shared R file

You could create a file `shared.R` somewhere, e.g. `code/shared.R`. It would include any shared code to execute for each R Markdown file, in this case:

```
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

Then at the top of each R Markdown file you would put the following chunk (assuming the knit directory is set to `analysis/`:

    ```{r global_options, include = FALSE}
    source("shared.R")
    ```

## Option 2: Import a file with shared code chunks

If you want modularize which code chunks a given file executes, and change the order in the document they are executed, you can use [code externalization](https://yihui.name/knitr/demo/externalization/). To do this, you create a shared R file, e.g. `code/chunks.R`. The syntax is to start each chunk with `# ---- name-of-chunk ----`:

```
# ---- global_options ----
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

# ---- last-updated ----
<insert other R code here>

```

The at the top of each R Markdown file, you load the chunks:

    ```{r shared-chunks, include = FALSE}
    knitr::read_chunk("../code/chunks.R")
    ```

But they haven't been executed yet (which is what would have happened with `source()`. Instead, you put the name of the chunk you want to execute later in the document (in your case you'd want to put the chunk at the beginning to change the chunk options):

    ```{r global_options, include=FALSE}
    ```

This is the strategy that [workflowrBeta](https://github.com/jdblischak/workflowrBeta) uses. The shared chunks are in [chunks.R](https://github.com/jdblischak/workflowrBeta/blob/master/inst/infrastructure/analysis/chunks.R), and the [R Markdown template loads them](https://github.com/jdblischak/workflowrBeta/blob/master/inst/rmarkdown/templates/analysis/skeleton/skeleton.Rmd).

**Comment by jdblischak** [comment]
@LSun Curious about your experience. Do any of these options seem better than the others? Or are they all more trouble than they're worth? :-)

**Comment by LSun** [comment]
Hi John, 
Thank you for asking. I ended up adding the following chunk in the beginning of almost every .rmd file.
```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```
Previously I thought there was a way to add something in one of the .yml files to achieve that, but since there wasn't, I guess the most straightforward and non-intrusive way for me would be to add that code chunk manually.
What do you think?

**Comment by jdblischak** [comment]
> I guess the most straightforward and non-intrusive way for me would be to add that code chunk manually.

@LSun Agreed. Since it's only one line of code, there's no need to get too complicated. And with RStudio's `Find in Files...` feature, it is easy to update many files.

**Comment by LSun** [comment]
Oh I didn't know that feature. Thank you. Now it's even better.
