### ISSUE TITLE
workflowr 1.2.0 breaks collapse=TRUE knitr option

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#149]
I'm attaching an example that can be used for testing. 

The most likely culprit is `cache_hook`, a chunk hook that that was added in 1.2.0.

[test.Rmd.gz](https://github.com/jdblischak/workflowr/files/2958200/test.Rmd.gz)

**Comment by jdblischak** [comment]
@pcarbo Thanks for reporting.

The function `cache_hook()` is used as the [output hook applied to all chunks](https://yihui.name/knitr/hooks/#output-hooks). If no caching is used, it should have no effect.

I had inspected this default hook by running the following in the R console:

```
knitr::knit_hooks$get("chunk")
## function (x, options) 
## x
## <environment: namespace:knitr>
```

It simply returns `x`, which is what `cache_hook()` does if no cache is detected. However, this hook gets updated based on the output format of the document. Thus from within an R Markdown document that uses `rmarkdown::html_document()` as the output format, it is the following:

```
## function (x, options) 
## {
##     x = gsub(paste0("[\n]{2,}(", fence, "|    )"), "\n\n\\1", 
##         x)
##     x = gsub("[\n]+$", "", x)
##     x = gsub("^[\n]+", "\n", x)
##     if (isTRUE(options$collapse)) {
##         x = gsub(paste0("\n([", fence_char, "]{3,})\n+\\1(", 
##             tolower(options$engine), ")?\n"), "\n", x)
##     }
##     if (is.null(s <- options$indent)) 
##         return(x)
##     line_prompt(x, prompt = s, continue = s)
## }
## <bytecode: 0x55d69c459d70>
## <environment: 0x55d69c45e720>
```

Because the behavior of `collapse` is implemented in the chunk output hook, only it is affected (and not other chunk options) by overwriting the default output hook.

Thus the solution is to update `cache_hook()` to first execute this default code. The problem is that knitr is GPL'd and the function is not exported. It is defined inside of the function `render_markdown()`:

https://github.com/yihui/knitr/blob/master/R/hooks-md.R#L159

I haven't been able to come up with a clever way to extract it. The long-term solution would be to refactor this function and export it from knitr.

**Comment by pcarbo** [comment]
@jdblischak Thanks for the update. Sorry it is so complicated to fix.

**Comment by jdblischak** [comment]
@pcarbo I'm glad you found it! That default function appears to have multiple purposes, including also implementing the behavior of `indent`. As much as possible, I want `wflow_html()` and `html_document()` to produce the same output, and this is a clear example where that no longer happens.

**Comment by pcarbo** [comment]
See  Issue #153 for another example.

**Comment by jdblischak** [comment]
@JiaxiangBU Could you please see if my fix on the dev branch fixes the problem for you? 

```
devtools::install_github("jdblischak/workflowr@dev")
```

**Comment by pcarbo** [comment]
@jdblischak Your fix works for me; see [here](https://github.com/stephenslab/wflow-divvy/blob/f832d7c4078c2e6f4e305d70ea57bb6f2e97ed6c/docs/test.html).

**Comment by jdblischak** [comment]
@pcarbo Thanks!
