### ISSUE TITLE
duplicate unnamed chunk bug?

### ISSUE THREAD

**Issue by stephens999** [workflowr/workflowr#15]
I get the following error when running:
`wflow_commit(commit_files="MH-examples1.Rmd")`
Rendering MH-examples1.Rmd

Error in parse_block(g[-1], g[1], params.src) : 
  duplicate label 'unnamed-chunk-1'

none of my chunks are labelled, so something must be going wrong under the hood?

**Comment by jdblischak** [comment]
Could you please send me the file via the slack #workflow channel?

This SO post may be helpful for fixing the issue: [How to nest knit calls to fix duplicate chunk label errors?](http://stackoverflow.com/questions/17535227/how-to-nest-knit-calls-to-fix-duplicate-chunk-label-errors)

**Comment by stephens999** [comment]
it is here: https://github.com/stephens999/fiveMinuteStats/blob/master/analysis/MH-examples1.Rmd

you might try cloning the repo and seeing if you can reproduce it?

**Comment by jdblischak** [comment]
I couldn't replicate the error. All of the following worked for me:

* The RStudio Knit button
* RStudio run all chunks
* `wflow_build()`
* `wflow_commit(commit_files="MH-examples1.Rmd")` (after making a small edit)

**Comment by stephens999** [comment]
i got the same problem again with a different file so it was not a one off.
I think this may be something to do with differences in my typical workflow vs yours...
(maybe my routine use of the knit button to render?)

**Comment by jdblischak** [comment]
@xiangzhu also got this error. His workaround was to explicitly name all the chunks. Still not sure what is causing this issue.

> I got the following error:
>
> ```
>   Error in parse_block(g[-1], g[1], params.src) : 
>     duplicate label 'unnamed-chunk-1'
> ```
> it seems that the error disappear after i add chunk names ...

**Comment by jdblischak** [comment]
Yesterday I tried to produce this error using the latest dev version (https://github.com/jdblischak/workflowr/commit/56c75fae16619ac5333eb7570f6cf445f4f4b722) but was unsuccessful. I used macOS, tried different combinations of named and unnamed chunks (with and without setting chunk options), and rendered the file repeatedly switching back and forth between the RStudio "Knit HTML" button, `wflow_build`, and `wflow_publish`.

If you continue receiving this error, please keep sending updates to the Issue so that we can determine if there is any pattern.

**Comment by jdblischak** [comment]
@stephens999 @xiangzhu Have either of you had this duplicate label bug happen recently?

**Comment by xiangzhu** [comment]
@jdblischak  I have not come across this type of error since the one reported on May 2017.
