### ISSUE TITLE
Add `NEWS.md`

### ISSUE THREAD

**Issue by JiaxiangBU** [workflowr/workflowr#150]
1. Describe the suggested feature.
2. Describe why you think this feature is needed.

In the file structure of `devtools` to build an R package, the document `NEWS.md` helps the existing users of a project to check something updated. Would you think about it and add it in the `workflowr` project setting?

3. Tell us the version of workflowr you are using. Run `packageVersion("workflowr")` in R or RStudio, and copy & paste the output here.

``` r
packageVersion("workflowr")
#> [1] '1.2.0'
```

<sup>Created on 2019-03-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jdblischak** [comment]
> In the file structure of devtools to build an R package, the document NEWS.md helps the existing users of a project to check something updated. Would you think about it and add it in the workflowr project setting?

@JiaxiangBU Thanks for the suggestion! In my experience, workflowr users do not use version numbers for their data analysis projects. Instead, most use the Git history as the changelog. I definitely encourage you to keep your updates as organized as possible, but I don't think this is a common enough use case to automatically add to every workflowr project, especially since it is straightforward for a user like yourself to add the file `NEWS.md` manually.

Also, since a workflowr project creates a website, it might make more sense to create `analysis/news.Rmd`. This would create `docs/news.html`, and readers could look through the notes you have made directly in the website. There's no need to limit yourself to a markdown file on GitHub.

Thoughts?

**Comment by JiaxiangBU** [comment]
@jdblischak I agree with you, seemingly `NEWS.md` is an option for the users. But Does the `NEWS.Rmd` is better than `NEWS.md`? for this question, 
I do some research.
the `devtools` considers `NEWS.md` because it displays it in the Github instead of Github Pages. 
And even though the package `pkgdown` uses `NEWS.md`, it displays the news content in a `NEWS.html` document.

I think I get your point, I close this issue, thanks for your sharing of your thought.

**Comment by jdblischak** [comment]
> But Does the NEWS.Rmd is better than NEWS.md?

@JiaxiangBU This is a personal preference. If you want it to be easily readable from the GitHub repo, it makes more sense to use `NEWS.md` and put it in the root of your project. If you want it to be easily readable from your workflowr website, it makes more sense to save it as `analysis/NEWS.Rmd` so that its HTML is included in the website.

To make the NEWS file more prominent in your workflowr website, you can add it to the navigation bar in `_site.yml`:

```
navbar:
  title: "title"
  left:
  - text: Home
    href: index.html
  - text: About
    href: about.html
  - text: License
    href: license.html
  - text: News
    href: NEWS.html
```

And then you could update the navigation bar across the entire site using:

```
wflow_publish("analysis/_site.yml", republish = TRUE)
```

**Comment by JiaxiangBU** [comment]
@jdblischak This is useful, thanks for your tips.
