### ISSUE TITLE
Add a feature for table of content. 

### ISSUE THREAD

**Issue by JiaxiangBU** [workflowr/workflowr#151]
1. Describe the suggested feature.

I find the other rmd document in the directory `analysis` doesn't have a button on the GitHub pages.
Is there a way to add a toc for them?

2. Describe why you think this feature is needed.

It helps the readers of that pages search and read.

3. Tell us the version of workflowr you are using. Run `packageVersion("workflowr")` in R or RStudio, and copy & paste the output here.

```
> packageVersion("workflowr")
[1] ‘1.2.0’
```

**Comment by jdblischak** [comment]
> I find the other rmd document in the directory analysis doesn't have a button on the GitHub pages.
Is there a way to add a toc for them?

@JiaxiangBU Thanks for the suggestion! I actually had a function that did something like this in a very early version of workflowr, but I deprecated it since no one was using it.

The current advice ([here](https://jdblischak.github.io/workflowr/articles/wflow-01-getting-started.html#add-a-new-analysis-file)) is to manually link the other analyses in `analysis/index.Rmd`. For example, if you have an analysis in `analysis/example.Rmd`, then you could add the following text to `analsyis/index.Rmd`:

```
Click [here](example.html) for my analysis of...
```

But I'd consider creating a new function, that e.g., creates a markdown-formatted list of all the published analyses for the project (and optionally add it to `analysis/index.Rmd`). Would that be useful for you?

**Comment by JiaxiangBU** [comment]
Hi, @jdblischak thanks for your quick reply.

> creates a markdown-formatted list of all the published analyses for the project (and optionally add it to analysis/index.Rmd). Would that be useful for you?

Yes, I think it is helpful, now I just write a quick function to build a table to include all documents in the `analysis` folder.  Still wait for your new function, that's cool.

**Comment by jdblischak** [comment]
> Yes, I think it is helpful, now I just write a quick function to build a table to include all documents in the analysis folder. Still wait for your new function, that's cool.

@JiaxiangBU If you've already written a quick function, would you like to contribute it to workflowr for use by others? Since you're using this functionality, you're the best person to know how to make it convenient for other users. I can help mentor you on the process of adding your function to workflowr and contributing via Git/GitHub. Interested?

**Comment by JiaxiangBU** [comment]
@jdblischak, sorry for the late reply, yeah, I'm interested. I will fork it and build a new pull request. Just when I complete it, I will let you know.

**Comment by jdblischak** [comment]
@JiaxiangBU Great! Please read [CONTRIBUTING.md](https://github.com/jdblischak/workflowr/blob/dev/CONTRIBUTING.md) and let me know if you have any questions. Especially important is to make your new commits on the dev branch with `git checkout dev`.

**Comment by JiaxiangBU** [comment]
@jdblischak I write the quick function and pull it to the `dev`  branch, but there are some errors in the `devtools::test` pre-test and `document.R` updating process.
Here is my pull request, https://github.com/jdblischak/workflowr/pull/154.
I comment the details there.
