### ISSUE TITLE
Feature request: add date option to the function `wflow_open`

### ISSUE THREAD

**Issue by JiaxiangBU** [workflowr/workflowr#156]
> Before posting your issue, please search the existing issues (both "open" and "closed") to check that a similar feature has not already been requested.

1. The issue https://github.com/jdblischak/workflowr/issues/100 requests the options in the yaml field, like `date="2018-08-08"`.
1. The issue https://github.com/jdblischak/workflowr/issues/23 requests automatically filling out the YAML option. 

I think my issue is based on these two.

> 1. Describe the suggested feature.
> 2. Describe why you think this feature is needed.

The current version give the users the **created time** option in the YAML field. However, sometimes the **updated time** may be better for the readers to know.

I think for the function `wflow_open`, just add an arguement `created_time = TRUE` as a default option. It helpes users to have one more choice.

3. Tell us the version of workflowr you are using. Run `packageVersion("workflowr")` in R or RStudio, and copy & paste the output here.

```
> packageVersion("workflowr")
[1] ‘1.2.0’
```

**Comment by jdblischak** [comment]
> The current version give the users the created time option in the YAML field. However, sometimes the updated time may be better for the readers to know.

The last updated date is accessible from the workflowr reproducibility report. See the screenshot below from your workflowr project [string](https://jiaxiangbu.github.io/string/ch1.html):

![Screenshot from 2019-04-07 22-03-58](https://user-images.githubusercontent.com/1608317/55694220-2bae3080-5981-11e9-81b9-692bcf049e01.png)

> I think for the function wflow_open, just add an arguement created_time = TRUE as a default option. It helpes users to have one more choice.

What would be inserted for the date if `created_time = FALSE`? Do you want it to insert `Sys.Date()` instead?

```
title: "Untitled"
date: "`r Sys.Date()`"
output: html_document
```

As you may have seen in the other past Issues, I don't have a lot of motivation for adding extra arguments to `wflow_open()`. This is because specifying an argument to `wflow_open()` takes a user just as long as changing the value in the R Markdown file itself. To me, it only makes sense to enhance `wflow_open()` if you were creating lots of R Markdown files at a time.

However, if you have the time and motivation, I would be open to accepting a Pull Request that added an argument such as `created_time`. Let's continue discussing the exact behavior here in this Issue first though before you start working on it.

**Comment by JiaxiangBU** [comment]
> What would be inserted for the date if `created_time = FALSE`? Do you want it to insert `Sys.Date()` instead?

Yes, that is what I mean. But I see the updated time in the screenshot so I think `created_time` is unnecessary.

> This is because specifying an argument to `wflow_open()` takes a user just as long as changing the value in the R Markdown file itself.

I agree with you. Keeping `wflow_open` neat and simple is better for the users.
