### ISSUE TITLE
Restarting R session solves git2r-related question

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#160]
> Before posting your question, please search the existing issues (both "open" and "closed") to check that a similar question has not already been posted.

I have searched both open and closed issues, and it seems there is no similar one.

Hi John @jdblischak -- recently I came across the following error (which was traced back to `git2r`), and it seems that I solved it by simply restarting the R session; please see details below.

```r
> wflow_publish("analysis/grs.Rmd")
Error: A Git repository is required for this functionality.
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
> library("git2r")
Error: package or namespace load failed for ‘git2r’ in get(Info[i, 1], envir = env):
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/git2r/R/git2r.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

Restarting R session...

Loading .Rprofile for the current workflowr project
This is workflowr version 1.3.0
Run ?workflowr for help getting started
> library("git2r")

> wflow_publish("analysis/grs.Rmd")
Current working directory: /Users/xiangzhu/GitHub/mvp-cad
Building 1 file(s):
Building analysis/grs.Rmd
Summary from wflow_publish

**Step 1: Commit analysis files**

Summary from wflow_git_commit

The following was run: 

  $ git add analysis/grs.Rmd 
  $ git commit -m "wflow_publish(\"analysis/grs.Rmd\")" 

The following file(s) were included in commit dc20c78:
analysis/grs.Rmd

**Step 2: Build HTML files**

Summary from wflow_build

Settings:
 clean_fig_files: TRUE

The following were built externally each in their own fresh R session: 

docs/grs.html

Log files saved in /private/var/folders/dm/39__1gf52_s_9xbqrfd_46lc0000gp/T/RtmpFJlHGw/workflowr

**Step 3: Commit HTML files**

Summary from wflow_git_commit

The following was run: 

  $ git add docs/grs.html docs/figure/grs.Rmd docs/site_libs docs/.nojekyll 
  $ git commit -m "Build site." 
```

**Comment by jdblischak** [comment]
Thanks for the report! Could you please describe what you had done just
before this? My guess is that you installed some packages. The downside of
always loading workflowr via .Rprofile is that any of its dependent
packages (eg git2r) can't be easily updated. To avoid issues like this, you
can always install packages outside of a workflowr project.

**Comment by xiangzhu** [comment]
> Could you please describe what you had done just before this? 

When I traced back the error to `git2r`, the next thing I did was to reinstall `git2r`, within the workflowr same project.

> To avoid issues like this, you can always install packages outside of a workflowr project.

Thanks and I will follow this suggestion. Do you think it helpful to add this tip to the documentation page, something like the "best practice of using workflowr"?

Since this is just a case report, please feel free to close the ticket as you see fit.

**Comment by jdblischak** [comment]
@xiangzhu I did some more investigation, and I am fairly certain that your error was caused by installing git2r (it may have been a dependency of another package) while git2r was already loaded in the current session. Source: https://github.com/wch/movies/issues/3#issuecomment-49396154

I was able to replicate the error in the Docker image `rocker/r-ver` by running `remotes::install_github("ropensci/git2r")` inside of a workflowr project and then running `library(git2r)`. Note that I was still able to run `wflow_publish("analysis/index.Rmd")` prior to trying to explicitly load git2r, but afterwards it would no longer work.

```
wflow_publish("analysis/index.Rmd")
"git2r" %in% loadedNamespaces()
## [1] TRUE
remotes::install_github("ropensci/git2r")
wflow_publish("analysis/index.Rmd")
"git2r" %in% loadedNamespaces()
[1] TRUE
library(git2r)
## Error: package or namespace load failed for ‘git2r’ in get(method, envir = home):
##  lazy-load database '/usr/local/lib/R/site-library/git2r/R/git2r.rdb' is corrupt
## In addition: Warning message:
## In get(method, envir = home) : internal error -3 in R_decompress1
wflow_publish("analysis/index.Rmd")
## Error: A Git repository is required for this functionality.
## In addition: Warning messages:
## 1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
##   restarting interrupted promise evaluation
## 2: In get(method, envir = home) :
##   restarting interrupted promise evaluation
## 3: In get(method, envir = home) : internal error -3 in R_decompress1
"git2r" %in% loadedNamespaces()
## [1] FALSE
```

I attempted to catch this error internally via `tryCatch()` and `requireNamespace("git2r")`, but I couldn't find a robust method to suppress the error and warning while also obtaining enough information to determine the actual error. In other words, I wasn't able to "catch" the lazy-load database error.

Thus I'm going to add an FAQ about installing packages in a workflowr project.

**Comment by xiangzhu** [comment]
@jdblischak  Many thanks for investigating this issue!

To confirm, as a user I can avoid this kind of error by "always installing packages outside of a workflowr project", right?

I was not aware of this when I first started using workflowr, and I was often able to install/update certain packages within the workflowr project.

I feel a FAQ entry would be very useful, especially for new users. Thanks!

**Comment by jdblischak** [comment]
> To confirm, as a user I can avoid this kind of error by "always installing packages outside of a workflowr project", right?

Yes, that strategy will always work. Note that it may be overly cautious though, since you won't have problems if the packages you are installing do not share dependencies with workflowr (or if you are already using the latest versions of the workflowr dependencies).

> I was not aware of this when I first started using workflowr, and I was often able to install/update certain packages within the workflowr project.

That's because it rarely is an issue. Also, you've been using workflowr since the very beginning! :-) The feature to add a `.Rprofile` to automatically load R wasn't added until workflowr [version 0.8.0](https://jdblischak.github.io/workflowr/news/index.html#workflowr-0-8-0).

> I feel a FAQ entry would be very useful, especially for new users. Thanks!

Here it is: [How should I install packages to use with a workflowr project?](https://jdblischak.github.io/workflowr/articles/wflow-05-faq.html#how-should-i-install-packages-to-use-with-a-workflowr-project)
