### ISSUE TITLE
How to knitr::include_graphics in workflowr?

### ISSUE THREAD

**Issue by Zepeng-Mu** [workflowr/workflowr#162]
Hi,

I am trying to add figures to my Rmd file with `include_graphics` function in `knitr`, but it seems that the figures are not showing. How can I do this in workflowr?

Thanks so much!

**Comment by jdblischak** [comment]
Please check out the FAQ "How can I include external images in my website?"
and let me know if that strategy works for you.

https://jdblischak.github.io/workflowr/articles/wflow-05-faq.html

**Comment by jdblischak** [comment]
@Zepeng-Mu A quick follow-up. First, here is an [exact link](https://jdblischak.github.io/workflowr/articles/wflow-05-faq.html#how-can-i-include-external-images-in-my-website) to that FAQ question. Second, I looked the man page for `include_graphics()`. It's main purpose is to convert the syntax for a figure to support any rmarkdown output (e.g. HTML versus LaTeX). Since workflowr always converts to HTML, you can directly specify the path to the figure file using either Markdown syntax:

```
![](assets/external.png)
```

or if you prefer, you can directly write HTML:

```
<img src="assets/external.png">
```

**Comment by Zepeng-Mu** [comment]
Great, thank you so much!

I used to use `![]` notation, but sometimes prefer `include_graphics` because it allows me to set figure size by `out.width/height` in a chunk.
I can try different methods in workflowr and see what happens

**Comment by jdblischak** [comment]
> I used to use ![] notation, but sometimes prefer include_graphics because it allows me to set figure size by out.width/height in a chunk.

Ah, ok. That use case makes sense. Using that function will also automatically center the image, which is nice.


I am able to use `include_graphics()` with the strategy for external figures explained in the FAQ. If I save the figure file as `docs/assets/figure.png`, then I can include the chunk below in a workflowr R Markdown file:

````
```{r use-knitr, out.width=100}
knitr::include_graphics("assets/figure.png")
```
````

which is converted to the following HTML:

```
<pre class="r"><code>knitr::include_graphics(&quot;assets/figure.png&quot;)</code></pre>
<p><img src="assets/figure.png" width="100" style="display: block; margin: auto;" /></p>
```

Does this work for you? The only downside is that the image preview won't work in the R Markdown file.

**Comment by jdblischak** [comment]
Note that `include_graphics()` changed its default behavior in knitr 1.28. The call should now be:

````
```{r use-knitr, out.width=100}
knitr::include_graphics("assets/figure.png", error = FALSE)
```
````

I updated the docs in f4bedd0
