### ISSUE TITLE
About git locking

### ISSUE THREAD

**Issue by pat-s** [workflowr/workflowr#170]
See #80.

When building targets in parallel with _drake_ and using `wflow_publish` as the _workflowr_ command, I often see targets failing with the following error

```
$error
<simpleError: The Git repository is locked. This can happen if a Git command
previously crashed or if multiple Git commands were executed at the
same time. To fix this, you need to delete the file .git/index.lock.
You can do this by running the following in the R console:

file.remove("/home/patrick/papers/2019-feature-selection/.git/index.lock")>
```

However, when this happens I usually only build one target with _workflowr_ and not multiple ones in parallel. 
When building only this one target sequentially with _drake_, everything is fine.
I am not sure if _drake_ maybe locks something there or some other issues are introduced by parallelization in general (I think this is hard to track down).
Would it be possible to add a flag to `wflow_publish()` which does not lock the Git repo?

**Comment by jdblischak** [comment]
@pat-s Thanks for the bug report!

> I am not sure if drake maybe locks something there or some other issues are introduced by parallelization in general (I think this is hard to track down).

I checked the [drake repo](https://github.com/ropensci/drake) and couldn't find anywhere it was potentially locking the Git repo.

> Would it be possible to add a flag to wflow_publish() which does not lock the Git repo?

I haven't implemented the functionality in Issue #80, partly because of the potential unforeseen consequences. The error message you are receiving is from the workflowr function [`check_git_lock()`](https://github.com/jdblischak/workflowr/blob/4bca64e05e449fb1ec44a9ca58bb4f2e09fcebef/R/git.R#L478), which only checks for the existence of this file. Workflowr itself executes Git commands via git2r/libgit2, which do not appear to have the option of disabling the creation of `index.lock`. I'm also worried that this would not be a good idea. That file is only created temporarily during the execution of a Git command. If `check_git_lock()` detects that file, it strongly suggests that some other process is writing to the Git repository.

Some questions/ideas for further troubleshooting:

1. Do any of the other steps in your drake pipeline run anything that would read or write to the Git repository?

1. Would it be possible to create a minimal example drake pipeline that recreates this error, even if it only happens occasionally?

1. After you receive that error from workflowr, does the file `index.lock` still exist? If it doesn't, that would suggest a different step had created and then deleted it.

**Comment by pat-s** [comment]
> Do any of the other steps in your drake pipeline run anything that would read or write to the Git repository?

No, only the `worklflowr` functions.

> Would it be possible to create a minimal example drake pipeline that recreates this error, even if it only happens occasionally?

Not so easy. In the end this problems seems to be related to parallel workers on a HPC probably accessing the same dir/lock files at the same time.

> After you receive that error from workflowr, does the file index.lock still exist? If it doesn't, that would suggest a different step had created and then deleted it.

I'll check next time. I've only seen it occasionally so far and maybe `index.lock` was really a leftover of some previous runs in which the file was not deleted properly due to several reasons (e.g. user interruption of the _drake_ call). 

When thinking about it, the last point I mentioned (leftover from a previously interrupted call) makes most sense to me. 
However, this is hard to tackle: If we would remove `index.lock` before starting the `workflowr` function, we risk breaking other calls which currently perform a git operation. This can happen if multiple workers call `wflow_publish()` at the same time, attempting to create a `index.lock` file.

This point again makes me think that maybe one should only use `wflow_build()` in a parallelized workflow to avoid such problems?

**Comment by jdblischak** [comment]
> No, only the worklflowr functions.

Is there only one step that calls workflowr? Doe this `wflow_publish()` step get called once or does it get called multiple times (e.g. for each Rmd file)?

> If we would remove index.lock before starting the workflowr function, we risk breaking other calls which currently perform a git operation.

You could have your code check the timestamp of `index.lock`. If it was created an hour ago, then it is likely due to an older interrupted run.

> This point again makes me think that maybe one should only use wflow_build() in a parallelized workflow to avoid such problems?

But then you'd lose the important version controlling aspect of workflowr. You could manually re-recreate the steps `wflow_publish()` by having the drake pipeline run `wflow_git_commit()`, but that seems like it is just changing the step that generates the error.

To help me understand your use case better: when you execute your drake pipeline, do any of the R Markdown files have uncommitted changes?

**Comment by jdblischak** [comment]
@pat-s Any update on this issue? Did you find a solution or workaround? I like the idea of combining drake and workflowr, so it'd be useful for me to better understand how one uses them together in practice.

**Comment by pat-s** [comment]
Sorry for forgetting about this! You know the struggle.

> Is there only one step that calls workflowr? Doe this wflow_publish() step get called once or does it get called multiple times (e.g. for each Rmd file)?

I am calling `wflow_publish()` for each Rmd. See [here](https://github.com/pat-s/2019-feature-selection/blob/bbd422affd277f853de95854bea58f0fee66443e/code/09-reports.R).

The issue is that I can't build the reports in parallel (multiple jobs) because the git locking causes jobs with `wflow_publish()` to fail if there is already one running.

> To help me understand your use case better: when you execute your drake pipeline, do any of the R Markdown files have uncommitted changes?

Sometimes yes.

**Comment by jdblischak** [comment]
@pat-s Thanks for following up!

This is tough since this involves Git operations, which I can't do much about. Here are my suggestions:

1. Is it possible to tell drake that some rules should not be run in parallel? If yes, having the `wflow_publish()` steps run sequentially should work.
1. Have the pipeline perform Git operations in bulk before and after building the Rmd files. This doesn't give you as much fine-grained control over the Git history (e.g. if the Rmd files depend on each other, it'd be useful to know which ones had been run prior), but it should avoid the locking issue while still harnessing parallel processing. Something like:
    1. `git add analysis/*`
    1. Run `wflow_build()` in parallel
    1. `git add docs/*`

**Comment by pat-s** [comment]
I guess 1) is not possible because the workers cannot be "paused" or "stopped" if there is a specific call detected. It is not about drake per se here, it could be any other scheduling system which executes parallel calls of `wflow_publish()`. So adding a specific adaption there cannot be the solution.

I guess 2) is the way to go: No `wflow_publish()` to avoid git racing/locking but rather one quick `git add && git commit` after each `wflow_build()´ call.

AFAIK {workflowr} locks git during the complete build process, isn't it? This causes the git locking issues. While writing this: If that's the case, maybe {workflowr} can only perform quick `git add` commands after the document has been rendered? (apologies if I'm wrong on what {workflowr} does here)

**Comment by jdblischak** [comment]
> AFAIK {workflowr} locks git during the complete build process, isn't it?

No, it currently doesn't. I proposed it in #80, but never implemented it. All the Git operations should be done quickly via git2r, which I why I think the errors you get are spurious. If workflowr locked the Git repo for the entire duration of the build, I suspect you'd always get errors with parallel processing (since multiple calls to `wflow_publish()` would attempt to lock the Git repo for extended periods of time).

That being said, workflowr tends to be slower than Git because it performs lots of safety checks (since it is running automatically). If you can use a tool like drake to confidently always perform the Git operations when they should be run, that might be faster and avoid some of the spurious errors. And you'll know if anything goes wrong because the workflowr report will show a warning if the Git operations were not performed in the proper order.
