### ISSUE TITLE
wflow_quickstart function

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#176]
Summarizing our discussion about this suggested new feature, `wflow_quickstart("tornadoes.Rmd")` would roughly do the following:

1. Create a workflowr project called "tornadoes".

2. Copy `tornadoes.Rmd` to `analysis/index.Rmd`.

3. Runs `wflow_publish("analysis/*Rmd")`.

4. Runs `wflow_use_github()` and `wflow_git_push()`, when possible.

A common point-of-failure for Step 3 will be that the files are no longer in the right place (because the working directory will change), so we need to figure out a user-friendly way around that.

**Comment by jdblischak** [comment]
I created `wflow_quickstart()`. It's on the branch "quickstart". Could you please test it out?

The main differences between your description above and the current implementation are:

1. Instead of changing the provided Rmd to `index.Rmd`, it adds a link to the HTML results in `index.Rmd`. I think this will better accommodate the situation where the user has multiple Rmd files.
1. It doesn't attempt to run `wflow_git_push()`. Given that it isn't even guaranteed that the GitHub repo was created, I didn't want to attempt to additionally handle all the possible ways that `wflow_git_push()` might fail.

**Comment by pcarbo** [comment]
My first impression: awesome! This is what I did:

```
> wflow_quickstart("cars.Rmd","pcarbo")
wflow_quickstart:
* Started the project with wflow_start() in /Users/pcarbo/Desktop/cars/
* Copied cars.Rmd to /Users/pcarbo/Desktop/cars/analysis/
* Building files
* Published the analysis files with wflow_publish()
The GitHub repository cars can be automatically created for the account
pcarbo if you authorize workflowr to do so. This requires logging into
GitHub and enabling the workflowr-oauth-app access to the account.
Enable workflowr to create pcarbo/cars? (y/n) y
* Configured to host project on GitHub.com
* Current working directory changed to /Users/pcarbo/Desktop/cars/
* To do: Run wflow_git_push() to push your project to github
> wflow_git_push()
Please enter your username: pcarbo
Please enter your password: ********************
Summary from wflow_git_push
Pushing to the branch "master" of the remote repository "origin"
Using the HTTPS protocol
The following Git command was run:
  $ git push origin master
```

See the attached R Markdown file, `cars.Rmd`. 

This is the repository created on GitHub:
https://github.com/pcarbo/cars

[cars.Rmd.gz](https://github.com/jdblischak/workflowr/files/3718928/cars.Rmd.gz)

**Comment by pcarbo** [comment]
My only question so far is that I don't understand why I am required to specify the username in `wflow_quickstart` whereas it was not needed for `wflow_start`.

**Comment by pcarbo** [comment]
I tried another example in which the code doesn't run to completion:

```
* Building files
Error: could not find function "read_csv"
```

It would be nice if it reverted back to the original state and removed the files if this doesn't succeed, like `wflow_build` and `wflow_publish`.

**Comment by pcarbo** [comment]
And, predictably, it doesn't work when using relative paths:

```
Error: 'StormEvents_details-ftp_v1.0_d2018_c20190817.csv.gz' does not 
exist in current working directory ('/Users/pcarbo/tornadoes').
```

I think we briefly discussed this potential issue, but not sure what is the best approach it.

**Comment by jdblischak** [comment]
> My only question so far is that I don't understand why I am required to specify the username in wflow_quickstart whereas it was not needed for wflow_start.

This is because `wflow_start()` only performs local operations. Since `wflow_quickstart()` additionally runs `wflow_use_github()` (or `wflow_use_gitlab()`), it needs to know the user's username for that online service.

> It would be nice if it reverted back to the original state and removed the files if this doesn't succeed, like wflow_build and wflow_publish.

But does that make as much sense in this case? The reason `wflow_build()`/`wflow_publish()` are so conservative is because it is assumed that the user may already have something worth keeping, and thus do not want to mess it up.

On the other hand, `wflow_quickstart()` can't mess up an existing project because it is starting it from scratch. Thus there is no harm in a partially created project. Instead of obliterating everything, it could produce a warning such as "It looks like the code in your Rmd file failed to execute. Try fixing any file paths and then re-run wflow_build()`.

We could make this a flag, e.g. `delete_on_failure`.

> I think we briefly discussed this potential issue, but not sure what is the best approach it.

Some ideas:

* We could provide a data argument for data files to copy to the new project
* We could either copy to `analysis/`, or copy to `data/` and attempt to modify the file path in the Rmd file (which will be brittle, since they may not have a full string to the file, but instead use something like `file.path()` or `here::here()`).

Thoughts?

**Comment by pcarbo** [comment]
> Since wflow_quickstart() additionally runs wflow_use_github() (or wflow_use_gitlab()), it needs to know the user's username for that online service.

I see, you have another argument `git.user.name`.

> Instead of obliterating everything, it could produce a warning such as "It looks like the code in your Rmd file failed to execute. Try fixing any file paths and then re-run wflow_build()`.

I think a warning is a great solution for now (and maybe later, too).

> I think we briefly discussed this potential issue, but not sure what is the best approach it.

I'm trying to think of the simplest solution (that can be refined later on). I'm also thinking there could easily be files such as `functions.R` and `dat.RData`.

What about allowing non-Rmd files in the `files` argument; these files are copied to `analysis`, with a suggestion printed to the user to move these files to a better placee (e.g., `data` or `code`).

**Comment by pcarbo** [comment]
What happens if I do something like `wflow_quickstart(c("cars.Rmd", "cars_more.Rmd"),"pcarbo")`?

**Comment by pcarbo** [comment]
(And more generally `files` could be a directory, in which case all the contents of that directory are copied to the `analysis` directory.)

**Comment by pcarbo** [comment]
> I saw this in the email thread.

Thanks. I removed this comment because I figured it out on my own, but thanks for the reply anyhow.
