### ISSUE TITLE
link to pandoc is dead in README.md

### ISSUE THREAD

**Issue by PietrH** [workflowr/workflowr#190]
The link in the README which refers to `https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md` is currently dead. 

It could probably be changed to `https://github.com/jgm/pandoc/blob/master/README.md`

**Comment by jdblischak** [comment]
@PietrH Thanks so much for reporting the dead link. The file I was pointing to was moved in https://github.com/rstudio/rmarkdown/pull/1574. I prefer to link to the [RStudio-provided instructions for installing pandoc](https://rmarkdown.rstudio.com/docs/articles/pandoc.html) because they detail the requirements and options for using pandoc with the rmarkdown package.

**Comment by PietrH** [comment]
@jdblischak No problem, there's still the link to pandoc.com for more general information. Thank you for the quick fix!
