### ISSUE TITLE
Using Minty theme

### ISSUE THREAD

**Issue by ditordccaa** [workflowr/workflowr#192]
Hi there,

I was wondering if there is a possibility to use minty theme with workflowr when building the website.

I tried downloading the .css file of minty theme from here : https://bootswatch.com/minty/

I put the file in the analysis folder and updated the _site.yml file but it didn't work for me.

Am I missing something?

Cheers,

**Comment by jdblischak** [comment]
> I put the file in the analysis folder and updated the _site.yml file but it didn't work for me.

@ditordccaa When you say it didn't work for you, do you mean 1) the CSS file was ignored, or 2) the CSS file was recognized, but the resulting website looked bad?

I was able to use the minty CSS file by downloading it to `analysis/` and updating `_site.yml` to use it:

```
output:
  workflowr::wflow_html:
    css: bootstrap.min.css
```

However, the result was terrible because that CSS file uses Bootstrap version 4. The rmarkdown package, and thus workflowr, still uses Bootstrap version 3.

Thus your current options are 1) wait until rmarkdown implements Bootstrap v4 (https://github.com/rstudio/rmarkdown/issues/1260), or 2) find a version of the minty theme that uses Bootstrap v3.

**Comment by ditordccaa** [comment]
@jdblischak  Thanks for your response. 
Actually it's the second option. the CSS file was recognized but as you mentioned, the website looked bad.
Ok I'll try to find a minty theme for bootstrap3.

Thanks a lot.
Cheers ,

**Comment by jdblischak** [comment]
@ditordccaa Great. If you find a Bootstrap v3 CSS file for the minty theme, please report back here so that other users could potentially use it.

I'm closing this issue since it has been resolved as best as we can for now. Please feel free to re-open or open a new related Issue.
