### ISSUE TITLE
Display author ORCID

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#195]
> Before posting your question, please search the existing issues (both "open" and "closed") to check that a similar question has not already been posted.

I did the search and did not find a similar issue.

Hi John @jdblischak  -- I wonder if it is possible to display author ORCID in workflowr.

I see this feature in `pkgdown` sidebar: https://pkgdown.r-lib.org/reference/build_home.html#sidebar.

Thanks a lot for your time and thoughts on this question!

**Comment by jdblischak** [comment]
Hi @xiangzhu!

Could you please expand more on the result you would like to obtain and how workflowr can help with it?

To me, this seems similar to a question I recently receive via Twitter, where the user wanted to insert the Zenodo DOI badge on every page. This can be setup manually in workflowr using the existing rmarkdown features. Check out the thread for my advice to use the `before_body` option: https://twitter.com/_psyguy/status/1232462090561916929

pkgdown automatically scrapes the ORCID from the `DESCRIPTION` file. Since workflowr doesn't require a package, it can't use this same strategy. If automatically adding badges (e.g. ORCID, Zenodo, etc.) is a desired feature, one way to faciliate this in workflowr would be to add a feature where users can specify badges in `_workflowr.yml`. My main concern with adding this feature is that it doesn't save that much time. In other words, in the amount of time it takes to read the documentation and paste the necessary information in `_workflowr.yml`, one could also read the rmarkdown documentation and insert the content directly.

@pcarbo and I have discussed including a sidebar similar to pkgdown. I worry about this because it can affect the page in unexpected ways. pkgdown uses a [custom HTML template](https://github.com/r-lib/pkgdown/blob/master/inst/templates/content-home.html) and plenty of [CSS styling](https://github.com/r-lib/pkgdown/blob/master/inst/assets/pkgdown.css#L149) to create the sidebar. This can have unintended consequences, e.g. on the page that you linked above (the h2 header was automatically given the same id as the sidebar, causing it to be styled like the sidebar, see https://github.com/r-lib/pkgdown/issues/1181 for details).

What are your thoughts on a sidebar versus putting the content at the top of the page? Also, would you prefer this metadata content on every page or only the main page?

**Comment by xiangzhu** [comment]
Hi John,

Thanks for the explanations. They all make sense to me. 

> Could you please expand more on the result you would like to obtain and how workflowr can help with it?

What I have now             |  What I hope to have
:-------------------------:|:-------------------------:
![Screenshot from 2020-03-13 10-32-11](https://user-images.githubusercontent.com/5986023/76645297-f35e8d00-6515-11ea-818f-e5f93da3db83.png)  |  ![Screenshot from 2020-03-13 10-33-46](https://user-images.githubusercontent.com/5986023/76645398-29037600-6516-11ea-98c1-c43096abbe4d.png)

In short, I hope to have that little green icon next to my name, and when I click the icon it directs me to my ORCID page.

I am imagining something as follows:

```rmd
---
title: "RSS-NET analysis of IBD GWAS summary statistics and NK cell regulatory network"
author: "Xiang Zhu"
orcid: "0000-0003-1134-6413"
date: 2019-08-19
output: workflowr::wflow_html
---
```

> What are your thoughts on a sidebar versus putting the content at the top of the page?

I am not a fan of the sidebar (although `pkgdown` uses it). In addition, people might get confused if `workflowr` and `pkgdown` have similar appearances.

> Also, would you prefer this metadata content on every page or only the main page?

For my case above, I hope it appear on every page.

Finally, I want to emphasize that I favor simplicity over this potential feature -- if adding this feature would complicate the usage/maintenance of `workflowr`, then I am totally fine without it. 

Thanks again for your time and help!

**Comment by jdblischak** [comment]
@xiangzhu I sent PR https://github.com/SUwonglab/rss-net/pull/1 to demo one potential option for adding the badge to your workflowr website. Please give it a try and let me know what you think.

I'm not going to add official support for ORCID IDs in workflowr. According to the [official ORCID guidelines](https://orcid.org/trademark-and-id-display-guidelines), you have to first authenticate the ID before displaying the green icon:

> Do not display the green iD icon next to an iD that has not been authenticated.

**Comment by xiangzhu** [comment]
@jdblischak  Many thanks for providing a working example for me to try!

Unfortunately I will not use this approach in my workflowr sites because this approach shows author+badge before the title, whereas the ideal case I imagined is that only the badge is added to the current workflowr layout.  

I will stick to the simple design of workflowr (without showing ORCID badge). Please feel free to close this issue. Thanks again!

**Comment by jdblischak** [comment]
> I will stick to the simple design of workflowr (without showing ORCID badge).

@xiangzhu Sounds good. Another suggestion: you can always manually insert the HTML for the ORCID badge directly into the Rmd files for those that you really want to customize the display. The solution would look similar to my PR (in that you'd need to add the badge image file), but then instead of using `before_body`, you'd copy the HTML code just below the YAML header. Though the workflowr button would be between the title and author info.
