### ISSUE TITLE
jquery version

### ISSUE THREAD

**Issue by SFonsecaCosta** [workflowr/workflowr#207]
Hi,

I found from one of my repositories that github is having some security problems with old jquery versions.

Would be possible, that when we generate the workflowr project that the libraries from jquery are updated to version 3.5.0 or later?

The jquery libraries when we generate a new workflow project are linked to the version 1.11.
jquery-1.11.3 and jqueryui-1.11.4.

Thank you very much for your help and time.

Best regards,

Sara

**Comment by jdblischak** [comment]
@SFonsecaCosta Thanks for alerting me to this issue.

All of the website files (the JS/CSS in `docs/site_libs/`) are controlled by the rmarkdown package. Someone has opened an issue there requesting guidance on this issue: https://github.com/rstudio/rmarkdown/issues/1814

Let's see what the rmarkdown maintainers advise.

**Comment by jdblischak** [comment]
@SFonsecaCosta Thanks again for alerting me to this potential security issue. I've read the security release and the various discussions from other maintainers of R packages that use jQuery. Here's my interpretation:

1. HTML files created with `rmarkdown::html_document()` are **not** affected by this security bug. The [bug was introduced in jQuery version 1.2](https://github.com/jquery/jquery/security/advisories/GHSA-gxr4-xjj5-5px2). As you reported, workflowr uses jQuery 1.11.3 (this is because `workflowr::wflow_html()` calls `rmarkdown::html_document()`).

    ![image](https://user-images.githubusercontent.com/1608317/83830138-68270a80-a6b2-11ea-9015-d1dc0fbc4075.png)

1. When rmarkdown is [updated to Bootstrap 4](https://github.com/rstudio/rmarkdown/pull/1706), it will use a jQuery verison >= 3.5.0. Thus HTML documents created with rmarkdown will completely avoid this security bug.

1. Even for R packages that use a vulnerable version of jQuery, [upgrading will be a very laborious process in order to prevent features from breaking](https://github.com/rstudio/bookdown/pull/693#pullrequestreview-226222435). Thus there is little incentive to upgrade unnecessarily.

Thus my conclusion is there is nothing that needs to be done at the moment for workflowr since workflowr-generated websites are not affected by this bug.

Related discussions:

https://github.com/rstudio/rmarkdown/issues/1814
https://github.com/subugoe/openairegraph/issues/13
https://github.com/rstudio/distill/issues/132
https://github.com/rstudio/bookdown/pull/882
https://github.com/rstudio/bookdown/pull/693
https://github.com/rstudio/shiny/issues/2856
