### ISSUE TITLE
After commiting changes to notebook, associated webpage retains out-of-date SHA1

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#21]
This stems from John's and Peter's discussion on whiteboard yesterday.

This is the scenario:

1. I make a change to `n1.Rmd`, and commit this change to the repo.

2. `n1.html` retains SHA1 from previous commit, and therefore is not in sync with `n1.Rmd`.

3. My collaborator views the webpage, and assumes that the code to reproduce this webpage is `n1.Rmd` from the most recent commit, which is incorrect.

To resolve this situation, I suggest that `wflow_commit` makes a small addition to `n1.html` that warns the user that this webpage may be out-of-date; e.g., 

> Warning: `n1.Rmd` has been updated more recently than this webpage, and 
> therefore `n1.Rmd` from the most recent commit may not exactly reproduce 
> the code and results contained in this webpage. Access snapshot `f2bb9475d271c7c13c2ff08237bb87ae21330e6c` to retrieve the version of
> `n1.Rmd` that reproduces this webpage.

**Comment by jdblischak** [comment]
The main complication I see with this at the moment is when to check and add this message. The current `wflow_commit` is slow because it checks the Git log for every R Markdown file. The plan is to change this default behavior and make it optional (being discussed in #14). Thus in this new design, each HTML file will only be checked if it is out of date when specifying `all = TRUE`, and if it is, it will be rebuilt. One option would be to still check the Git log for every file every time even if `all = FALSE`, but that would make the function very slow, especially for a repo with many Rmd files. Thoughts on how to incorporate checking for out-of-date HTML files into the workflow?

**Comment by pcarbo** [comment]
When I run `wflow_commit` in step 1 above, couldn't `n1.html` be edited before the `git commit` call so that the webpage is automatically flagged as being out-of-date? Then I can revise the SHA1 in the webpage whenever I call `wflow_build` or `wflow_publish`.

Would this approach avoid the need to look at git logs?

**Comment by pcarbo** [comment]
How I think about it is this: the SHA1 in a webpage is a "guarantee" that the HTML is up-to-date with the notebook. This can be guaranteed whenever you call `wflow_build` or `wflow_publish`. However, whenever you call `wflow_commit`, this guarantee no longer exists, so you should remove or flag the SHA1 in the corresponding webpage. 

Unless I'm missing something important, I believe this flagging system should provide the same information as the git logs.

**Comment by jdblischak** [comment]
Now I think I understand your solution. This would work as long as every time the user commits an Rmd file without updating the HTML, they use a workflowr function. However, if they add and commit the Rmd using the command line or other method, then these changes would not be detected. Do I understand correctly?

Are you thinking the HTML with the edited message should be included in the same commit as the Rmd or a subsequent? Since the SHA1 is not being changed, I think it would be ok to include them in the same commit. Please let me know what you think.

**Comment by pcarbo** [comment]
> However, if they add and commit the Rmd using the command line or other method, 
> then these changes would not be detected.

Yes, exactly. This would work as long as the user only uses workflowr interface.

In general, it is simpler to to design a "closed" interface. If you start to design an interface that may interact with other interfaces (e.g., command-line git), then it is difficult to provide any guarantees. 

And remember, if things go wrong (e.g., because user started messing around with git repository), the user always has the fallback option of running `wflow_publish(all = TRUE)`, which rebuilds everything from scratch.

> Are you thinking the HTML with the edited message should be included in the same 
> commit as the Rmd or a subsequent?

I prefer the same commit, but both are fine; more important is what is easier to implement.

**Comment by jdblischak** [comment]
I'm not planning on implementing this.

First it would be technically difficult, because somehow the HTML would have to be edited even though it is not being published.

Second, the workflowr framework is not against "drafts". In other words, we encourage users to run `wflow_git_commit()` if they are not ready to publish the latest changes. Workflowr guarantees that when you are reading an HTML file, you can obtain the exact version of the Rmd file that produced it. It doesn't guarantee that the author of the analysis won't update it in the future (or may have already begun to commit new changes that haven't made it to the website).

Expanding on the second point, if users know that committing a work-in-progress to the Rmd file would generate a warning on their website, they may instead choose to not commit the change until it is completely ready. And I would rather encourage committing often.

> My collaborator views the webpage, and assumes that the code to reproduce this webpage is n1.Rmd from the most recent commit, which is incorrect.

I see the potential concern here, but that is also why we include the link to the exact version of the Git repository in the workflowr report. And the collaborator may even prefer to be working on the latest version of the Rmd. In practice, this potential problem hasn't been reported.
