### ISSUE TITLE
Inline LaTeX renders locally but not on GitHub pages

### ISSUE THREAD

**Issue by rgayler** [workflowr/workflowr#211]
I have a `{workflowr}` project with some inline LaTeX math script, e.g. `$A + B$`
See https://rgayler.github.io/VSA_op_properties/simulation.html

This inline maths renders OK locally, but on GitHub pages it renders as `\(A + B\)`

I understood (possibly wrongly) that the GitHub pages are rendered from the html files in `docs/` on the GitHub repo, which are exact copies of the html files in my local `docs/`,  which renders correctly.

What is happening and how do I get the maths to render correctly on the GitHub pages?

Thanks

**Comment by jdblischak** [comment]
> This inline maths renders OK locally, but on GitHub pages it renders as \(A + B\)

It looks good in my browser (Firefox 79.0a1 running on Windows 10). Here's a screenshot:

![image](https://user-images.githubusercontent.com/1608317/84693845-2732bf80-af16-11ea-95fd-d864e072f6b6.png)

> I understood (possibly wrongly) that the GitHub pages are rendered from the html files in docs/ on the GitHub repo, which are exact copies of the html files in my local docs/, which renders correctly.

You understand correctly!

> What is happening and how do I get the maths to render correctly on the GitHub pages?

The LaTeX equations are rendered to HTML using the JavaScript library [MathJax](https://www.mathjax.org/). The majority of the supporting files (e.g. CSS, JavaScript) for your workflowr website are saved in `docs/site_libs/`. This means that you don't have to worry about any of these resources becoming temporarily unavailable. The main exception to this setup is MathJax. Instead of bundling the MathJax JavaScript code in `site_libs/`, the rmarkdown package loads MathJax from an RStudio maintained server.

You can see this at the bottom of [`simulation.html`](https://github.com/rgayler/VSA_op_properties/blob/38d75dbaa017141fd03310883d3b1adfe7413a07/docs/simulation.html#L1242):

```
<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
```

Thus there are multiple reasons why the equations were not being rendered once you pushed to GitHub:

1. The RStudio server may have been temporarily unavailable
1. Your browser settings (e.g. if they it has restrictions on running JavaScript)
1. Firewall issues

Hopefully this was a temporary issue. If it continues to happen, you can pass `mathjax = "local"` to `workflowr::wflow_html` in `analysis/_site.yml`, which will then get passed to `rmarkdown::html_document`. This will bundle MathJax just like the other website resources (this isn't the default because of the large size of the MathJax library).

And as a reminder, if you edit `analysis/_site.yml`, make sure to commit it and also re-publish the existing analysis pages, e.g.

```
wflow_publish("analysis/_site.yml", "Bundle MathJax", republish = TRUE) 
```

This will ensure that the changes go into effect.

**Comment by rgayler** [comment]
Thanks! Your explanation made it easy to track down the cause. 

The page rendered properly in a different browser, but not my usual FireFox browser, which is set up with multiple privacy protection add-ons. It turned out that [Privacy Badger](https://privacybadger.org/) had decided that mathjax.rstudio.com had put a tracker on my github.io page and blocked it.

I over-rode Privacy Badger and the page now renders correctly for me. I also sent feedback on this to Privacy Badger.

Thinking about long-term issues, I will try bundling MathJax with the website resources (as you suggested) in order to remove the dependency on Mathjax being available via Rstudio. A website is not really a viable archival medium but it would be nice to think it might still be operational in 10 years. Given the finite lifespans of companies (GitHub and Rstudio) and browser backward-compatibility I won't be holding out for longer viability than that.

**Comment by rgayler** [comment]
Solution confirmed:

`analysis/_site.yml` now contains

```
output:
  workflowr::wflow_html:
    mathjax: "local"
```
and `docs/site_libs` is 11MB larger as a consequence.

The page now renders correctly from `github.io` with Privacy Badger on its original settings, because there is no longer a dependency on `mathjax.rstudio.com`.

**Comment by jdblischak** [comment]
Great! I'm glad you were able to track down the issue. And thanks for confirming here so that other users can benefit.
