### ISSUE TITLE
Support parameters when knitting an Rmd file

### ISSUE THREAD

**Issue by ashirwad** [workflowr/workflowr#213]
Before posting your issue, please search the existing issues (both "open" and "closed") to check that a similar feature has not already been requested.

1. Describe the suggested feature.
It would be nice to have the ability to generate multiple `html` files from a single `Rmd` file, where each `html` file will correspond to a unique value of the parameter. (e.g., multiple reports for different regions)

2. Describe why you think this feature is needed.
I have to knit an Rmd file to generate output for two different data sets (everything else remains the same).

3. Tell us the version of workflowr you are using. Run `packageVersion("workflowr")` in R or RStudio, and copy & paste the output here.
`[1] ‘1.6.2’`

**Comment by jdblischak** [comment]
@ashirwad Thanks for opening this feature request! My answers below:

> It would be nice to have the ability to generate multiple html files from a single Rmd file, where each html file will correspond to a unique value of the parameter. (e.g., multiple reports for different regions)

This is tricky because workflowr depends on the 1:1 relationship between the Rmd source file and the HTML output file. Especially important is being able to automatically determine the name of the HTML file that corresponds to the Rmd file. If the name of the HTML files are determined by the parameters passed to the Rmd file while it is being built, it won't be possible for the workflowr functions to determine which HTML files were built by a given Rmd file.

> I have to knit an Rmd file to generate output for two different data sets (everything else remains the same).

Could you please take a look at the vignette [Sharing common code across analyses](https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html) to see if any of these strategies appeal to you? The basic idea is to maintain the 1:1 mapping between Rmd and HTML, but keep the shared code in a common file. In other words, you would create the hypothetical files `param1.Rmd` and `param2.Rmd`, but the only difference between the files is the value of the parameter. They both call the same shared code file to produce the results.

**Comment by ashirwad** [comment]
Thanks, John (@jdblischak )! The one-to-one correspondence between Rmd and HTML file makes sense. Also, I had checked the workflowr documentation, but I think I missed the vignette that you linked in the answer.
