### ISSUE TITLE
minimizing dependence on workflowr

### ISSUE THREAD

**Issue by stephens999** [workflowr/workflowr#22]
while teaching I found that having fiveMinuteStats depend on workflowr was
a bit annoying : the students all had to have workflowr installed to knit the rmd files.
One way around that could be to check for workflowr installation in the boilerplate.

eg: **Code version:** `r if(require(workflowr,quietly=TRUE)){workflowr::extract_commit(".", 1)$sha1}`

or something similar. That would allow students to knit these files without installing workflowr.
Not sure if this modification to boilerplate could be a generally good idea?

**Comment by jdblischak** [comment]
I definitely agree. One of the selling points of workflowr is that it doesn't lock you in, and the call to `extract_commit` at the top violates this principle.

The one change I would make to your suggestion is to use `requireNamespace`. Unlike `require`, this does not attach the package.

```
**Code version:** `r if(requireNamespace("workflowr", quietly = TRUE)) {
                        workflowr::extract_commit(".", 1)$sha1}`
```

However, the above solution loses the tracking of the code version completely if the user stops using workflowr. I had been thinking of implementing this directly using git2r. This is not as nice as the function I had written (it prints the whole SHA1 instead of just the first 7 characters, and also it displays nothing if there is not Git repo present instead of NA), but the reduction of dependencies may be worth it.

```
**Code version:** `r if(requireNamespace("git2r", quietly = TRUE))
                        if(git2r::in_repository())
                          git2r::commits()[[1]]@sha`
```

Thoughts?

**Comment by pcarbo** [comment]
> The reduction of dependencies may be worth it.

I agree, as long as you provide an informative message, something like, "Code version id not available; please install the workflowr package to retrieve it."

**Comment by jdblischak** [comment]
Here are the more verbose versions of the two options:

```
**Code version:** `r
if(requireNamespace("workflowr", quietly = TRUE)) {
  workflowr::extract_commit(".", 1)$sha1
} else {
  "Unavailable. Install workflowr package to enable."
}`
```

or

```
**Code version:** `r 
if(requireNamespace("git2r", quietly = TRUE)) {
  if(git2r::in_repository()) {
    git2r::commits()[[1]]@sha
  } else {
    "Unavailable. Initialize Git repository to enable."
  }
} else {
  "Unavailable. Install git2r package to enable."
}`
```

I have the if/else logic start on the subsequent line so that it is easier to read and understand.

**Comment by pcarbo** [comment]
I like it.

**Comment by jdblischak** [comment]
Which of the two options do you prefer? I am leaning towards the second since it allows the user to embed the code version without using the workflowr package (the main downside being that it is more verbose and this code is present at the top of every file).

**Comment by pcarbo** [comment]
I prefer the second. It always helps to add a comment to the code explaining what the code does.

**Comment by stephens999** [comment]
i'm fine with either

**Comment by jdblischak** [comment]
Fixed in https://github.com/jdblischak/workflowr/commit/f9425b3203eb3a5a4193e0d33f75ff675a340519
