### ISSUE TITLE
Generating web site also using subfolders

### ISSUE THREAD

**Issue by LearnUseZone** [workflowr/workflowr#220]
Hello @jdblischak ,

I've read some comments and also found a relevant issue here and also I watch at least one video where you said that currently workflowr cannot create web site if there are subfolders with .Rmd files in "analysis" folder in other words all .Rmd files has to be in "analysis" folder.

Based on what I learnt about workflowr (I still have gaps) and rmarkdown packages, I created a workaround that based on my tests is working - it's available at https://learnusezone.github.io/workflowrSubfolders/index.html .

It's tested with only one subfolder and within it only one .Rmd file.
It's prepared semi-automated - there are manual steps which can be programmed but this should be only as proof of concept (POC) so I didn't want to spend too much time on it.
For now, downsides which I see are:
1) There are manual steps focused on some text replacements.
2) Text replaced in the final .html file isn't replaced in an associated .Rmd file (it could be but it's not necessary for these POC purposes)
3) It could be complicated if there are dozens of files and subfolders and web links. - I think that this is the major downside but still possible to overcome.

Can you please look at it and give me your thoughts?
1) If a one decide to use this semi-automated workaround, do you think there are some complications (downsides) that I possibly missed?
2) Do you have any advises how to enhance at least this workaround process? Because as I mentioned above, if it's used for few web pages with only few or non web links, then it should work fine.

Maybe you already think about such workound but find much more complications that me so I believe that you could give me some advises - maybe you advise to rather not use that because of something. On the other hand I hope that it could give you some kind of inspiration how also workflowr could handle .Rmd files in subfolders.

If you find a time for this, I recommend to start with https://github.com/LearnUseZone/workflowrSubfolders/blob/master/_preparationSubFolders.R which contains all steps (also with comments) that I made. These are notes mainly for me so you can find there link to file(s) that you don't have but in such case(s) you can ignore it.

If you have further questions, I'll be glad to provide more information.

**Comment by jdblischak** [comment]
@LearnUseZone Thanks for the detailed explanation!

My initial impression is that this workaround seems like a lot of work. Could you please describe more of your motivation for using subfolders within the `analysis/` directory? How many Rmd files do you have in your workflowr project (or do you anticipate having)? If you need to organize them for navigating the website, you can do this by organizing the hyperlinks to different files in different sections.

Looking at your implementation more in-depth, I worry about the duplication. The `_site.yml` file is duplicated and so it the `site_libs` directory. Also, I can't guarantee that the workflowr reproducibility checks are working correctly in this situation since they aren't expecting the extra subfolders.

At the end of the day, workflowr is an extension of rmarkdown:

* `workflowr::wflow_html()` extends `rmarkdown::html_document()`
* `wflow_build()` calls `rmarkdown::render_site()`
* `wflow_site()` is a [custom site generator](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html#custom-site-generators) for rmarkdown websites

The biggest advantage of this is that anything you can do with rmarkdown, you can do with workflowr. The biggest disadvantage is that anything you can't do with rmarkdown, you can't do with workflowr. RStudio funds 3 full-time software engineers to work on the rmarkdown ecosystem (see their [2019 report](https://rstudio.com/assets/img/RStudio-Benefit-Corporation-2019-Annual-Report.pdf)), and they've decided it would be too complicated to enable subdirectories for rmarkdown websites. The previous discussion in Issue #95 provides more details on why this would be difficult to implement, and also provides some potential workarounds that may work with the workflowr framework (no guarantees though).

You are certainly not alone in wanting rmarkdown to support subdirectories. I also would like this feature. And here is a recent request from a few months ago: https://github.com/rstudio/rmarkdown/issues/1859 At this point, rmarkdown is so widely used, that I doubt they will ever be willing to introduce the backwards-incompatible changes that would be required to support subdirectories.

**Comment by LearnUseZone** [comment]
Hello @jdblischak ,

thank you for your time and pointing out other web sites which helped me.

I adjusted my solution of working with subfolders based on https://github.com/jdblischak/workflowr/issues/95#issuecomment-360094662 (with negligible changes) as one of options that also you recommended at the end of that thread. Result notes: https://github.com/LearnUseZone/workflowrSubfolders/blob/master/code/_preparationSubfolders.R

Briefly, I plan to have some development codes (not suitable for .Rmd) in folder "code" as you wrote in the documentation where I put 2 folders with 1 file for these tests.
I created new folder "codeRmd" in the main folder for workflowr project containing folders and .Rmd files associated to content of folder "code".

I agree that this is more efficient way to work with subfolders than my original attempt.
The most important for me is that if I understand correctly then now, a potential problem with the workflowr reproducibility checks (as you mentioned above) could be solved. Is my understanding correct?

The last 2 situations of low importance are:
- I need to live with the fact that all .html files are directly in "docs"/"public" (GitHub/GitLab) folder but because crucial for me is to have organized development codes and .Rmd files this is OK. So I can leave workflowr to take care about these generated .html files.
- I need to keep in mind to use correct hyperlinks to future .html files.


I have one more question:
GitHub Desktop allows to write short commit text but also "Description" (if I need to write more). Is anything like this GitHub Desktop description implemented also in workflowr package or do I need to write more text (if needed) to parameter "message" of function wflow_publish()?
 
 
 
Answers to your questons regarding my original workaround (only for a reason to have it all answered):
Motivation
- I want to have everything organized (mainly development codes, outputs and .Rmd files). Currently, I plan to have around 40 .Rmd files saved accross folders "docs"/"public"  and 2 other subfolders (currently subfolders in folders "code" and "codeRmd").

Duplicates
- I agree that  "./analysis/subPages/_site.yml" is updated duplication and it would be better to not have because e.g. it causes some kind of mess which I'd like to avoid.
- Folder "./docs/subPages/_site_libs" is really duplicated and if I enhance this solution, I could replace text in generated .html file in "./docs/subPages/" to use "./docs/site_libs" folder but I didn't do that because for these testing purposes it wasn't needed. In this case, I don't afraid of this duplication because it can be fixed by that text replacement.

Organizing hyperlinks to differet files in different sections
- If I understand you correctly, I did this when I added hyperlink in file "./docs/index.html" to file ".docs/subPages/aboutSubPages.html".

Downsides
1) The critical one is your reply: "I can't guarantee that the workflowr reproducibility checks are working correctly in this situation since they aren't expecting the extra subfolders."
2) Downsides from my original comment.

**Comment by jdblischak** [comment]
In which directory do you want to execute the code chunks in your Rmd files?

A line like the following isn't reproducible because it can only be run on your one machine. If you move the project to another directory on your computer, or try to run it on a different computer, it will break.

```
source("D:/Cloud/Sync/Study/Programming/R/Work/Projects/GitHub/workflowrSubfolders/code/subPages1/print1.R")
```

The default for workflowr is to run the code in the root directory of the project, so the following should work. Please give it a try and let me know if that works:

```
source("code/subPages1/print1.R")
```

If you want to execute the code in a different subdirectory, you can change this in the file `_workflowr.yml`. For example, if you want to execute the code in `codeRmd`, you could set `knit_root_dir: "codeRmd/"`.

Also, have you seen the vignette [Sharing common code across analyses](https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html)? I think you might find some of its tips interesting.

**Comment by LearnUseZone** [comment]
Hello @jdblischak ,

folder "code" will contain subfolders containing .R files with data manipulation R codes.
Folder "codeRmd" will contain subfolders with .Rmd files associated to relevant .R files from withing subfolders of folder "code".

Thank you very much for pointing out the problem with using of absolute paths and link to documentation where I found here::here() function. I like the idea of that function so I started to use it.

I played also with options we discussed here and I also tested options to use "pandoc_args: --strip-comments" not only in "analysis/_site.yml" but also directly in .Rmd files (currently used in file "testPrint2.Rmd") and it works correctly.

So based on my today tests, I found everything what I needed to have a very acceptable solution for using workflowr together with .Rmd files in subfolders.

The only last thing that came in my mind as a potential update of workflowr package when using .Rmd files within subfolders is related to workflowr checks. If you open e.g. https://learnusezone.github.io/workflowrSubfolders/subPages1--testPrint1.html, you can see that 2 checks failed so it would be nice to have something that will indicate that this failed because .Rmd files weren't directly in "analysis" folder and have it directly within that workflowr button. But I think this is really only nice to have feature which can be completely omitted because for me, it's enough to look at web address path and I can immediately see that it's from subfolder or some short text can be easily added directly to web page.

Thank you again very much for your help and if there's nothing else in your mind, feel free to close this issue.

**Comment by jdblischak** [comment]
> Thank you very much for pointing out the problem with using of absolute paths and link to documentation where I found here::here() function. I like the idea of that function so I started to use it.

`here::here()` is really useful, and it doesn't hurt anything in this case. But I don't think you should need it when using the workflowr framework. The code is executed in the root directory of the project. And as long as you don't change the working directory in RStudio, it should work interactively in the R console as well.

I'm confused why the workflowr check for absolute paths is still failing. That absolute path is no longer there. Thus I suspect somehow the reproducibility report isn't getting regenerated properly. I'm not quite sure how to fix that. If you want to investigate further, please experiment some (e.g. by adding new absolute paths just to test if they are detected), and open a new issue to discuss.

As for the Rmd failure, that's because you never commit the copies in `analysis/`. With your subfolder workflow, is it possible to add the step `wflow_publish("analysis/sub*Rmd)` after you copy the Rmd files to `analysis/`? That would remove the warning.

**Comment by LearnUseZone** [comment]
Hello @jdblischak ,
thank you for additional comments.
I've fixed both check issues.

You can find all changes in file "code/_preparationSubfolders.R" where I added more comments to both used functions that caused those check errors. You can find brief additional information also below.

1) here::here()
* The problem was that previously I used functions generate_rmd() and wflow_build_dir() (see in file "_preparationSubfolders.R"; original versions of functions are at https://github.com/jdblischak/workflowr/issues/95#issuecomment-360094662) in a way when folder "analysis" is set as working directory. I updated them so now, I don't need to manually switch a working directory so here::here() is really not needed.

2) absolute path failes
* The problem was in function generate_rmd() on a row where parameter child of r chunk was defined. Path to original .Rmd file (in a subfolder) was specified using absolute path.
* I've updated that with using of knitr::opts_knit$get(\"output.dir\") that I found explained at https://github.com/jdblischak/workflowr/issues/111#issuecomment-407861132, so now there's a relative path.
* I've also added setwd(here::here()) into wflow_build_dir() to ensure that I will work with workflowr project directory each time when I will render .Rmd files in subfolders.

3) commiting of temporary .Rmd files in "analysis" folder
* I decided to use workflowr::wflow_git_commit within if condition as it's coded in function wflow_build_dir() but your advice definitely help me. I wanted to have an option to not commit if I think more relevant changes inside .Rmd file(s) are needed and also I rather keep commiting (wflow_git_commit()) and building (wflow_build()) separate also for an option to not commit when I still don't need to commit.

**Comment by jdblischak** [comment]
@LearnUseZone Great! I'm glad you now have a working solution!

For other users interested in using subfolders within a workflowr project, please check out this example repository:

https://github.com/LearnUseZone/workflowrSubfolders
https://learnusezone.github.io/workflowrSubfolders/
https://github.com/LearnUseZone/workflowrSubfolders/blob/master/code/_preparationSubfolders.R

**Comment by yihui** [comment]
FYI a quick update from {rmarkdown}: https://github.com/rstudio/rmarkdown/issues/1859#issuecomment-5431523808
