### ISSUE TITLE
wflow_build options to specify files

### ISSUE THREAD

**Issue by bfairkun** [workflowr/workflowr#221]
Hi,

An option to use the intersection (instead of the union) of file sets to build specified by the various other wflow_build() options would be nice.

I often use the great `make=TRUE` option so that I can easily just build all the files where the Rmd has been edited more recently than the html... But sometimes I realize, actually want I want is to do that only for a subset of my newly edited Rmd files, of which I can easily describe as a glob pattern with the `files` argument. Currently I am not aware of an easy way to achieve that.

**Comment by jdblischak** [comment]
@bfairkun Thanks for opening this issue for discussion!

> Currently I am not aware of an easy way to achieve that.

You're correct that this is not currently possible.

> actually want I want is to do that only for a subset of my newly edited Rmd files, of which I can easily describe as a glob pattern with the files argument.

I'd like to better understand your use case. Can you give me a sense of how many new files you are actively editing at once? And how long do they take to run? I could create a new argument that controls the use of `union()` versus `intersection()`, but this would add more complication (more code and more documentation of this new option).

For example, what's stopping you from running `wflow_build()` (with its default of `make = TRUE`)? The first time its run it might build more files than you'd prefer, but after that one run then only the ones you continue editing will be built. What are the characteristics of the files you want to avoid building (e.g. long run time, errors b/c code is work-in-progress, etc.)?

**Comment by pcarbo** [comment]
Would the `dry_run` option help here?

**Comment by bfairkun** [comment]
@jdblischak sometimes I have often have 5-10 files that I am actively editing or are a work-in-progress with sort of long run time. So that is one reason I think this functionality would be nice.

The other reason is that occasionally I write Rmd files that depend on data that is too big to commit to a git repository. So using a project organization similar to what is recommended in the workflowr FAQ, I have code in the `code` directory that does the heavy lifting processing (on a cluster with lots of storage) and creates large semi-processed files, as well as smaller files in the `output` directory which I commit to my repository and reference in my Rmd files.  But sometimes in my Rmd files, I actually want to use the large data files or semi-processed files that I do not commit. Therefore, my solution is to just build the large Rmd files on the cluster which contains the large files. If I use a consistent naming scheme for my Rmd files that distinguishes those that need to be run a the cluster, versus at any clonable copy of the repository, I can do something like `wflow_build("RunOnCluster_*.Rmd", make=T)` versus `wflow_build("RunOnAnyCloneOfRepo_*.Rmd", make=T)`

@pcarbo and yes, I suppose I could use the output of `dry_run` (with `make=T`) (or whatever function under the hood makes the `make` argument work) in combination with`list.files()` to find the intersection of the files I want to build and use that in the `files=` argument.

**Comment by jdblischak** [comment]
@bfairkun Great. Thanks for the extended explanation of your use case.

To make sure I understand the feature request, here's a hypothetical example. Let's say you are working on 10 new files: `short1.Rmd`, `short2.Rmd`, ..., `short5.Rmd` and `long1.Rmd`, `long2.Rmd`, ..., `long5.Rmd`. Only `short2.Rmd`, `short3.Rmd`, and `long4.Rmd` have been updated more recently than their corresponding HTML files. The current behavior is:

1. `wflow_build()` (or more explicitly, `wflow_build(make = TRUE)`) will build `short2.Rmd`, `short3.Rmd`, and `long4.Rmd`.

1. `wflow_build("analysis/short*.Rmd")` will build all 5 `short*.Rmd` files.

1. `wflow_build("analysis/short*.Rmd", make = TRUE)` will build all 5 `short*Rmd` files plus `long4.Rmd`, because it uses `union()` to combine the Rmd files specified by the different arguments.

Since `long4.Rmd` takes a long time to run, and you are actively editing the various `short*.Rmd` files, you'd like to be able to only build the `short*.Rmd` files that have been updated more recently than their corresponding HTML files. My proposal for the new behavior would be to add an argument `combine`. It accepts a function that will be used to combine the Rmd files from the various arguments. The default would be `combine = union`, which would replicate the current behavior. To instead take the intersection, you would pass the intersection function:

```
wflow_build("analysis/short*.Rmd", make = TRUE, combine = intersection)
```

This would only build `short2.Rmd` and `short3.Rmd`.

@bfairkun What do you think of this proposed feature? Is this the behavior you need?

@pcarbo What do you think of the argument name and functionality? I like passing a function instead of a character string because this would potentially allow users to specify any arbitrary function they want that accepts 2 character vectors.

**Comment by pcarbo** [comment]
> I like passing a function instead of a character string because this would potentially allow users to specify any arbitrary function they want that accepts 2 character vectors.

@jdblischak That is clever but I worry it will be confusing; not everyone who uses R (and I'm thinking of workflowr's audience in particular) is comfortable with passing functions as arguments.

I think the argument name is fine. I wonder if "and" and "or" would be more intuitive than "intersection" and "union" (e.g., to draw the connection to Web searches).

**Comment by bfairkun** [comment]
>What do you think of this proposed feature? Is this the behavior you need?

@jdblischak, yes this would be perfect!

**Comment by jdblischak** [comment]
> I wonder if "and" and "or" would be more intuitive

@pcarbo Good points. Passing functions as arguments is probably overkill in this case, and not worth the potential confusion of novice users. I like `"and"` and `"or"`.

Another decision to make: should we make this a package level option, e.g. `"workflowr.combine"`? This would allow users to set `options(workflowr.combine = "or")` in their `.Rprofile` if they wish to always override the default behavior.

**Comment by pcarbo** [comment]
> Another decision to make: should we make this a package level option.

Potentially, but maybe hold off for now while we see how it is used? (I could see `options` being useful in other ways — e.g., for the "view" option in `wflow_build` and `wflow_publish`. Also, have you considered setting the default for `verbose` to `options()$verbose`, as is sometimes done in other packages?)

**Comment by jdblischak** [comment]
> Potentially, but maybe hold off for now while we see how it is used?

True. There's no rush.

> (I could see options being useful in other ways — e.g., for the "view" option in wflow_build and wflow_publish.

The option `workflowr.view` already exists. Run `?workflowr` to see all the available package options.

> Also, have you considered setting the default for verbose to options()$verbose, as is sometimes done in other packages?)

I've considered it but haven't figured out a good way to implement it. Part of the reason is that the workflowr messaging is using a mixed strategy at the moment. I started primarily using the S3 print methods to describe everything that happened. This has its advantages and disadvantages. Recently I've been using `message()` more during the actual execution of the function. No one has complained about the verbosity, so I haven't made it a priority to address it.

**Comment by pcarbo** [comment]
> The option `workflowr.view` already exists. 

Ah, somehow I missed that.

**Comment by jdblischak** [comment]
@bfairkun The new argument `combine` for `wflow_build()` and `wflow_publish()` is now available on the master branch. Could you please install this version from GitHub and let us know how it works for you? Thanks!

```
remotes::install_github("jdblischak/workflowr")
```
