### ISSUE TITLE
Error: callr subprocess failed: no se pudo encontrar la función "%>%"

### ISSUE THREAD

**Issue by ogorodriguez** [workflowr/workflowr#224]
I have searched and have not found a similiar issue. 

Hi, I am trying to run workflowr (ver 1.6.2) and I am getting the error

Error: callr subprocess failed: no se pudo encontrar la función "%>%"

when running wflow_build()

callr version used: 3.5.0

tidyverse and dplyr are called in library

I have opened a ticket in callr here (https://github.com/r-lib/callr/issues/170)  Their answer is that magrittr was not called in the child operations and that I should check here.  As mentioned above.  Tidyverse and dplyr have been loaded so I thought that took care of magrittr for the pipe.

It was working fine at first and then it started throwing this error. 

Session.Info

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252
[4] LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] workflowr_1.6.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5       rstudioapi_0.11  knitr_1.29       magrittr_1.5     tidyselect_1.1.0
 [6] here_0.1         R6_2.4.1         rlang_0.4.7      dplyr_1.0.1      tools_4.0.2     
[11] xfun_0.18        pacman_0.5.1     tinytex_0.24     htmltools_0.5.0  ellipsis_0.3.1  
[16] yaml_2.2.1       digest_0.6.25    rprojroot_1.3-2  tibble_3.0.3     lifecycle_0.2.0 
[21] crayon_1.3.4     purrr_0.3.4      tidyr_1.1.0      later_1.1.0.1    vctrs_0.3.2     
[26] promises_1.1.1   fs_1.5.0         glue_1.4.2       evaluate_0.14    rmarkdown_2.3   
[31] compiler_4.0.2   pillar_1.4.6     generics_0.0.2   backports_1.1.7  httpuv_1.5.4    
[36] pkgconfig_2.0.3

**Comment by jdblischak** [comment]
@ogorodriguez Thanks for the detailed bug report! I'm not sure exactly what's causing the problem, but here are some ideas for troubleshooting.

1. Can you re-run `wflow_build()` on the problematic file, but this time set the argument `local = TRUE`? This will build the file in your local R session instead of using callr to build it in a separate isolated R session. This should hopefully provide a more informative error message and potentially reveal the problematic code chunk.

1. Are you able to share the problematic Rmd file that is generating this error? If not, can you create a new Rmd file and add the chunk below?
    ```
    library(dplyr)
    mtcars %>% summarize(mean(mpg))
    ```
   Please report what happens when you try to build this file with `wflow_build()`. Also, does it work when you run it directly in the R console?

**Comment by ogorodriguez** [comment]
Hi @jdblischak It worked setting the local = TRUE param.  Will I need to run it all the time?  Thanks for the prompt reply and for keeping up such a great tool.

**Comment by ogorodriguez** [comment]
I also ran the test file above and was able to build it no problem or error message and no use of local = TRUE either.  

wflow_build("analysis/test*.Rmd")
Current working directory: C:/Users/.../Desktop/Rprojects/02_drob-tidytuesday-horror-movies
Building 1 file(s):
Building analysis/test_callr_error.Rmd
Summary from wflow_build

Settings:


The following were built externally each in their own fresh R session: 

docs/test_callr_error.html

Log files saved in C:/Users/.../AppData/Local/Temp/Rtmp40TrR6/workflowr

**Comment by jdblischak** [comment]
@ogorodriguez Did you ever determine the isssue with the Rmd file that was causing the error? I am curious to diagnose it, so if you could share the analysis code, I am interested in investigating.

> It was working fine at first and then it started throwing this error.

I think I missed this the first time I read your issue, or I didn't appreciate the significance of it. The fact that it was working and then stopped is even more evidence that you added some problematic code to the Rmd. If we can find it and fix it, then you can continue using workflowr for this analysis.

**Comment by ogorodriguez** [comment]
@jdblischak following up on this I see that I need to load all the packages I am using in each Rmd to avoid having the callr error pop up when building or publishing.  Is there a way for me to load all the packages once so they apply to all of the Rmd analysis files I create.  

The error does not occur when not building nor publishing.  Hope this helps.  I am open to send more info if needed.   You can see my repo here: 
https://github.com/ogorodriguez/01_nested-machine-learning-workflows

**Comment by jdblischak** [comment]
@ogorodriguez Thanks for following up and sharing your workflowr project.

>  I need to load all the packages I am using in each Rmd

Correct. Workflowr treats each Rmd as a separate, isolated analysis.

> Is there a way for me to load all the packages once so they apply to all of the Rmd analysis files I create.

Yes, you have various options. Check out the vignette [Sharing common code across analyses](https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html).

The most straightforward option would be to create a file such as `code/packages.R` that contains the common packages to load, e.g.:

```
library(dplyr)
library(ggplot2)
```

Then at the top of each Rmd file, you would put:

````
```{r}
source("code/packages.R")
```
````

And then if you add a package to `code/packages.R`, it will be available to all of your Rmd files. Whenever you make changes to `code/packages.R`, don't forget to commit the changes. You can do this separately with `wflow_git_commit()`, or you can pass it to `wflow_publish()` along with the Rmd files. For example, the below will commit the changes to `code/packages.R` and also publish all the Rmd files:

```
wflow_publish(c("code/packages.R", "analysis/*Rmd"))
```

> The error does not occur when not building nor publishing.

Exactly. That is a feature of workflowr 🙂 Lots of code works when run interactively in the R console, but not when you try to run it 6 months later on a different computer. It's easy to load a package in the R console, but forget to add it to the script. Or to rename a variable in every place in your script but one, such that it continues to work in the current R session (since the variable with the previous name still exists), but it will break in a clean R session. This is the reason that all Rmd files in a workflowr project are built in a separate clean R session (using the wonderful callr package).

**Comment by ogorodriguez** [comment]
Hello @jdblischak I thank you a lot for all of this points you have offered to better take advantage of your wonderful workflowr package.  

Knowledge sharing seems to be a gift you possess and here be noted.  Big thanks.

**Comment by ogorodriguez** [comment]
One little thing here @jdblischak : 

> And then if you add a package to code/packages.R, it will be available to all of your Rmd files. Whenever you make changes to code/install.R, don't forget to commit the changes. You can do this separately with wflow_git_commit(), or you can pass it to wflow_publish()

When you wrote code/install.R, you were still referring to code/packages.R right?

**Comment by jdblischak** [comment]
> Knowledge sharing seems to be a gift you possess and here be noted. Big thanks.

Thank you for your kind words.

> When you wrote code/install.R, you were still referring to code/packages.R right?

Yes, thanks for catching that typo. I will edit my above post for the benefit of future readers of this thread.
