### ISSUE TITLE
Figure cross-references not working

### ISSUE THREAD

**Issue by rgayler** [workflowr/workflowr#229]
I am trying to use Figure numbering and cross-referencing in an analysis document, using bookdown::html_document2 output format with workflowr::wflow_html as the base format. This works as expected in an RStudio vanilla project, but in a workflowr project the figures are not numbered and the cross-references are rendered as literal text. 

# Example

I have a minimal analysis file:
```text
---
title: "test"
author: "Ross Gayler"
date: "2020-12-06"
output: 
  bookdown::html_document2:
    base_format: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

Here comes a figure!

```{r test, fig.cap = "This is an exciting test figure."}
plot(cars)
``` # this comment is needed to embed a chunk in a chunk

Figure \@ref(fig:test) shows a test figure.
```
# Working

When I knit that (knit to HTML button) in an RStudio vanilla project, it works as expected. The Figure-n prefix is added to the caption and the cross-reference gets substituted with the correct value, and the workflowr decorations are added:
![image](https://user-images.githubusercontent.com/5409051/101268407-829f8500-37b6-11eb-8ad9-4d648253af60.png)

# Failing

When I knit the same file (knit to HTML button or wflow_build()) in an RStudio workflowr project, the workflowr decorations are added but the Figure-n prefix is missing from the caption and the cross-reference gets directive is rendered literally:
![image](https://user-images.githubusercontent.com/5409051/101268426-ba0e3180-37b6-11eb-9c4d-a7c0135ed167.png)

I know approximately nothing about the internals of workflowr, bookdown, and rmarkdown - so any suggestions on where to start looking to fix this would be greatly appreciated.

**Comment by jdblischak** [comment]
@rgayler Thank you for the minimal working example file. This made it very easy for me to investigate the issue.

> in a workflowr project the figures are not numbered and the cross-references are rendered as literal text.

In the workflowr project, the output format is specified in `analysis/_site.yml`. This is so that the same output is applied to all the Rmd files. To enable figure cross-referencing, update the output format in `analysis/_site.yml`. This could look something like the following:

```
output:
  bookdown::html_document2:
    base_format: workflowr::wflow_html
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate
```

After you update `_site.yml`, don't forget to commit the change. The line below commits the change to `analysis/_site.yml` and re-publishes all the published analyses:

```
wflow_publish("analysis/_site.yml", "Enable figure cross-references with bookdown", republish = TRUE)
```

xref: #210

> I know approximately nothing about the internals of workflowr, bookdown, and rmarkdown - so any suggestions on where to start looking to fix this would be greatly appreciated.

Here is some more intuition on how things are working. The configuration file `_site.yml` controls the behavior of the website that is built with `rmarkdown::render_site()`. This is a feature of [R Markdown Websites](https://rmarkdown.rstudio.com/lesson-13.html) that workflowr builds on. Here is how it works:

1. The output format that is specified in `_site.yml` takes precedence. This is why your example file had no cross-referencing. Because the output format in `_site.yml` was `workflowr::wflow_html`,  the output format `bookdown::html_document2` specified in the individual Rmd file was ignored.

1. Individual Rmd files can override the default output settings, but only if the output format matches that in `_site.yml`. As an example, the file `index.Rmd` that `wflow_start()` creates is configured to disable the table of contents:

    ```
    output:
      workflowr::wflow_html:
        toc: false
    ```

    However, when you change `_site.yml` to use `bookdown::html_document2`, then `index.Rmd` will once again have a floating table of contents on the left. Since the output format doesn't match, it gets ignored entirely. If you want to keep suppressing the table of contents for `index.Rmd`, you would update it to match the output format:

    ```
    output:
      bookdown::html_document2:
        toc: false
    ```

> `# this comment is needed to embed a chunk in a chunk`

Here's a Markdown formatting trick for you. In order to include R Markdown code chunks inside of a Markdown code block, use 4 backticks to specify the Markdown code chunk instead of the usual 3. Then you can copy-paste the contents of the Rmd file directly inside it without any modification.

**Comment by jdblischak** [comment]
@rgayler Did using `bookdown::html_document2` in `analysis/_site.yml` fix your figure cross-references?

**Comment by rgayler** [comment]
@jdblischak sorry for the slow reply - the day job gets in the way of the fun stuff.

Using `bookdown::html_document2` in `analysis/_site.yml` did indeed fix the figure cross-references. Thanks!

At some point, for my own benefit, I will have to write a table with an entry for every workflowr-relevant entity in the project with a note saying what they do, how to use them, and their cross-relationships - effectively a `workflowr` cheat sheet.
I find that I'm getting progressively worse at extracting the information I want from long-form vignettes.

> In order to include R Markdown code chunks inside of a Markdown code block, use 4 backticks 

Thanks for that also. My google-fu completely failed me on that one.

**Comment by jdblischak** [comment]
> effectively a workflowr cheat sheet

That'd be a wonderful resource, especially since it would be from the viewpoint of a user. If you make a cheatsheet, please let me know so that I can share it with other users.

> Thanks for that also. My google-fu completely failed me on that one.

No problem. That's a real tough one to search for, so I do my best to spread this sort of tribal knowledge. For more tips and tricks, I recommend the [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/).
