### ISSUE TITLE
automatic author and date?

### ISSUE THREAD

**Issue by stephens999** [workflowr/workflowr#23]
I noticed that when i do new-Rmarkdown file in Rstudio it automatically
fills in my name and date for me.
it would be nice if workflowr could do the same.

**Comment by jdblischak** [comment]
Yes, I can add this functionality to `wflow_open`. My plan would be to obtain the author name from `git config user.name`. Do you have an idea of how RStudio does it? My RStudio does not currently have this functionality. I am using the most recent version on RStudio (1.0.136) and rmarkdown (1.3.9003 from GitHub) on Ubuntu. Did you install a preview release of RStudio or change one of the settings?

**Comment by stephens999** [comment]
no, i'm not sure how it does it.
I'm using Rstudio 1.0.44 and i guess i must have change the settings at
some point? When i click new-rmarkdown the pop-up window has "author" field
already filled in.
Matthew

**Comment by pcarbo** [comment]
Interesting, I don't have that feature either. (I'm using RStudio 1.0.139.) 

I wonder if you have set a environment variable that records your name. Matthew, can you run `Sys.getenv()` in RStudio and send us the output?

**Comment by pcarbo** [comment]
I doesn't seem that this is a feature that can be relied on. A simple alternative is to add the author field automatically and include a placeholder for the user to fill out.

**Comment by jdblischak** [comment]
The current template comes with the following YAML header:

```
---
title: "Untitled"
author: "First Last"
date: YYYY-MM-DD
output: html_document
---
```

Matthew's suggestion is to automatically fill in the author and date fields. I would accomplish this via a workflowr function, since I don't have access to whatever mechanism RStudio is using. Thus if a user ran `wflow_open` it would automatically fill in the author and date fields, but if they open a new file using the workflowr template via the RStudio menus (File -> New File -> R Markdown -> From Template), it would rely on their RStudio settings.

How does that sound?

**Comment by pcarbo** [comment]
Sounds good to me.

**Comment by stephens999** [comment]
Sounds great, although not clear to me where you get the user's name from

**Comment by jdblischak** [comment]
> Sounds great, although not clear to me where you get the user's name from

I use my given name for my Git user.name, whereas you use your GitHub account username. There is no requirement for this field (GitHub just needs it to be consistent so that it can attribute all the commits to you). Using the authors in the fiveMinuteStats repo as an example, we can see that both GitHub usernames and real names are used for the Git user.name. Thus my proposed solution would automatically add "stephens999" for the author field.

If this is undesirable behavior, we'll need to think of another way to obtain the user's name.

```
fiveMinuteStats$ git log --pretty=format:%an | sort | uniq
Arjun Biddanda
jhmarcus
jhsiao999
jnovembre
John Blischak
mbonakda
mfrasco
Nan Xiao
stephens999
Xiao Nan
```

**Comment by stephens999** [comment]
i think that is fine. MS

**Comment by jdblischak** [comment]
I'm going to close this since `wflow_open()` has been deprecated, and thus workflowr no longer has any function that creates R Markdown files.

A similar idea was recently raised in #100. As I [commented there](https://github.com/jdblischak/workflowr/issues/100#issuecomment-382817556), I'm reluctant to implement features like this that would require a lot of error handling code relative to the benefit to the user.
