### ISSUE TITLE
How to edit README.md file from root folder in my computer so it appears in website when push

### ISSUE THREAD

**Issue by ogorodriguez** [workflowr/workflowr#230]
I want to know how to edit the README file from the root folder so it has more info other than 

_A [workflowr][] project.

[workflowr]: https://github.com/jdblischak/workflowr_

Is it possible?  thanks.

**Comment by jdblischak** [comment]
@ogorodriguez Yes! You can edit `README.md` with the following steps:

1. Open `README.md` in your text editor (e.g. RStudio)
1. Make your edits
1. Commit the changes:
    ```
    wflow_git_commit("README.md", "Update README")
    ```
    Note that the second argument is the commit message. In general, the more descriptive you make it, the more likely your future self will understand your intentions when you review your development history.
1. Push changes with `wflow_git_push()`

This is the general strategy for editing any non-Rmd file in a workflowr project.

Lastly, it is not required to use workflowr functions to commit changes to non-Rmd files. `wflow_git_commit()` and `wflow_git_push()` are provided for convenience so that you can run Git commands easily in the R console. If you prefer using Git in the terminal, the above steps are equivalent to running the following:

```
git add README.md
git commit -m "Update README"
git push
```

**Comment by ogorodriguez** [comment]
Thanks a lot!
