### ISSUE TITLE
wflow markdown doc does not allow sql chunk execution

### ISSUE THREAD

**Issue by kieran-mace** [workflowr/workflowr#236]
Using a the workflowr workflow, my sql chunks can no longer be executed. If I copy my notebook to a regular notebook, things work fine:

with 
```
---
title: "a_title"
author: "Me"
date: "2021-01-23"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
I get no option to execute the sql chunk
```
![Screen Shot 2021-01-27 at 12 15 24 PM](https://user-images.githubusercontent.com/18296227/106049113-9ec6f080-609a-11eb-93f2-4c2f0c5ae355.png)

with: 
```
---
title: "R Notebook"
output: html_notebook
---
```
everything works great. 
![Screen Shot 2021-01-27 at 12 25 59 PM](https://user-images.githubusercontent.com/18296227/106049313-dafa5100-609a-11eb-9380-ee977e0d58b1.png)

**Comment by kieran-mace** [comment]
Could this be because`workflowr::wflow_html` extends `html_document` and not `html_notebook`? curious that R chunks work, but other engines do not.

**Comment by jdblischak** [comment]
Thanks for taking the time to report this. A few questions to help me troubleshoot:

* Does your SQL code chunk work with `output: html_document`?
* What happens when you click on the "Knit" button for the workflowr Rmd file?
* What happens when you run `wflow_build()` for the workflowr Rmd file? Is there an error message?

**Comment by jdblischak** [comment]
Here's an example Rmd file that works for me when I include it in a workflowr project. Both the Knit HTML button and `wflow_build()` work. The Run All Chunks button doesn't work because that sends the SQL code chunk to the R console.

````
---
title: "sql"
author: "John Blischak"
date: "2021-01-27"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r}
library(DBI)
con <- dbConnect(RSQLite::SQLite(), "data/text.sqlite")
dbWriteTable(con, "mtcars", mtcars, overwrite = TRUE)
```

```{sql connection=con, output.var="result"}
SELECT * FROM mtcars WHERE cyl = 4
```

```{r}
head(result)
dbDisconnect(con)
```

````

**Comment by kieran-mace** [comment]
Yes can confirm that your script works for me too. 

This is not a bug, but a function of workflowr docs being rmarkdown and not rnotebooks. To run workflowr interactively as a notebook, before publishing, one should create an rnotebook, iterate, then change the Rmd file to have a `output: workflowr::wflow_html` configuration before publishing

**Comment by jdblischak** [comment]
> The Run All Chunks button doesn't work because that sends the SQL code chunk to the R console.

Actually I was wrong about this. You should be able to use the Run All Chunks button as well. There is no need to use `html_notebook` first.

Try following these steps:

1. Change the YAML header to show chunk input inline:

    ```
    output: workflowr::wflow_html
    editor_options: 
      chunk_output_type: inline
    ```

1. Make sure the "Knit Directory" used by RStudio matches the value of `knit_root_dir` specified in `_workflowr.yml`. Unfortunately the defaults are mismatched. By default RStudio runs the code in the "Document Directory". In the context of a default workflowr project setup, this would be `analysis/`. In contrast, by default workflowr runs the code in the "Project Directory" (`knit_root_dir: "."` essentially means: run the code in the same directory as `_workflowr.yml`). To fix this, click on the dropdown next to the Knit button, and select "Project Directory".

    ![image](https://user-images.githubusercontent.com/1608317/106070061-be2d4000-60d1-11eb-9587-ddf126997d56.png)

1. Restart the R session: `Session` -> `Restart R and Clear Output`

1. Run all chunks. The code should be displayed inline.

1. Click Knit HTML (or use `wflow_build()`). You should see the results in your workflowr website.

Please let me know if the above steps work for you. I suspect the issue you were having was likely due to the fact that RStudio was running the code from `analysis/` whereas workflowr was using the project directory.

**Comment by jdblischak** [comment]
Quick update: As an alternative to specifying

```
editor_options: 
  chunk_output_type: inline
```

You can also delete these two lines entirely.

**Comment by jdblischak** [comment]
Another quick update: here's a relevant thread on how RStudio changes the working directory to the location of the Rmd file. As far as I know, it's not possible to configure the global setting for the Knit Directory in RStudio (but I'd love to be informed that this is now possible).

https://github.com/rstudio/rstudio/issues/2595#issuecomment-451986362
