### ISSUE TITLE
Container feature from bootstrap3 template not working 

### ISSUE THREAD

**Issue by FedericoComoglio** [workflowr/workflowr#237]
Hi @jdblischak,

I am working with the [flatly](https://bootswatch.com/3/flatly) template (bootstrap3 version). I am not able to include containers other than Jumbotron or list groups. I also reproduced this issue by downloading the CSS template from [bootswatch](https://bootswatch.com) and calling it from the `_site.yml` config file.

My understanding is that `rmarkdown` does not support bootstrap4 but I thought all bootstrap3 features listed on bootswatch should work. Is this the case?

Thanks a lot in advance!

**Comment by jdblischak** [comment]
@FedericoComoglio Thanks for opening this issue. You should be able to use bootstrap3 with workflowr. The workflowr buttons are all created with bootstrap3.

A few questions to help me investigate:

1. What version of rmarkdown are you using? Last I checked, they are working on supporting bootstrap4, so if you downloaded directly from GitHub, you may have an in-progress version.

1. Could you please share a minimal example of the HTML you'd like to include?

1. Are you able to accomplish what you want outside of the workflowr context? You can test this by putting a `_site.yml` and `index.Rmd` in a directory, and then running `rmarkdown::render_site()`? If it works for rmarkdown, it should continue to work with workflowr.

**Comment by FedericoComoglio** [comment]
Thank you very much for looking into this, @jdblischak. To your points:

1. I am currently using `rmarkdown` 2.6
2. The only group of features that I cannot successfully include at the moment are containers, e.g. this panel:

```
<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Panel danger</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
</div>
```

3. Excellent point. I have generated a reprex with the following `_site.yml` content:

```
name: test
output_dir: _site
output:
  html_document:
    theme: flatly
    highlight: textmate
```

and the following `index.Rmd`:

```
---
title: "Home"
site: test
output:
  html_document:
    toc: false
---

<a href="#" class="btn btn-danger">Danger</a>

<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Panel danger</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
</div>
```

The button is rendered correctly, while the panel is not. I conclude this issue has, therefore, nothing to do with `workflowr`. Feel free to close it, I will migrate it to `rmarkdown`.

Thanks a lot for your help!

**Comment by jdblischak** [comment]
Thanks for the minimal reproducible example. It made it easy to diagnose and fix the problem.

When I ran your example, I saw the following:

![image](https://user-images.githubusercontent.com/1608317/107451185-c4c9a780-6b14-11eb-9d91-759a5ff9e97c.png)

The outer panel was rendered correctly, but the inner content was not. This is due to a quirk of markdown/pandoc. There is more than one way to specify a code chunk. Instead of using the 3 backticks, you can indent by 4 spaces. Thus your HTML that was indented by 4 spaces was converted to verbatim text instead of interpreted as HTML.

Reducing the number of indented spaces to always be fewer than 4 fixes the issue.

```
---
title: "Home"
site: test
output:
  html_document:
    toc: false
---

<a href="#" class="btn btn-danger">Danger</a>

<div class="panel panel-danger">
  <div class="panel-heading">
  <h3 class="panel-title">Panel danger</h3>
  </div>
  <div class="panel-body">
  Panel content
  </div>
</div>
```

![image](https://user-images.githubusercontent.com/1608317/107451369-238f2100-6b15-11eb-8234-27446581140e.png)

The HTML isn't as readable, but this is sufficient for small HTML snippets. If you have longer HTML content, I'd recommend putting it in a separate HTML file and importing it via [`includes`](https://rmarkdown.rstudio.com/docs/reference/includes.html). This has the added benefit that it will get applied to every Rmd file in the site (assuming you specify it in `_site.yml`).

**Comment by FedericoComoglio** [comment]
Thank you, @jdblischak! I didn't think of this possibility. This solves my issue. Closing now.
