### ISSUE TITLE
wflow_clean. was originally: wflow is adding back old html files?

### ISSUE THREAD

**Issue by stephens999** [workflowr/workflowr#24]
Im' not sure what is going on and don't have time to investigate right now, but
seems odd: when i rename an rmd file it seems to confuse workflowr.
Sometimes it seems it is recreating the old html files in docs (for the version of the file
i removed). Or am i going crazy?

**Comment by jdblischak** [comment]
It shouldn't be recreating the old HTML. However, it doesn't automatically delete it yet. I am vary wary about deleting content, so I still have to implement this.

If you rename the file from `oldname.Rmd` to `newname.Rmd` and then build the site, then `docs/`will contain both `oldname.html` and `newname.html`. For now, you could remove `oldname.html` manually with `git rm -r docs/oldname.html docs/figure/oldname.Rmd`

**Comment by stephens999** [comment]
here's what seems to be happening: workflowr::wflow_commit("newname.Rmd") is saving
the figures in docs/figure/oldname.Rmd 
In this example, try1.Rmd is the old name

Note that try1 was never even added to the git repo as far as i remember. 
(at least, docs/figure/try1.Rmd was never added, as you can see it is untracked.)


Matthews-MacBook-Air-2:gtex-zcorr stephens$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	docs/figure/try1.Rmd/

nothing added to commit but untracked files present (use "git add" to track)

Matthews-MacBook-Air-2:gtex-zcorr stephens$ rm -r docs/figure/try1.Rmd/
Matthews-MacBook-Air-2:gtex-zcorr stephens$ open gtex-simple.Rproj 
Matthews-MacBook-Air-2:gtex-zcorr stephens$ ls
CITATION		README.md		code			docs			output
LICENSE			analysis		data			gtex-simple.Rproj
Matthews-MacBook-Air-2:gtex-zcorr stephens$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

AT THIS POINT I RAN 
workflowr::wflow_commit(commit_files = "analysis/est_zcorr_1.Rmd")


Matthews-MacBook-Air-2:gtex-zcorr stephens$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
Matthews-MacBook-Air-2:gtex-zcorr stephens$ git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	docs/figure/try1.Rmd/

nothing added to commit but untracked files present (use "git add" to track)
Matthews-MacBook-Air-2:gtex-zcorr stephens$ ls docs/figure/try1.Rmd/
unnamed-chunk-1-1.png	unnamed-chunk-2-1.png	unnamed-chunk-3-1.png	unnamed-chunk-4-1.png	unnamed-chunk-4-2.png

**Comment by jdblischak** [comment]
I figured out what is happening. This was an unexpected quirk of the function `rmarkdown::render_site`. Even though I only pass it one file to render, e.g. `rmarkdown::render_site("est_zcorr_1.Rmd")`, it always copies the entire `figure/` subdirectory from `analysis/` to `docs/`. What is happening to you is that the figure files previously created by `try1.Rmd` still exist in `analysis/figure/try1.Rmd`. You aren't notified by `git status` about these files because `analysis/figure` is in `.gitignore` (to prevent users from saving duplicate copies of figures). When you run `wflow_commit(commit_files = "analysis/est_zcorr_1.Rmd")`, it only renders that specific file, but then it also copies the entire contents of `analysis/figure`.

In the short term, you can fix this issue by deleting the unnecessary figures from both `docs/` and `analysis`.

```
rm -r docs/figure/try1.Rmd
rm -r analysis/figure/try1.Rmd
```

In the long term, I am planning on writing a function called `wflow_clean` that searches both `analysis/` and `docs/` for no longer needed files.

Another option would be to create a custom site generator to be used by `render_site` instead of using the default. At this point I'd like to avoid resorting to that option because that would likely completely lock a user into using workflowr.

**Comment by jdblischak** [comment]
I am labeling this issue as an "enhancement". The plan is to find orphaned image files like the ones that caused problems here with a function like `wflow_clean`.

**Comment by jdblischak** [comment]
The issues discussed above have been solved in workflowr 1.0+. The custom site generator `wflow_site()` only copies the figure directory of the Rmd file being built, `wflow_publish()` deletes unused figure files,  and both`wflow_rename()` and `wflow_remove()` handle figure files.
