### ISSUE TITLE
Is there a possibility to have the contrib and about files in the final report and in github as md files?

### ISSUE THREAD

**Issue by Jo-Schie** [workflowr/workflowr#243]
I add a lot of information to my about.md and contrib.md files about my ongoing project, and I was wondering whether it was possible to include them somehow into the website build as well. 

My first thought was to simply copy the md files to the analysis directory and then build the website, but that would not work. The package description states for the `wflow_build()` function:

_files: character (default: NULL). Files to build. Only allows files in the analysis directory with the extension Rmd or rmd. If files is NULL, the default behavior is to build all outdated files (see argument make below). Supports file globbing. The files are always built in the order they are listed._

My second thought was that maybe it was possible to somehow convert md files to Rmd before copying them, but that  [seems to be not straight forward](https://stackoverflow.com/questions/12277622/convert-a-md-file-back-to-rmd). 

My third thought was that maybe I can specify two outputs in the yaml header something along [these lines](https://stackoverflow.com/questions/25078572/specifying-multiple-simultaneous-output-formats-in-knitr). But I guess that would also not work, because  `wflow_build()` specifies the output folders for the rendered documents and the about.md is kept in the `analysis` directory. In addition there is information in the `.md` file that is included by the `wflow_build()` routine and is not the standard format for Github. I tested this by creating an README.Rmd with the following header:

```R
---
title: "README"
output:
  workflowr::wflow_html:
    toc: false
    keep_md: yes
  md_document:
    variant: markdown_github
editor_options:
  chunk_output_type: console
---

Describe your project.

```
So last idea would be to just create links in the README.md and CONTRIB.md to the rendered html files from the final website. That is currently the only really easy to implement and maintain option that I can think of but maybe I missed something?

**Edit**: I just saw that maybe the last option could be to do that at the time of publishing? Description states that 

_wflow_publish is the main workflowr function. Use it when you are ready to publish an analysis to your site. wflow_publish performs three steps: 1) commit the file(s) (can include both Rmd and non-Rmd files, e.g. _site.yml),_

**Comment by jdblischak** [comment]
I propose importing your `about.md` and `contrib.md` into corresponding Rmd files and printing the content. This will duplicate the same information on your website. Please try it out and let me know if this works for you.

Here's a small example. Let's say you have a Markdown file at the root of your project named `about.md` that contains the following:

````
# About

**bold text**

```
code chunk
```
````

You can import this into `analysis/about.Rmd` and print the text verbatim (so that it gets rendered properly as Markdown). Note that I remove the first line of `about.md` so that the titles aren't duplicated.

````
---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r echo=FALSE, results='asis'}
cat(readLines("about.md")[-1], sep = "\n")
```
````

Then whenever you make a change to `about.md`, you can commit the changes and also update the website by running the following. It commits `about.md` (and `analysis/about.Rmd` if you edited it), builds `analysis/about.Rmd`, and then commits `docs/about.html`.

```
wflow_publish(c("about.md", "analysis/about.Rmd"), "Update about page")
```

Here's the result I see for this minimal example:

![image](https://user-images.githubusercontent.com/1608317/110950395-cc49bf80-8311-11eb-83b2-a2dac28a65c2.png)

**Comment by Jo-Schie** [comment]
That works like a charm @jdblischak ! Thank you very very much. Package is Great btw! First time user but certainly not last! 

Maybe that could be something for a future release to be able to add Contrib. Readme and liscence from root? Anyways, very convenient like this as well and the results are perfect!

**Comment by jdblischak** [comment]
> That works like a charm @jdblischak ! Thank you very very much. Package is Great btw! First time user but certainly not last!

@Jo-Schie Thanks for the positive feedback! It's very motivating. Glad to hear you're enjoying workflowr.

> Maybe that could be something for a future release to be able to add Contrib. Readme and liscence from root? Anyways, very convenient like this as well and the results are perfect!

I'm not planning on automating this option, but I'm very open to Pull Requests to update the documentation. If you're interested, you could add a section on this solution to the vignette on customizing the website: https://github.com/jdblischak/workflowr/blob/master/vignettes/wflow-02-customization.Rmd
