### ISSUE TITLE
"Home" (`index.Rmd`) could mirror README contents

### ISSUE THREAD

**Issue by pat-s** [workflowr/workflowr#247]
Currently when starting a fresh project the contents of `index.Rmd`, which will create the subsequent entry-page "Home" for the project, is quite sparse.

In addition I came across the fact that often I would like to have the contents of README.md mirrored in the "Home" page of the workflow website.
However, one does not want to maintain two files.

Hence, I am using the following approach for `index.Rmd`.
Setting aside the stylistic options I chose in the example below, the mirroring of the README.md could be a good default?

````r
---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: yes
    toc_float: yes
    theme: paper
    highlight: textmate
editor_options:
  chunk_output_type: console
---

```{r, echo=FALSE, results='asis'}
readme = readLines("README.md")
writeLines(readme)
```
````

**Comment by jdblischak** [comment]
@pat-s Thanks for sharing your idea and solution. I agree this is a good use case to reduce duplication. It's similar to Issue #243. My answer here is the same as there though, i.e. I don't want to change the default, but I'd be interested in documenting this better. I think the trick of re-using the standard MD files from the root would make a good section in the customization vignette.

I've also been thinking about how to make it easier for users to customize the template used by `wflow_start()`. I'm still at the brainstorming stage, but I'm thinking of adding an argument `template` to `wflow_start()`. It would accept either a URL to a Git repo or a path to a local directory, and it would use those files instead of the default ones. I'd be happy to hear any feedback on this proposed approach.
