### ISSUE TITLE
Support for more bootstrap themes

### ISSUE THREAD

**Issue by tatakof** [workflowr/workflowr#259]
Will there be more support for the remaining bootstrap themes? (those found on bootswatch.com but not supported by workflowr)

**Comment by jdblischak** [comment]
@franfram Thanks for the question!

Support for bootswatch.com themes is provided by the rmarkdown package. The workflowr package combines rmarkdown+Git. Because it extends rmarkdown, any feature you can use with `rmarkdown::html_document()`, you should also be able to use with `workflowr::wflow_html()`.

https://bookdown.org/yihui/rmarkdown/html-document.html#appearance-and-style

> theme specifies the Bootstrap theme to use for the page (themes are drawn from the Bootswatch theme library). Valid themes include default, cerulean, journal, flatly, darkly, readable, spacelab, united, cosmo, lumen, paper, sandstone, simplex, and yeti. Pass null for no theme (in this case you can use the css parameter to add your own styles).

So if the rmarkdown developers were to support more bootswatch themes in the future, these would also be available to use with workflowr.

However, I did a quick search and found this [RStudio Community post](https://community.rstudio.com/t/in-rstudio-rmarkdown-how-to-add-new-html-themes-from-bootswatch/15791/3) about this very question. The user was able to use a different bootswatch theme by downloading the CSS file and specifying it in the YAML header. In the workflowr framework, you would save the CSS file in `analysis/` and then specify it in `analysis/_site.yml` to apply it to all of your web pages ([see the workflowr documentation on using custom CSS for more details](https://jdblischak.github.io/workflowr/articles/wflow-02-customization.html#style-with-custom-css)).

Even better though, I was looking through the rmarkdown issues and found this solution: https://github.com/rstudio/rmarkdown/issues/1988#issuecomment-763439930 If you are using a recent version of rmarkdown, you should be able to list any bootswatch theme. I did a quick test to confirm that this works by editing `analysis/_site.yml` as shown below:

```
output:
  workflowr::wflow_html:
    theme:
      bootswatch: lux
```

**Comment by neosanma** [comment]
Thank you very much, John!
