### ISSUE TITLE
Support for Quarto please

### ISSUE THREAD

**Issue by lachlansimpson** [workflowr/workflowr#278]
Before posting your issue, please search the existing issues (both "open" and "closed") to check that a similar feature has not already been requested.

1. Describe the suggested feature.

Quarto is a new "Open source scientific and technical publishing system" being built by RStudio.
https://github.com/quarto-dev/

3. Describe why you think this feature is needed.

While Quarto will not replace RMarkdown, it is being developed with the knowledge gained from developing RMarkdown.

**Comment by jdblischak** [comment]
Hi @datakid, I'd love to support quarto! However, when I investigated back in April, I couldn't figure out a way to integrate quarto. Do you have any insight or suggestions?

Here are the details. The workflowr package is an R Markdown extension package. It defines a [custom site generator](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html#custom-site-generators), [`wflow_site()`](https://workflowr.github.io/workflowr/reference/wflow_site.html), and a [custom output format function](https://bookdown.org/yihui/rmarkdown/new-formats.html), [`wflow_html()`](https://workflowr.github.io/workflowr/reference/wflow_html.html). This is how workflowr is able to automatically inject its reproducibility features while the file is rendered from Rmd to HTML.

This is the exact same strategy used by, eg [bookdown](https://github.com/rstudio/bookdown). Its custom site generator is [`bookdown_site()`](https://pkgs.rstudio.com/bookdown/reference/bookdown_site.html), and it provides multiple custom output format functions, eg [`html_document2()`](https://pkgs.rstudio.com/bookdown/reference/html_document2.html). Without the line `site: bookdown::bookdown_site` in the YAML header of the file `index.Rmd`, as can be seen in [bookdown-demo](https://github.com/rstudio/bookdown-demo/blob/5331ffcb5bc0ed3d86c8d94774f515080ff7dae4/index.Rmd#L5), bookdown can't inject its features.

As far as I can tell, the bookdown maintainers are not planning on integrating quarto files. Sources:

https://community.rstudio.com/t/bookdown-evolution-in-response-to-quarto/133163
https://github.com/search?q=repo%3Arstudio%2Fbookdown+quarto&type=issues
https://github.com/rstudio/bookdown/search?q=qmd&type=issues

And as far as I can tell, there is no way to easily integrate an rmarkdown-powered R package to incorporate quarto files. I can't find a [custom output format function exported from the quarto R package](https://github.com/quarto-dev/quarto-r/blob/main/NAMESPACE), and the [FAQ for R Markdown Users](https://quarto.org/docs/faq/rmarkdown.html#can-you-create-custom-formats-for-quarto-like-you-can-for-r-markdown) makes it clear that the [quarto extension system for custom formats](https://quarto.org/docs/extensions/formats.html) does not allow injecting R code that executes during the rendering process:

> A major difference with custom output format in R Markdown is that Quarto Extension does not use R but Lua, for example if you need to add some logic behind custom metatada fields.

Thus unless I am missing a potential solution, creating a workflowr-like experience for quarto docs (eg automated version control and other reproducibility features) would require rewriting the features in Lua for a new quarto custom format. This is in theory possible, but it would require a substantial investment of development time.

**Comment by jdblischak** [comment]
Another data point: `rmarkdown::render()` supports the `.Qmd` file extension

https://github.com/rstudio/rmarkdown/blob/607290ccab1ec1acab419bf0a05f1d046d4596b5/R/render.R#L349

So it might be possible to update workflowr to include files with the `.Qmd` extension within a workflowr project. However, at the end of the day, they'd likely be rendered using the rmarkdown theme for the entire website (ie just like an Rmd file), which is presumably not what you want (since it defeats the purpose of using quarto if the only difference is the file extension). I'd be more than happy to be proven wrong though!

**Comment by jdblischak** [comment]
Another data point: Quarto support for blogdown has been discussed but as of now there is no support for `.Qmd` files https://github.com/rstudio/blogdown/issues/692

**Comment by lachlansimpson** [comment]
Hi @jdblischak Thank you for the comprehensive answer! I didn't have a specific need, I was asking because I was at an R Ladies talk about `workflowr` and the question came up. When I came looking for an answer (open and closed tickets, FAQ), I didn't see one. I appreciate your work, thank you.

**Comment by jdblischak** [comment]
No worries @datakid! I had been meaning to gather my thoughts on how to potentially integrate quarto files into workflowr, and your Issue was the motivation I needed to write everything down. I've been frustrated that I haven't been able to think of a workaround. I see you are at RStudio. If it ever comes up, I'd appreciate it if you could advocate for some sort of "bridge" to support quarto files for authors like me that maintain rmarkdown-based packages. If an output format function could be exported from the quarto R package, and some edits made to `rmarkdown::render_site()`/`rmarkdown::render()` to run `quarto` via system calls for the Qmd files, then it could potentially be much easier to support both Rmd/Qmd files.

**Comment by lachlansimpson** [comment]
Hi @jdblischak, good questions, well spotted. I've asked around - I think your best bet is to raise it as a feature request in the Quarto GH repository - either the [quarto-r](https://github.com/quarto-dev/quarto-r) or [quarto-cli](https://github.com/quarto-dev/quarto-cli) or a combination?

**Comment by lachlansimpson** [comment]
Hi @jdblischak just thought I'd drop you a line - not sure if this covers your needs, but it looks like `blogdown` is getting talked about - I thought you might like to weigh in on those discussions?

https://github.com/quarto-dev/quarto-cli/issues/3917
https://github.com/quarto-dev/quarto-r/issues/22

**Comment by jdblischak** [comment]
@datakid Thanks for your continued engagement on this Issue. I really appreciate your support.

> not sure if this covers your needs, but it looks like `blogdown` is getting talked about

That Issue seems like a reasonable request to me. It's essentially the quarto-r equivalent of `rmarkdown::draft()`, `blogdown::new_post()`, `worfklowr::wflow_open()`, etc. They'll have to implement it in quarto-cli first (the other Issue you linked), so I suspect it's mainly an issue of priority compared to other in-development features.

> I think your best bet is to raise it as a feature request in the Quarto GH repository

I took some time today to play with quarto to better familiarize myself. I imagine two scenarios:

1. Integrate the workflowr reproducibility features into quarto documents (eg confirm qmd is committed to Git repo, list of past versions, clean environment, append session info, etc)
2. Integrate quarto rendering features into a workflowr project. In other words, use quarto's HTML formatting, cross-formatting, multi-column figures, etc.

At this point I'm not hopeful about either prospect. For scenario 1, I found the Issue https://github.com/quarto-dev/quarto-r/issues/21, in which one of the core maintainers of rmarkdown/quarto unambiguously [states](https://github.com/quarto-dev/quarto-r/issues/21#issuecomment-1185684448): 

> Custom format for R Markdown are R functions and can only be used with R Markdown. They won't work with Quarto.
>
> Authors of custom formats would need to port them to Quarto extensions format.

Then for scenario 2, I'm not sure how to make that convenient enough to be worthwhile. I could allow users to put `.Qmd` files in their workflowr projects, but then what to do with them. I could treat them like R Markdown files, which would get them the workflowr reproducibility features, but none of the quarto authoring/formatting features, so it'd be no different than naming them `.Rmd`. Alternatively, with more work, I could update workflowr to run `quarto_render()` on any `.Qmd`/`.qmd` files. During the rendering I could inject a `_quarto.yml` file with settings to match a typical R Markdown based website as closely as possible (eg to share the same navigation bar). I'm sure there would be some troubleshooting involved, but this at least seems feasible to me. But then these quarto files wouldn't have any of the reproducibility features, which mostly defeats the purpose of using workflowr in the first place.

Can you (or anyone else) think of other potential scenarios? I'm open to attempting some sort of integration if someone can describe a compelling use case. But with the inability to use `wflow_html()`/`wflow_site()` with quarto documents, and the fact that quarto already provides lots of quality of life development tooling for [projects in general](https://quarto.org/docs/projects/quarto-projects.html) and [websites in particular](https://quarto.org/docs/websites/), I'm struggling to see the motivation.

That being said, I'd love to see some of the reproducibility features pioneered in workflowr (especially the tight integration with version control) ported to quarto, either directly or via extensions. I'm a freelancer, and I have some basic experience writing Lua scripts, so please let your Posit colleagues know that they can reach out if they're interested in hiring me to implement these features :-)
