### ISSUE TITLE
multiple folders under analysis

### ISSUE THREAD

**Issue by hazeljanderson** [workflowr/workflowr#280]
Is it possible to implement workflowr with multiple subfolders under the analysis subdirectory? I have my project organized according to the Environmental Data Initiative's [thematic standardization](https://edirepository.org/resources/thematic-standardization). Ideally, under my analysis subdirectory, I would have L0, L1, and L2 folders with .rmd files in each. The resulting rendered HTML files would also follow the same format and the website would be rendered with the L0, L1, and L2 folders as drop-down menus.

**Comment by jdblischak** [comment]
@hazeljanderson Thanks for the question. Unfortunately this is a limitation of the rmarkdown package (which is what workflowr uses to build the website). Other users have requested this in the past, and in fact they have hacked together some workarounds that you may be interested in

* #220 
* #95

Nested subdirectories get complicated because the website files each need to share resources (like CSS and JS), and it's difficult to produce the correct path to these external files when each HTML file is potentially in a different subdirectory.

That being said, there does appear to be some progress on this issue in the rmarkdown repo: https://github.com/rstudio/rmarkdown/pull/2199 To encourage the development of this feature, you can upvote (put a thumbs up) the PR, review the PR, and/or test it out

xref: https://github.com/rstudio/rmarkdown/issues/146, https://github.com/rstudio/rmarkdown/issues/1859

In practice, I recommend using filename prefixes to organize your analysis files by theme, e.g. `analysis/L0-file1.Rmd`, `analysis/L0-file2.Rmd`, `analysis/L1-file1.Rmd`, etc.

**Comment by yihui** [comment]
FYI a quick update from {rmarkdown}: https://github.com/rstudio/rmarkdown/issues/1859#issuecomment-5431523808
