### ISSUE TITLE
rmarkdown::render and fig.path warning

### ISSUE THREAD

**Issue by fkgruber** [workflowr/workflowr#283]
I have an Rmarkdown which has no fig.path set anywhere. If I run wflow_build the html is generated without issues. however, If I use rmarkdown::render I get the warning
`Warning! The custom fig.path you set was ignored by workflowr. `
under every figure.

So it seems that using render the fig.path is being set triggering the workflowr warning. Is there a way to prevent this from happening? I would like to use render to generate my html without that warning.

thanks
FKG

**Comment by jdblischak** [comment]
> If I use rmarkdown::render I get the warning
>
>  I would like to use render to generate my html without that warning.

@fkgruber Could you please provide some more context and motivation for why you are using `rmarkdown::render()`? Is there a reason you don't want to use `wflow_build()` or the RStudio Knit button? Are you trying to create a standalone HTML file, ie an HTML file that embeds all of its resources directly into the file so that it can be viewed outside of the full website context?

**Comment by fkgruber** [comment]
The main reason is that while writing the R markdown I would like to see what the html is looking like without having to re-run everything as required by wflow_build. With rmarkdown::render I can use the existing variables in the workplace to generate the html.

However, I just realized that if I do local=T it seems to behave the same as render. Is that right?

**Comment by jdblischak** [comment]
You could use `wflow_build(local = TRUE)`, but I think [`wflow_run()`](https://workflowr.github.io/workflowr/reference/wflow_run.html) might be the better option given that you are interactively developing the analysis. Also, for faster rendering of the HTML itself, you could also use knitr's caching feature:

````
```{r setup}
knitr::opts_chunk$set(cache = TRUE)
```
````

And then when you're finished with the analysis, you can change it to `cache = FALSE`, delete that chunk entirely, or run `wflow_publish()` with `delete_cache = TRUE`. No matter which option you choose, workflowr will detect if a chunk accessed a cached result and warn you about it (since relying on the cache for your final results is potentially disastrous from a reproducibility standpoint).

**Comment by fkgruber** [comment]
I just noticed that wflow_build with local=T is not standalone. I would like to be able to get standalone htmls in order to easily share the html.  I know rmarkdown::render does generate standalone but then we get all these warnings.

Is there a way to either make wflow_build with local=T generate a standalone html or remove that fig.path warning from rmarkdown::render?
thanks 
FKG

> > If I use rmarkdown::render I get the warning
> > I would like to use render to generate my html without that warning.
> 
> @fkgruber Could you please provide some more context and motivation for why you are using `rmarkdown::render()`? Is there a reason you don't want to use `wflow_build()` or the RStudio Knit button? Are you trying to create a standalone HTML file, ie an HTML file that embeds all of its resources directly into the file so that it can be viewed outside of the full website context?

**Comment by jdblischak** [comment]
I am having trouble reproducing the `fig.path` warnings. Could you please share the exact command you are running to execute `rmarkdown::render()`? The FAQ contains suggestions on how to create a [standalone file](https://workflowr.github.io/workflowr/articles/wflow-05-faq.html#html).

Here is a minimal, reproducible example I created. Could you please edit it so that it generates the `fig.path` warnings?

```R
library("rmarkdown")
library("workflowr")
tmpdir <- tempfile()
wflow_start(tmpdir, name = , change_wd = FALSE)
rmd <- file.path(tmpdir, "analysis", "test.Rmd")
rmd_lines <- c(
  "---",
  "title: \"test\"",
  "output: workflowr::wflow_html",
  "editor_options:",
  "  chunk_output_type: console", 
  "---",
  "",
  "```{r}",
  "plot(1:10)",
  "```",
  ""
)
writeLines(rmd_lines, con = rmd)
html <- render(rmd, html_document(), knit_root_dir = "..")
browseURL(html)
html_base <- render(rmd, html_document_base(), knit_root_dir = "..")
browseURL(html_base)
```

**Comment by fkgruber** [comment]
Hi
In your example if I remove the html_document and change the output file:
`html <- render(rmd,  knit_root_dir = "..",output_file="~/test.html")`
I get the warning
![image](https://github.com/workflowr/workflowr/assets/4311763/4f8f97e1-d921-46d4-9659-b0d2522cf997)

**Comment by jdblischak** [comment]
> remove the html_document and change the output file

Thanks. I confirmed that if I do the following two steps, I can reproduce the warning.

---

Here are two suggested workarounds. Please let me know if you like either of these options:

1. Use `html_document()` instead of the default `workflowr::wflow_html()`. This will allow you to set `output_file` to whatever you like. You can even pass the same arguments to `html_document()` so that the theme is similar (copied from `analysis/_site.yml`):

    ```
    html_theme <- render(rmd, html_document(toc = TRUE, toc_float = TRUE, theme = "cosmo",
                                            highlight = "textmate"),
                         knit_root_dir = "..", output_file = "~/test.html")
    browseURL(html_theme)
    ```

1. Don't specify a custom `output_file`. The standalone HTML file will be saved in `analysis/` (the standard, non-standalone HTML files are always moved to `docs/`). This will allow you to keep the rest of the workflowr features in the standalone file

**Comment by fkgruber** [comment]
Hi 
thanks
Yes I'm using solution 2 and not using output_file

FKG

**Comment by jdblischak** [comment]
@fkgruber Thanks for bringing this to my attention. I've [updated](https://github.com/workflowr/workflowr/commit/89ba735746f53521ae9f782034790552a1e25690) the [FAQ entry](https://workflowr.github.io/workflowr/articles/wflow-05-faq.html#html) to reflect this
