### ISSUE TITLE
How can I see the output of workflowr in real-time?

### ISSUE THREAD

**Issue by tkcaccia** [workflowr/workflowr#289]
My page contains very computationally expensive code.
I would like to know if there is a way to see in real-time the output of my R code of the Rmd file.

**Comment by jdblischak** [comment]
@tkcaccia thanks for using workflowr and thanks for your question

> is a way to see in real-time the output of my R code of the Rmd file

I'm not sure if I fully understand what you are requesting, so you may need to elaborate.

Do you want to be able to view the results of the code chunks directly in the Rmd file? If yes, you can edit the YAML header of the R Markdown file to use `inline` for the `chunk_output_type`, as below:

```yaml
editor_options:
  chunk_output_type: inline
```

I prefer the setting `console` because I like the R code to be sent directly to the R console. That way I can interactively explore and debug my R code in the console instead of inside a code chunk.

Alternatively, if you want to be able to view the entire rendered workflowr web page, I recommend you use caching for your chunks with long-running code. 

````
```{r setup}
knitr::opts_chunk$set(autodep = TRUE)
```

```{r long-running-code, cache=TRUE}
# long running code here
```
````

Then when your analysis is finished, you can pass the argument `delete_cache = TRUE` to `wflow_publish()` to ensure the results are still reproducible.

If this isn't what you are trying to accomplish, please describe in more details.

**Comment by tkcaccia** [comment]
Sure. I am running my code in a cluster. The workflowr function processes the Rmd correctly. 
I would like to see in the output that is generated in R what part of the code is running.
I copied here the output that I got (the last part)


```
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
27/39
28/39 [unnamed-chunk-13]
29/39
30/39 [unnamed-chunk-14]
31/39
32/39 [unnamed-chunk-15]
Loading .Rprofile for the current workflowr project
This is workflowr version 1.7.1
Run ?workflowr for help getting started
Loading .Rprofile for the current workflowr project
Loading .Rprofile for the current workflowr project
Loading .Rprofile for the current workflowr project
This is workflowr version 1.7.1
Run ?workflowr for help getting started
This is workflowr version 1.7.1
Run ?workflowr for help getting started
This is workflowr version 1.7.1
Run ?workflowr for help getting started                                                 
```

**Comment by jdblischak** [comment]
> I am running my code in a cluster.

Understood. Thanks for sharing the context and motivation.

> I would like to see in the output that is generated in R what part of the code is running.

Both `wflow_build()` and `wflow_publish()` have the argument `verbose = FALSE`. If you set this to `TRUE`, it will print the output from `rmarkdown::render_site()` directly to the R console, which should then show up in the stdout file created by whichever scheduler is installed on your HPC cluster. Another option would be to set the argument `log_dir` to an easily accessible directory so that you can directly monitor the log files created by workflowr (via the callr package).

In general this will be most useful if you give your code chunks informative labels. For example, I created a test Rmd file with the slow running chunks below:

````rmarkdown
```{r slow-chunk-1}
message("running first slow chunk")
Sys.sleep(5)
```

```{r slow-chunk-2}
message("running second slow chunk")
Sys.sleep(5)
```

```{r slow-chunk-3}
message("running third slow chunk")
Sys.sleep(5)
```
````

And the log file displays each code chunk label as it is executed, so you'd know where in the process your file is.

```
  |                                 
  |                           |   0%
  |                                 
  |..                         |   9%                                           
  |                                 
  |.....                      |  18% [seed-set-by-workflowr]                   
  |                                 
  |.......                    |  27%                                           
  |                                 
  |..........                 |  36% [slow-chunk-1]                            
  |                                 
  |............               |  45%                                           
  |                                 
  |...............            |  55% [slow-chunk-2]                            
  |                                 
  |.................          |  64%                                           
  |                                 
  |....................       |  73% [slow-chunk-3]                            
  |                                 
  |......................     |  82%                                           
  |                                 
  |.........................  |  91% [session-info-chunk-inserted-by-workflowr]
  |                                 
  |...........................| 100%  
```

Unfortunately all you can see is the chunk label and the percentage. This is a direct limitation of `rmarkdown::render_site()`. Even with the default setting of `quiet = FALSE`, this is all it displays. In other words, even if you add statements like `print()`, `message()`, or `cat()`, there is no way to report intermediate results while the R Markdown file is being executed.

**Comment by tkcaccia** [comment]
Thank you
