### ISSUE TITLE
function `dir.exists` not available for R<3.2.0

### ISSUE THREAD

**Issue by CreRecombinase** [workflowr/workflowr#32]
I was helping someone get up and running with `workflowr` who was running R 3.1.3, and she ran into the error: 
``` wflow_open("analysis.Rmd")
Error in wflow_open("analysis.Rmd") : 
could not find function "dir.exists"
```

It looks like this can be easily remedied by installing the package `backports` which re-implements functions introduced since R 3.0.0.

**Comment by pcarbo** [comment]
Nick, you should tell them it is about time they upgraded their 2-year old version of R! :)

An alternative is to change the `DESCRIPTION` file to read `Depends: R (>= 3.2.0)`.

**Comment by CreRecombinase** [comment]
That might be better, as it looks like she's running in to other issues with the older R version.

**Comment by jdblischak** [comment]
Good to know. Thanks for reporting this, @CreRecombinase.

The oldest R version I automatically check with Travis-CI is 3.2.5 (https://github.com/jdblischak/workflowr/commit/3c3f1dbb3c8d8b943d2baa344087693582c0a6f3). Travis also supports R 3.1.3, but I can't run on this version because of `devtools` errors (i.e. I wasn't aware of any workflowr-specific problem b/c the tests couldn't even be run).

Given that I can't easily perform automated tests on versions of R less than 3.2.5, I will change this in DESCRIPTION (it won't be merged into master until the next release though). And as you and @pcarbo noted, trying to use an older version of R with a package like workflowr that has lots of dependencies would be an exercise in frustration. Better to completely fail at install than constantly trying to debug subsequent errors.
