### ISSUE TITLE
Is `wflow_commit` a required step?

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#36]
Hi John,

Excellent work for putting together this package! I have been using it for several (collaborative) data analysis projects, and I find it very helpful!

I am wondering whether users are required to use `wflow_commit`. Sometimes, I get the following error when using `wflow_commit`:

```r
> wflow_commit(all=TRUE)

Rendering NA

Error: The specified directory '/home/maimaizhu/GitHub/replication-time/NA' does not exist.
```

I did not spend time to investigate why this happened. Instead, I am using the following recipe to publish the website, which seems to work fine:

1. In Rstudio: write `Rmd` files for my analyses
2. In Rstudio: run `wflow_build()` to obtain the `html` files 
3. In Shell: run `git add`, `git commit` and `git push`

**Is there any potential problem if I do not use `wflow_commit()` at all?**

**Comment by jdblischak** [comment]
> Excellent work for putting together this package! I have been using it for several (collaborative) data analysis projects, and I find it very helpful!

Wonderful! I'm glad you're finding it useful.

> I am wondering whether users are required to use wflow_commit. Sometimes, I get the following error when using wflow_commit:
> 
> wflow_commit(all=TRUE)
>
> Rendering NA
> 
> Error: The specified directory '/home/maimaizhu/GitHub/replication-time/NA' does not exist.

I'm not sure what exactly is causing that error. I cloned [replication-time](https://github.com/xiangzhu/replication-time) and took a quick look. The argument `all` is currently a bit confusing (one of the goals of the big update I am working on now is to clarify this option), so it would be easier for me to help you debug if I knew what you wanted to accomplish.

> I did not spend time to investigate why this happened. Instead, I am using the following recipe to > publish the website, which seems to work fine:
>
>    In Rstudio: write Rmd files for my analyses
>    In Rstudio: run wflow_build() to obtain the html files
>    In Shell: run git add, git commit and git push
>
> Is there any potential problem if I do not use wflow_commit() at all?

You can replicate the functionality of `wflow_commit()` manually, but it's a little more involved than your current steps. From `?wflow_commit`:

> worklowr facilitates reproducibility by placing the current SHA-1 of the Git repository at the top of each HTML file. This indicates which version of the code could be used to reproduce the results. In order for this to be meaningful, the R Markdown file must not have changed since it was last committed. wflow_commit can be invoked in 3 different (though not mutually exclusive) modes.

Thus you need to commit the Rmd files before building and committing the HTML files so that the SHA-1 displayed in the HTML corresponds to the exact state of the Git repository when it was built. Thus the steps to replicate `wflow_commit()` would be:

1. Once the Rmd files are ready, commit them (e.g. use `git add/commit` or RStudio Git GUI)
1. Build the HTML files that correspond to the Rmd files that were committed. `wflow_build()` isn't sufficient for this task if you had already built the HTML during your interactive testing. `wflow_build()` only looks at the modification times of the Rmd and HTML files (similar to how a Makefile works).
1. Add and commit the HTML files in `docs` and the corresponding figures in `docs/figure/`.

Do these steps make sense?

**Comment by xiangzhu** [comment]
Many thanks for the explanation!
