### ISSUE TITLE
Same Rmd files but updated input data files

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#40]
Hi John @jdblischak 

Here is a typical problem I often have when using `workflowr`:

1. Write an `analysis.Rmd` file with `input_data.file` as input, where `input_data.file` is stored in some external folders (e.g. `Dropbox`).
2. Do the following: `wflow_build()` -> `wflow_view()` -> `wflow_commit()` -> `git push`.
3. After a while, update `input_data.file` but use the **same** `analysis.Rmd` file.
4. Re-do the following: `wflow_build()` -> `wflow_view()`

I hope that the corresponding `analysis.html` reflects the change of update in `input_data.file`, but it seems that the html files remain the same ...

```r
> wflow_build()
All HTML files have been rendered
``` 
Do you know how to solve this problem? Thanks!

**Comment by jdblischak** [comment]
Great question, @xiangzhu. The latest release of workflowr is not designed to handle your situation very well. In order to build and commit the html to include on the website, there needs to be a committed change to the Rmd file. Thus to fix this immediately, you could add a short line to the Rmd file like "Using the version of `input_data.file` from 2017-06-12" and then commit the Rmd file with `wflow_commit`.

Your situation will be handled easily in the next release of workflowr (will happen later this week. I just have to update all the documentation). The new function `wflow_publish` will build any specified files and commit the HTML files even if the Rmd files themselves have not been changed. So something like this:

```
wflow_publish("file-with-updated-input-data.Rmd")
```

I'll post on Slack when this new release is available.

**Comment by xiangzhu** [comment]
Yes, I am using the same quick fix as you suggested.

I am looking forward to the next release. Thanks!

**Comment by pcarbo** [comment]
To be clear, @xiangzhu, workflowr will only recognize updates to files that are tracked by git. (@jdblischak Please correct me if I am wrong.)

**Comment by jdblischak** [comment]
> To be clear, @xiangzhu, workflowr will only recognize updates to files that are tracked by git. (@jdblischak Please correct me if I am wrong.)

@pcarbo I'm not sure what distinction you are referring to. `wflow_publish` can recognize many files in many different states depending on the arguments specified by the user. However Xiang is not relying on any of the automated detection capabilities of `wflow_publish`. In his specified use case (a previously published Rmd file that has not changed, but the underlying data has), the solution to add the updated HTML to the website is straightforward:

```
wflow_publish("analysis/file.Rmd")
```

Ideally the underlying data file would be small enough to be under version control, which would make the Git history more informative. But in this case with a big data file, I think this workflow works well enough.

**Comment by pcarbo** [comment]
@jdblischak I'm glad to hear the solution is straightforward!

**Comment by jdblischak** [comment]
@xiangzhu Your workflow should now be supported with [workflowr 0.5.0](https://github.com/jdblischak/workflowr/releases/tag/v0.5.0). Please re-open this Issue if you have any trouble after upgrading
