### ISSUE TITLE
Add Gitlab instructions to "Getting started" vignette

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#42]
I expect that the instructions will not be that different for [Gitlab](http://gitlab.com), but it would be nice to show that `workflowr` works for websites other than Github.

**Comment by jdblischak** [comment]
I agree that we should demonstrate that workflowr can be used with other hosting sites. However, I don't think it should be in the Getting started vignette. This already has so many details and could potentially confuse more novice users (who may not yet be clear on the exact differences between Git and GitHub).

[GitLab Pages](https://about.gitlab.com/features/pages/) will host a static site at https://username.gitlab.io/projectname. However, I don't know if it has a trick that allows serving from the `docs/` subdirectory like GitHub Pages.

**Comment by pcarbo** [comment]
@jdblischak Sure, from the Getting Started we could link to a separate page with more details on using GitLab instead of Github. (Obviously, there are other sites like Bitbucket, but Gitlab is logical because it targets scientists.)

**Comment by jdblischak** [comment]
Tip from @jimhester: We can create links to past versions of the HTML pages hosted on GitLab using http://raw.githack.com/ (we currently use https://rawgit.com/, which only supports GitHub).

**Comment by lazappi** [comment]
I have been playing around with this on our local Gitlab instance. It seems be working ok, except for links to past HTML versions (as in the comment above). For reference here are the things people need to do (hopefully haven't missed anything):

* Manually set up your git remote
* Add a `.gitlab-ci.yml` file
* (you may need to set up a gitlab-runner depending on the instance, but that's not really a workflowr problem)
* Copy the `docs/` directory to `public/`(this has to be done after every change you want to publish)
* Set the `github` attribute in `_workflowr.yml` (for links to work)

Otherwise it seems to work ok, although I have only tested it with the vignette example so there could be issues with more complex projects. I guess the docs/public directory issue is the biggest problem for workflowr and it would be great if there was some way to address that to avoid the copying (maybe via a `_workflowr.yml` option?).

**Comment by jdblischak** [comment]
> I have been playing around with this on our local Gitlab instance.

@lazappi Thanks for investigating this!

> For reference here are the things people need to do (hopefully haven't missed anything):

Would like to help write a vignette for setting up GitLab or would you prefer to review/modify something I write?

>    Add a .gitlab-ci.yml file

Could you please copy-paste an example `.gitlab-ci.yml` file?

>    Copy the docs/ directory to public/(this has to be done after every change you want to publish)
> I guess the docs/public directory issue is the biggest problem for workflowr and it would be great if there was some way to address that to avoid the copying (maybe via a _workflowr.yml option?).

This isn't a problem for workflowr, it just isn't documented (since it currently requires running Git in the Terminal). The `docs/` directory can be renamed using `git mv` and then the output directory changed in `analysis/_site.yml` from `../docs` to `../public`.

```
sed -i s/docs/public/ analysis/_site.yml # unix-only
git add analysis/_site.yml
git mv docs/ public/
git commit -m "Switch to hosting with GitLab"
```

I'd like to create a workflowr equivalent for renaming files and subdirectories so that this can all be done with R, but wrapping Git commands is labor intensive (e.g. to implement all the necessary error-handling to prevent users from borking their Git repo).

The only downside to this approach is that previous versions of the HTML file when it was in `docs/` will no longer be reported on the workflowr webpages, but this won't be an issue if GitLab is used from the beginning of the project.

>    Set the github attribute in _workflowr.yml (for links to work)

Ugh, naming things is hard. I'm glad this works, but it sure is awkward. Unfortunately the other option of choosing a generic name like `git_host` would likely be confusing to novice Git users, so I'm going to leave this as it is for now.

**Comment by jdblischak** [comment]
@lazappi I apologize for the delay in implementing GitLab support (I got distracted by other projects). I am pushing for an upcoming workflowr release, and I've added support for GitLab. There is now a dedicated function `wflow_use_gitlab()` that automates almost every step (the user still has to manually create the repository on GitLab). I've also updated the links to past versions to use raw.githack (#134), so now past versions of HTML files can be conveniently viewed directly from the web browser. Here are some demos: [wflow-gitlab](https://jdblischak.gitlab.io/wflow-gitlab/), [test-gitlab](https://jdblischak.gitlab.io/test-gitlab/)

Would you be able to read over the documentation and give `wflow_use_gitlab()` a quick test run? These changes are on the dev branch (`devtools::install_github("jdblischak/workflowr@dev")`).

* [GitLab vignette](https://github.com/jdblischak/workflowr/blob/dev/vignettes/wflow-06-gitlab.Rmd)
* [wflow_use_gitlab()](https://github.com/jdblischak/workflowr/blob/dev/R/wflow_use_gitlab.R)

I've also made a lot of changes to the workflowr report, so I'd also appreciate any feedback you might have on the new layout (https://github.com/jdblischak/workflowr/issues/110#issuecomment-453233028).

**Comment by jdblischak** [comment]
> Only thing I noticed is that when wflow_git_push() asks for username/password it say GitHub rather than Gitlab.

@lazappi Good catch! I used SSH keys, so I didn't see that prompt. I went through and updated this for all the messages and the man pages (https://github.com/jdblischak/workflowr/commit/b800bf3ac0aab148ef411761d527b0882d9cede7). Next I'll need to update the vignettes.

**Comment by jdblischak** [comment]
Support for GitLab has been added in workflowr 1.2.0. I also just pushed commit 1be27c513500febdfedb5ef82d04ca32c15f6691 to mention GitLab more often in the documentation.
