### ISSUE TITLE
Change <title></title> for all pages

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#49]
It would be nice to have the option to set the title for all webpages in `_site.yml`, or perhaps set `<title>` using the `name` variable in `_site.yml`; e.g., for [the Divvy workflowr repo](https://pcarbo.github.io/wflow-divvy), add `<title>Divvy data exploration</title>` to all webpages. I have no idea how difficult this would be to do using the `rmarkdown` package.

**Comment by jdblischak** [comment]
The only options that can be easily shared across documents are arguments to `html_document()`. These do not include the YAML options `title`, `author`, and `date`. Since "Divvy data exploration" is in the navigation bar, I think the easiest way to achieve what you want is to delete the `title` entry in the YAML header of your documents, which makes the focus at the top of the page the navbar with its title.

**Comment by pcarbo** [comment]
@jdblischak I looked at the website again, and actually I am happy with most of the page titles. For the "overview" page, I did not set a title (although I later added a title). Indeed, the title was empty in `index.html`, but (in Firefox at least) the title showed up as the full URL (`https://pcarbo.github.io/wflow-divvy/index.html`), which is not very nice. Was I following your suggestion correctly?

I was thinking it might be nice to have a "default" title throughout, but if this isn't straightforward in R Markdown, feel free to close the issue.

**Comment by jdblischak** [comment]
> Indeed, the title was empty in index.html, but (in Firefox at least) the title showed up as the full URL (https://pcarbo.github.io/wflow-divvy/index.html), which is not very nice.

I agree that showing the full URL as the title does not look good. I tried to quickly replicate this by deleting `title: "Home"`, building the page, and viewing in Firefox. However I didn't see the URL displayed. Could you create a small demo repo and send a link to this Issue?

**Comment by pcarbo** [comment]
@jdblischak See [this page](https://pcarbo.github.io/wflow-divvy) now for a reproducible example (commit id `fb5ab7d`).

**Comment by jdblischak** [comment]
I don't see the full URL as the title. The screenshot below is what I observe with Firefox 54.0 on Ubuntu 17.04.

![screenshot from 2017-07-10 14-08-05](https://user-images.githubusercontent.com/1608317/28035178-46b52a12-6579-11e7-84ad-098953f533b2.png)

**Comment by pcarbo** [comment]
Do you have the title bar option enabled in Firefox? Otherwise, <title> typically shows up in the browser tabs, e.g., compare the tabs for these two pages:

![screenshot](https://user-images.githubusercontent.com/1503904/28036249-3efa3e94-657d-11e7-99a5-749fdd564e7d.png)

**Comment by jdblischak** [comment]
Ah, OK. I see now. I don't have the title bar option enabled, but I can see that the full URL is what is displayed in the tab.

![screenshot from 2017-07-10 14-44-35](https://user-images.githubusercontent.com/1608317/28036586-534e279c-657e-11e7-94ef-8d1463f0fdb1.png)

Since sharing the title across pages is not easily achieved with rmarkdown, I am not going to implement this at the moment. One of my design goals is that if a user wants to stop using workflowr, they can switch to just using `rmarkdown::render_site()` to build their website (which is why [chunks.R](https://github.com/jdblischak/workflowr/blob/a5ad1dc2a51734137f00c2a756f5bf2aae6d8ceb/inst/infrastructure/analysis/chunks.R) is so verbose since I don't want that functionality to be trapped inside workflowr functions).
