### ISSUE TITLE
Two types of Rmd files

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#55]
Hi John,

I would like to organize `Rmd` files in a `workflowr` repo by two categories:

1. the regular `Rmd` files that are saved under `analysis` folder: these files generate `html` files for the website (saved under `docs` folder);

2. `Rmd` files generate `pdf` and/or `html` files (saved under `docs/assets` folder).

please see two examples below.

Here two major questions are:

1. Where should I keep Type 2 `Rmd` files?

2. How could I tell `workflowr` to save the output files of Type 2 `Rmd` files in `docs/assets`?    

I wonder if you could let me know how to do this within current version of `workflowr` at your convenience. Thanks!

### Example 1: Research

- Type 1 `Rmd` files: progress documents of a research project (e.g. https://xiangzhu.github.io/breast-cancer/) 

- Type 2 `Rmd` files: presentations for this project (e.g. https://xiangzhu.github.io/breast-cancer/assets/OLOPADE_20170613.html) 

### Example 2: Teaching

- Type 1 `Rmd` files: lecture notes for a class

- Type 2 `Rmd` files: slides (`html` files) and assignments (`pdf` files) for this class

**Comment by jdblischak** [comment]
Good question, @xiangzhu. workflowr is designed to be flexible so that it can co-exist in the same Git repository as files built using a different framework.

> Where should I keep Type 2 Rmd files?

You can save non-workflowr Rmd files anywhere in the project except `analysis/`. Using your example, you could save them in another top level subdirectory, e.g. `breast-cancer/assets/`, or in a subdirectory of `analysis/`, e.g. `breast-cancer/analysis/assets/`.

> How could I tell workflowr to save the output files of Type 2 Rmd files in docs/assets?

As these files aren't part of the workflowr framework, it would be difficult for the workflowr functions to determine what exactly to do with them. Technically, `wflow_build()` passes all the files to `rmarkdown::render_site()`, which wouldn't work for slides or PDF documents. How about creating a custom Makefile to support this? For example, the following Makefile creates the file `docs/assets/file.pdf` from the source Rmd file `assets/file.Rmd`.

```
target := assets/docs/file.pdf
source := assets/file.Rmd

$(target): $(source)
	Rscript -e 'library("rmarkdown"); render("$<", output_file = "$@", pdf_document())'
```

Running `make` in the Terminal from the root of the project directory would build the file (below run in "dry run" mode with the `-n` flag:

```
$ make -n
Rscript -e 'library("rmarkdown"); render("assets/file.Rmd", output_file = "assets/docs/file.pdf", pdf_document())'
```

And then you could manually `git add/commit` the files.

**Comment by xiangzhu** [comment]
@jdblischak  Thanks for the reply!

Regarding the second question, I like the idea of having a separate Makefile; it is a more general and principled solution. I am curious whether this can be done with Rstudio (i.e. clicking the "knit" button). 

Specifically, I have Rmd files saved in `breast-cancer/assets/`, and I would like the output files saved in `docs/assets`. If I simply click the "knit" button, the output files will be save in `breast-cancer/assets/`. Is there any way to tell Rstudio to save the output files in `docs/assets` when I click the "knit"?

**Comment by pcarbo** [comment]
@jdblischak It seems like the simplest solution is to put the "Type 2" files in a separate folder, and workflowr accommodates this well. 

John, here you have demonstrated using a Makefile for the non-workflowr files. What about adding the workflowr files here as well (i.e., the files that are processed using `wflow_publish`). Would that be a good idea (for more advanced users)? Maybe I should demonstrate this in `pcarbo/wflow-divvy`?

**Comment by jdblischak** [comment]
> Regarding the second question, I like the idea of having a separate Makefile; it is a more general and principled solution. I am curious whether this can be done with Rstudio (i.e. clicking the "knit" button).

@xiangzhu Yes, you can automate this with RStudio. After saving the `Makefile` in the root of your workflowr project, in the RStudio IDE go to "Build" -> "Configure Build Tools..." and then choose "Makefile" from the drop-down menu. Then you can click on "Build All" in the Build pane (it will show up next to the Git pane), or type "Ctrl-Shift-B" to execute the Makefile. Please let me know if you have any trouble setting this up.

> What about adding the workflowr files here as well (i.e., the files that are processed using wflow_publish). Would that be a good idea (for more advanced users)?

@pcarbo I'd need some more details on the potential use case. I guess you could automate it with `wflow_publish(all = TRUE)` to always commit and build all tracked files. Is that what you were thinking?

**Comment by pcarbo** [comment]
> I'd need some more details on the potential use case. I guess you could automate it with wflow_publish(all = TRUE) to always commit and build all tracked files. Is that what you were thinking?

@jdblischak Thinking about this further, I don't think it makes sense to use `wflow_publish` inside a Makefile, as I originally suggested, because you would want to potentially customize the commit message each time, and frankly creating commits inside a Makefile seems strange to me (but maybe it is just me).

The more I think about it, I think it is a bad idea to have a Makefile for building the webpages because it would end up subverting the Best Practices were are trying to encourage within the `workflowr` interface. Unless you can think of a simple Makefile that would integrate well with `workflowr`.

**Comment by jdblischak** [comment]
> The more I think about it, I think it is a bad idea to have a Makefile for building the webpages because it would end up subverting the Best Practices were are trying to encourage within the workflowr interface. Unless you can think of a simple Makefile that would integrate well with workflowr.

@pcarbo I completely agree, which is why I wasn't sure what the intended use case would be where a Makefile would help.

**Comment by xiangzhu** [comment]
Hi John,

It seems that you and Peter had some follow-up discussions in this thread. Should I go with your suggestion (creating a separate Makefile), or should I wait at this moment? Thanks!

**Comment by jdblischak** [comment]
@xiangzhu Please go ahead and create a Makefile and try to connect it with the RStudio build tools. It would be great if you could report back on this Issue with your experience (and a link to your Makefile), since I'm sure others will be interested in a similar setup.

**Comment by jdblischak** [comment]
@xiangzhu Did you have any success with creating a Makefile to manage the non-workflowr R Markdown files for your project?

**Comment by xiangzhu** [comment]
No. After a second thought, I think it is better to keep `workflowr` framework as it is, and thus decide not to "customize" it by adding non-`workflowr` files.

**Comment by jdblischak** [comment]
> No. After a second thought, I think it is better to keep workflowr framework as it is, and thus decide not to "customize" it by adding non-workflowr files.

OK. Thanks for the update, @xiangzhu. To summarize this Issue:

It is possible to include non-workflowr R Markdown files (or really any files) in the same root directory as a workflowr project. Just make sure to save them in a directory other than `analysis/`, and to have them save results in `docs/` if you wish for the files to be accessible from the workflowr website. Essentially, workflowr will not interfere with any other files in the directory (e.g. you could have an R package in the same root directory), but it also will not assist with these other files (e.g. you could write your own Makefile to automate the process).
