### ISSUE TITLE
footer.html difference between versions

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#82]
When creating a new `workflowr` project using workflowr version 0.8.0, I notice that the `footer.html` file is different from previous versions; in addition, there is a new file `header.html` in `analysis/include` folder.

Instead of manually copying these files to previous `workflowr` projects, what is the fastest way of updating `footer.html` and adding `header.html`?

Thanks!

**Comment by jdblischak** [comment]
> When creating a new `workflowr` project using workflowr version 0.8.0, I notice that the `footer.html` file is different from previous versions; in addition, there is a new file `header.html` in `analysis/include` folder.

@xiangzhu Correct. These minor changes are described in the [NEWS](https://jdblischak.github.io/workflowr/news/index.html#miscellaneous). Briefly, the addition to the footer forces all equations to be TeX, and the addition to the header increases the spacing between sections.

> Instead of manually copying these files to previous `workflowr` projects, what is the fastest way of updating `footer.html` and adding `header.html`?

These are both minor improvements that most users will not even notice, so I didn't create a function to automatically update them (I'd have to write a lot of error handling, because I can't assume that users haven't added their own custom edits to these files). I'd recommend not bothering to update these files for past projects. But if you really want them, the quickest way is to manually copy-paste them and then run:

```
wflow_publish(c("analysis/include/footer.html", "analysis/include/header.html"), "Update website sytling", republish = TRUE)
```

**Comment by xiangzhu** [comment]
Thanks! Glad to know these are minor changes. I will not update them for previous projects.
