### ISSUE TITLE
Should figures be under version control in a workflowr project?

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#94]
Hi John -- I think this may be more of a git-related question than a `workflowr` question. But I start coming across this type of question a lot when using `workflowr` to organize projects.

Most of time the research results are summarized as figures, and it seems that `workflowr` put these figure files under version control -- I guess that's why we can view the updated figures in the generated website. Below is an example.

```bash
$ git status
On branch master
Your branch is ahead of 'origin/master' by 8 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   docs/figure/distr_logfc.Rmd/unnamed-chunk-2-1.png
	modified:   docs/figure/distr_logfc.Rmd/unnamed-chunk-3-1.png
	modified:   docs/figure/distr_logfc.Rmd/unnamed-chunk-4-1.png
	modified:   docs/figure/distr_logfc.Rmd/unnamed-chunk-5-1.png
	modified:   docs/figure/distr_logfc.Rmd/unnamed-chunk-6-1.png
	modified:   docs/figure/distr_logfc_zero.Rmd/unnamed-chunk-2-1.png
	modified:   docs/figure/distr_logfc_zero.Rmd/unnamed-chunk-3-1.png
	modified:   docs/figure/distr_logfc_zero.Rmd/unnamed-chunk-4-1.pn

$ git commit -m 'update pngs'
[master d1e9fc8] update pngs
 8 files changed, 0 insertions(+), 0 deletions(-)
 rewrite docs/figure/distr_logfc.Rmd/unnamed-chunk-2-1.png (98%)
 rewrite docs/figure/distr_logfc.Rmd/unnamed-chunk-3-1.png (98%)
 rewrite docs/figure/distr_logfc.Rmd/unnamed-chunk-4-1.png (98%)
 rewrite docs/figure/distr_logfc.Rmd/unnamed-chunk-5-1.png (98%)
 rewrite docs/figure/distr_logfc.Rmd/unnamed-chunk-6-1.png (98%)
 rewrite docs/figure/distr_logfc_zero.Rmd/unnamed-chunk-2-1.png (99%)
 rewrite docs/figure/distr_logfc_zero.Rmd/unnamed-chunk-3-1.png (97%)
 rewrite docs/figure/distr_logfc_zero.Rmd/unnamed-chunk-4-1.png (97%)
``` 

I wonder whether we should have these figures under version control. My intuition is that as long as the `*.Rmd` files are under version control, we don't really need to keep track of these previous figures. If we do need a previous figure at some point, we can just go back to find the corresponding `*.Rmd` and re-make the figure.

However, if I add `*.png` in `.gitignore`, I guess the figures will not be shown in the website, right?

I appreciate your time on this quite general question!

**Comment by pcarbo** [comment]
@xiangzhu The PNG files need to be committed to the repo, so do not add `*.png` to `.gitignore`.

**Comment by jdblischak** [comment]
@xiangzhu Thanks for the question! @pcarbo is right. Here are the reasons:

1. Practically the figure files need to be version controlled in order for them to be displayed on the website. This is because we are using GitHub to host the website files.
2. While in theory you could re-create the figures as long as you have the code and data files version-controlled, in practice this is much harder to do. Trying to re-create the same exact computational environment you had from even a year ago is very difficult. Furthermore, this version-controlled website is not just for you, but for your collaborators and colleagues as well. If I wanted to obtain an old version of one of your figures, I'd rather obtain it from the Git history than try to recreate your computational environment.

Some more thoughts:

1. Related to 1, we could get around this by uploading the figure files to a 3rd party service (e.g. Figshare). I have chosen not to do this since this would be one more account for the user to have to register before getting to try workflowr (and it'd be one more 3rd party website that I would have little control over if something changed or went wrong).
2. Related to 2, you can "freeze" your computational environment using a tool like Docker. But I leave the management of the computational environment to the user since there are multiple options for this, and workflowr can work alongside any of them (I personally use conda with my workflowr projects).

**Comment by xiangzhu** [comment]
@pcarbo @jdblischak  many thanks for your feedback on this! 

Yes, I understand that if I remove `*.png` files from version control, then these images will not be viewable.

**Comment by jdblischak** [comment]
@xiangzhu One last thought about your general question. You don't want to ever manually commit the image files created by workflowr (i.e. our line `$ git commit -m 'update pngs'` above). `wflow_publish()` will handle version controlling the relevant image files for each R Markdown file.

**Comment by xiangzhu** [comment]
@jdblischak  No, I never manually commit image files. However, when I am working on the same repo across **multiple machines**, there are sometimes a few "uncommitted" images showing up in the current working machine, like the example above. Moreover, these "uncommitted" images are associated with a "committed" `Rmd` file (handled by `wflow_publish()` in a previous machine).

**Comment by jdblischak** [comment]
> No, I never manually commit image files.

Great!

> However, when I am working on the same repo across multiple machines, there are sometimes a few "uncommitted" images showing up in the current working machine, like the example above. Moreover, these "uncommitted" images are associated with a "committed" Rmd file (handled by wflow_publish() in a previous machine).

Yes, it can be annoying how image files can accumulate when using workflowr. This should be reduced in the latest version (0.10.0). workflowr now cleans up the image files much better. If you see uncommitted image files for a given R Markdown file, run `wflow_publish` to clean them up (it will commit them if they are useful and remove them otherwise).

https://github.com/jdblischak/workflowr/blob/a2fa789241d7245170043c07e5af00bd8ccd6b3b/NEWS.md#miscellaneous

**Comment by xiangzhu** [comment]
Thanks! I will update all my machines to 0.10.0. This type of uncommitted image problem occurs for 0.9.0 and 0.8.0 IIRC.
