### ISSUE TITLE
Subdirectories under the `analysis`

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#99]
I wonder if I can create subdirectories under the `analysis` folder to organize `*.Rmd` files. Specifically, I wonder if I can create a `analysis_1` folder to collect all `*.Rmd` files related to Analysis 1, and a `analysis_2` folder to collect all `*.Rmd` files related to Analysis 2.

Ideally the rest should be the same. I `wflow_publish` and view everything in the `workflowr` website.

Currently I put everything under `analysis` and for some projects this folder becomes extremely large -- this makes it harder for me to quickly find a target `*.Rmd` file.

One solution would be to create a repo for `analysis_1` and another repo for `analysis_2`.

**Comment by jdblischak** [comment]
I agree that subdirectories would be nice, but they are actually quite complicated due to file paths (e.g. paths to figures and other supporting files). See the previous discussion here in #95.

The problem is that workflowr is built on top of the ability of `rmarkdown::render_site` to create websites from R Markdown files. `rmarkdown::render_site` requires a flat directory structure in which all website R Markdown files are in the same location as the files `_site.yml` and `index.Rmd`.

One way to aid with the organization is to use prefixes in place of the subdirectories, e.g. `1_file1.Rmd`, `1_file2.Rmd`, `2_file1.Rmd`, `2_file2.Rmd`.

One of the best parts of workflowr is that just about everything that works in plain R Markdown will work in a workflowr site. The downside of this great feature is that features unsupported by R Markdown will also be unsupported by workflowr.

**Comment by xiangzhu** [comment]
Thanks John!

I apologize for posting this redundant issue, since I did not go through all previous ones.

**Comment by jdblischak** [comment]
No worries, @xiangzhu! It's useful for me to know the features that workflowr users would like to see implemented. With some of the new changes that will be introduced in workflowr 1.0, I have some ideas on how subdirectories could be supported. The main reason I hesitate is that the solution would likely be complex, which would make it difficult not only to make sure the code runs robustly across all 3 operating systems, but I'd also need to make sure the documentation was clear enough to users.

And if you haven't had the chance, please do a quick experiment with the workflowr 1.0 release candidate and let me know what you think. You can quickly return to your current version afterwards.

```
# Install release candidate
devtools::install_github("jdblischak/workflowr@dev")

# Experiment
library("workflowr")
wflow_start("test1.0")
wflow_build()
?wflow_html

# Re-install stable release
devtools::install_github("jdblischak/workflowr")
```
